// DiT LoRA — reading an adapter and FUSING it into a diffusion transformer at
// load.
//
// Generalized from the LTX-2.5 IC-LoRA implementation (row LTX25-IC-LORA) into a
// model-agnostic seam (row ROAD-V1-DIT-LORA). Both LTX-2.5 and MiniMax-H3 are
// diffusion DiTs that materialize weights to host buffers then stage to device,
// so load-time fusion is the natural mechanism for both.
//
// Ported from Lightricks/LTX-2 @ fd4ded7f2d88d3da713abcdd4ad41ecc4a9314ca:
//
//   ltx-core loader/primitives.py:160-167   LoraPathStrengthAndSDOps
//   ltx-core loader/fuse_loras.py:99-116    aggregate_lora_products
//   ltx-core loader/fuse_loras.py:119-150   fuse_lora_weights
//   ltx-core loader/fuse_loras.py:183-204   the key shape and the products
//   ltx-pipelines iclora_utils.py:30-49     the reference-scale metadata
//   ltx-pipelines ic_lora.py:150-173        resolving factors across LoRAs
//
// ─── THIS IS NOT `include/vllm/lora/` ────────────────────────────────────────
//
// That subsystem is vLLM's runtime punica path: f32, slot-indexed, applied per
// token through `LinearMethodBase` (`punica.h:15-24`, `layers.h:26-28`). A DiT
// does not apply an adapter at runtime. It FUSES the delta into the weights at
// load and the adapter then has no runtime existence at all
// (`fuse_loras.py:119-150`). Mirroring vLLM's LoRA here would mirror the wrong
// upstream, so this is a separate path by decision rather than by oversight.
// The row's spec §1 records the argument.
//
// ─── THE ARITHMETIC, AND THE DTYPE THAT CARRIES IT ───────────────────────────
//
//     delta = (B1 * s1) @ A1  +  s2 * (B2 @ A2)  +  s3 * (B3 @ A3) + ...
//     W'    = W + delta
//
// The first term and the rest are written differently on purpose; see below.
//
// `B` is [out, rank], `A` is [rank, in], `W` is [out, in] row-major.
//
// **The accumulator is bfloat16, not f32.** All four of upstream's fuse rules
// set `aggregation_dtype=torch.bfloat16` — bf16 (`fuse_loras.py:71`), fp8-cast
// (`quantization/fp8_cast.py:239`), fp8-scaled-mm
// (`quantization/fp8_scaled_mm.py:189`) and NVFP4
// (`quantization/nvfp4/fuse.py:50`). An f32 accumulator here would be the exact
// defect AGENTS.md names: every token would still match and every golden would
// still pass while the path carried a precision upstream does not have.
//
// ─── TWO PRODUCT FORMS, AND WHY THE SECOND IS NOT THE FIRST ──────────────────
//
// Upstream's own docstring records that the FIRST product rounds differently
// from the rest — `matmul(B * strength, A)` against `addmm_(B, A, alpha=...)`
// (`fuse_loras.py:103-107`) — and BOTH are implemented here since row
// LTX25-LORA-FUSION. The difference is WHERE the strength enters:
//
//   first   `B * strength` is a bf16 tensor times a Python float, so the scaled
//           factor is ROUNDED TO BF16 BEFORE the matmul.
//   after   `alpha` is converted to the op math type (f32) and applied to the
//           f32 accumulation, so the ONLY rounding is the bf16 store.
//
// Reusing the first form for the rest is arithmetically plausible and WRONG:
// measured against the pinned module it moved 26 of 120 elements on the row's
// own fixture. No tolerance-based gate could report that, which is why the
// N-adapter case asserts a golden generated by EXECUTING `aggregate_lora_products`
// at the pin and asserts that the wrong form is separated from it.
//
// WHICH FORM APPLIES IS PER TENSOR, not per load. `_products_for_sd_key` skips a
// LoRA that does not carry the key (`fuse_loras.py:200-201`), so the second
// adapter of a two-adapter load takes the FIRST form on a tensor only it
// targets.
//
// ─── THE CONTRACT NAME REWRITE IS PER MODEL ──────────────────────────────────
//
// ComfyUI LoRA adapters carry a model-specific prefix before the module name.
// `DitLoraContractName` strips any prefix from the caller-supplied `prefixes`
// list, then rewrites `.lora_{A,B}.weight` to `.weight`. For LTX-2.5 the prefix
// is `{"diffusion_model."}` (LTXV_LORA_COMFY_RENAMING_MAP, sd_ops.py:136). For
// MiniMax-H3 it is `{"model.diffusion_model.", "diffusion_model."}`. The prefix
// set is passed to `DitLoraAdapter::Open` by the model's loader.
#pragma once

#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include "vt/dtype.h"
#include "vt/tensor.h"

namespace vllm {

class SafetensorsFile;

// LoraPathStrengthAndSDOps (loader/primitives.py:160-167). `sd_ops` has no
// field here because the only map upstream ever passes for LTX is
// LTXV_LORA_COMFY_RENAMING_MAP (`sd_ops.py:135-137`, used at `args.py:172`),
// whose entire content is stripping a `diffusion_model.` prefix — so it is
// applied unconditionally by `DitLoraContractName` rather than carried.
struct DitLoraSpec {
  std::string path;
  // DEFAULT_LORA_STRENGTH (utils/args.py, quoted into --lora's help at :605-608).
  double strength = 1.0;
};

// The reference scale factors an IC-LoRA was TRAINED with, read from the
// adapter's own `__metadata__` (iclora_utils.py:30-49). Both default to 1, which
// is upstream's default for an absent key.
struct DitLoraReferenceFactors {
  int64_t downscale = 1;
  int64_t temporal = 1;
};

// One `A`/`B` factor pair, already resolved onto the DiT contract's tensor name.
struct DitLoraFactorPair {
  // The CONTRACT name this pair fuses into, e.g.
  // "transformer_blocks.0.attn1.to_q.weight".
  std::string target;
  int64_t out_features = 0;
  int64_t rank = 0;
  int64_t in_features = 0;
  // [out, rank] and [rank, in], row-major, bf16 bit patterns. Held bf16 because
  // that is the dtype the products are formed in (`fuse_loras.py:202-203` casts
  // both to the rule's `aggregation_dtype` before the matmul).
  std::vector<uint16_t> b;
  std::vector<uint16_t> a;
};

// One loaded adapter file.
class DitLoraAdapter {
 public:
  // Read `spec.path`, resolve every `.lora_A.weight` / `.lora_B.weight` pair
  // onto a contract name, and keep the file's whole `__metadata__`.
  //
  // `contract` is the set of tensor names the DiT actually binds. A pair whose
  // target is not in it REFUSES BY NAME. Upstream instead SKIPS it
  // (`fuse_loras.py:135-137`, `if original_weight is None: continue`) because
  // its state dict is the whole model and a skip is unambiguous there. Here the
  // contract is a fixed enumerated set with unported modules already stripped,
  // so a skip would absorb a misnamed key and a genuinely inapplicable one
  // alike — and the first is the failure this project keeps paying for.
  //
  // `prefixes` is the set of ComfyUI prefixes to strip before the
  // `.lora_{A,B}.weight` -> `.weight` rewrite. For LTX-2.5 it is
  // `{"diffusion_model."}`; for MiniMax-H3 it is
  // `{"model.diffusion_model.", "diffusion_model."}`.
  static DitLoraAdapter Open(const DitLoraSpec& spec,
                              const std::vector<std::string>& contract,
                              const std::vector<std::string>& prefixes);

  const std::string& path() const { return path_; }
  double strength() const { return strength_; }
  const std::map<std::string, std::string>& metadata() const { return metadata_; }

  // The pair targeting `name`, or nullptr. One target at most: a duplicate is
  // refused at Open.
  const DitLoraFactorPair* Find(const std::string& name) const;

 private:
  std::string path_;
  double strength_ = 1.0;
  std::map<std::string, std::string> metadata_;
  std::vector<DitLoraFactorPair> pairs_;
};

// `<prefix><module>.lora_A.weight` -> `<module>.weight`, where `<prefix>` is any
// of `prefixes`. When no prefix matches, the key is used as-is. Returns false
// when `key` is not a LoRA factor.
//
// Mirrors LTXV_LORA_COMFY_RENAMING_MAP's prefix strip (`sd_ops.py:136`) composed
// with the `.lora_{A,B}.weight` -> `.weight` rewrite `_affected_weight_keys`
// performs (`fuse_loras.py:185-186`).
bool DitLoraContractName(const std::string& key,
                         const std::vector<std::string>& prefixes,
                         std::string* out_target, bool* out_is_a);

// One `__metadata__` integer factor, defaulting to 1 when the key is absent
// (iclora_utils.py:35, 46).
//
// Upstream swallows EVERY failure and returns 1 (`iclora_utils.py:36-38`,
// `except Exception: ... return 1`). A malformed value is refused by name here
// instead, because the two factors silently reverting to 1 place the reference
// plausibly and wrongly — which is the failure mode the reference refusal was
// written to prevent in the first place. Absent still means 1; only malformed
// differs.
int64_t DitReadLoraMetadataFactor(const std::map<std::string, std::string>& metadata,
                                   const std::string& key, const std::string& path);

// Resolve the reference factors across the adapters, mirroring ic_lora.py:150-173
// including its conflict errors (`:158-163`, `:167-172`).
//
// N adapters, in the order the load supplied them. `dubit.py:364-365` and
// `hdr_ic_lora.py:271-272` narrow their OWN entry points to exactly one adapter;
// `ICLoraPipeline` takes a list (`ic_lora.py:75`), `dfr_pipeline.py:212` builds
// `(*user_loras, *distilled_lora)`, and `--lora` is repeatable
// (`utils/args.py:600-611`). Row LTX25-LORA-FUSION lifted the arity cap this
// function used to enforce, which is what makes both conflict branches
// reachable.
DitLoraReferenceFactors DitResolveLoraReferenceFactors(
    const std::vector<DitLoraAdapter>& adapters);

// Add every adapter's delta for `target` into `buffer`, which holds `rows*cols`
// elements of `dtype` as produced by the model's materializer. Returns true when
// anything was fused.
//
// This is `fuse_lora_weights` (`fuse_loras.py:119-150`) collapsed onto one
// already-materialized tensor: the aggregation is bf16, the add is upstream's
// `deltas.add_(weight)` and the store is its `.to(dtype=weight.dtype)`
// (`fuse_loras.py:67-68`).
bool DitFuseLoraIntoTensor(const std::vector<DitLoraAdapter>& adapters,
                            const std::string& target, vt::DType dtype, int64_t rows,
                            int64_t cols, uint8_t* buffer, size_t buffer_bytes);

// ── per-load fusion helpers ────────────────────────────────────────────────
//
// The three steps every DiT loader performs around the materialize loop. They
// are model-agnostic: a loader passes its own tensor-spec type's `name` and
// `shape` fields, and its model's ComfyUI `prefixes`. LTX2.5 and MiniMax-H3
// both call these; no loader has its own copy.

// Open every requested adapter against the contract this load will bind, and
// resolve the reference factors. `contract_names` is the set of tensor names
// the DiT actually binds; `prefixes` is the ComfyUI prefix set to strip.
std::vector<DitLoraAdapter> DitOpenLoras(
    const std::vector<DitLoraSpec>& specs,
    const std::vector<std::string>& contract_names,
    const std::vector<std::string>& prefixes);

// Fuse LoRA deltas into one tensor's host buffer. Returns false (no-op) when
// the tensor is not rank 2 or no adapters are loaded — a shape filter, not a
// silent skip of a possible target, because `DitLoraAdapter::Open` has already
// refused a pair naming a tensor outside the contract.
bool DitFuseLorasIntoBuffer(
    const std::vector<DitLoraAdapter>& loras,
    const std::string& name, const std::vector<int64_t>& shape,
    vt::DType dtype, uint8_t* buffer, size_t buffer_bytes);

// Refuse adapters that fused into zero tensors. A LoRA that fused nothing
// renders identically to no LoRA at all, so reporting success is the failure.
void DitCheckLorasWereApplied(
    const std::vector<DitLoraAdapter>& loras, int64_t fused);

// The extras-map keys every DiT family uses for load-time LoRA. LTX2.5 defines
// `kLtx2LoraPathExtra` / `kLtx2LoraStrengthExtra` as aliases of these; H3 uses
// them directly. The spelling mirrors upstream's repeatable `--lora PATH [STRENGTH]`
// (`utils/args.py:600-611`): adapter 1 is the unindexed `lora_path` / `lora_strength`,
// adapter N >= 2 is `lora_path_<N>` / `lora_strength_<N>`.
inline constexpr char kDitLoraPathExtra[] = "lora_path";
inline constexpr char kDitLoraStrengthExtra[] = "lora_strength";

// The model-load extra that tells the engine where to resolve prompt-tag LoRA
// names to safetensors files. Mirrors sd.cpp's `lora_dir` (gosd.cpp:110-158).
// Rides in `VideoModelParams.extras` (LTX2) or `MiniMaxH3VideoModelParams.extras`
// (H3) — a model-load knob, not a per-generation extra.
inline constexpr char kDitLoraDirExtra[] = "lora_dir";

// Read `lora_path[_<N>]` / `lora_strength[_<N>]` from the extras map and return
// one `DitLoraSpec` per adapter, in index order. A gap in the sequence refuses
// by name, as does a `lora_strength_<N>` without its `lora_path_<N>`.
//
// This is the shared resolution that LTX2.5's `ResolveLoraSpecs` and H3's video
// engine both call. The function is model-agnostic: the prefix stripping happens
// later, in `DitLoraAdapter::Open`.
std::vector<DitLoraSpec> ResolveDitLoraSpecs(
    const std::map<std::string, std::string>& extras);

// True when `key` is `lora_path_<N>` or `lora_strength_<N>` with N >= 2 — the
// indexed spelling of a DiT LoRA extra. Each family's extras-validation pass
// calls this to recognize the repeatable family without listing it in a fixed
// array, since upstream's `--lora` has no arity bound.
bool IsDitLoraIndexedExtra(const std::string& key);

// True when `key` is any DiT LoRA extra: the base `lora_path` / `lora_strength`
// (index 1, no suffix) or any indexed variant `lora_path_<N>` / `lora_strength_<N>`
// (N >= 2). Use this to pass through the full LoRA family in a conversion that
// filters extras, so the first adapter is not silently dropped.
bool IsDitLoraExtra(const std::string& key);

// ── runtime prompt-activated LoRA (ROAD-V1-LORA-RUNTIME) ─────────────────────
//
// Load-time fusion (above) bakes adapter deltas into the base weights at load.
// Runtime activation applies a per-forward additive delta WITHOUT modifying base
// weights, so different requests can use different LoRAs without reloading.
//
// The prompt carries `<lora:name:strength>` tags; the engine strips them,
// resolves each name to a safetensors file, and applies the delta at each linear
// projection during the denoise loop. This mirrors vLLM-Omni's
// DiffusionLoRAManager (per-layer additive delta, base_linear.py:69-134) and
// LocalAI stable-diffusion.cpp's parse_loras_from_prompt (gosd.cpp:174-330).

// One resolved runtime LoRA spec: a file path and a strength, from parsing
// prompt tags. Duplicate adapters (same normalized path) accumulate strengths.
struct DitRuntimeLoraSpec {
  std::string path;
  double strength = 1.0;
};

// The result of parsing prompt tags: the resolved specs and the cleaned prompt
// (tags stripped, whitespace collapsed).
struct DitParseLoraResult {
  std::vector<DitRuntimeLoraSpec> loras;
  std::string clean_prompt;
};

// Parse `<lora:name:strength>` tags from `prompt`, resolve each name to a file
// path via `lora_dir`, and return the specs plus the cleaned prompt.
//
// Name resolution mirrors LocalAI sd.cpp's discover_lora_files + fallback chain
// (gosd.cpp:110-158, 174-330): exact filename in `lora_dir`, absolute path,
// case-insensitive match, relative path under `lora_dir`, extension probing
// (`.safetensors`). Duplicate LoRAs (same normalized path) accumulate strengths.
// A name that cannot be resolved is refused by name.
DitParseLoraResult DitParseLoraTags(const std::string& prompt,
                                     const std::string& lora_dir);

// One layer's runtime LoRA factors, already on the compute device. The tensors
// are non-owning views (`vt::Tensor`); the backing device memory is owned by the
// model context that constructed the state. `lora_a` is [rank, in_features],
// `lora_b` is [out_features, rank].
//
// The alpha/rank scaling is folded into `lora_b` at load time (mirrors
// vLLM-Omni's optimize, manager.py:320), so the per-forward delta is a plain
// `(x @ A^T) @ B^T` with no scaling. The `strength` is the prompt-tag strength,
// also folded into `lora_b` at load.
struct DitRuntimeLoraLayer {
  vt::Tensor lora_a;
  vt::Tensor lora_b;
  float strength = 1.0;
};

// All loaded runtime LoRA layers for one generation, keyed by contract target
// name (the same name `DitLoraContractName` produces). The forward path looks
// up each linear's target name via `Find`; a nullptr return means no runtime LoRA
// applies to that layer.
struct DitRuntimeLoraState {
  bool empty() const { return layers.empty(); }
  const DitRuntimeLoraLayer* Find(const std::string& target) const {
    auto it = layers.find(target);
    return it != layers.end() ? &it->second : nullptr;
  }
  std::map<std::string, DitRuntimeLoraLayer> layers;
  // Backing storage for factor data, populated by DitLoadRuntimeLoras. Map
  // elements are node-based (never move on insert), so vt::Tensor views into
  // them stay valid for the state's lifetime. Tests that construct layers by
  // hand leave these empty.
  std::map<std::string, std::vector<float>> a_storage;
  std::map<std::string, std::vector<float>> b_storage;
};

// Compute the runtime LoRA delta and add it to the output:
//   out += (a @ lora_a^T) @ lora_b^T
//
// `a` is [rows, in_features] (the reshaped input to the base linear),
// `lora_a` is [rank, in_features], `lora_b` is [out_features, rank].
// `out` points to [rows * out_features] f32 values that already hold the base
// linear output; the delta is added in place. A null `lora` is a no-op.
//
// This is the CPU path's delta computation (ROAD-V1-LORA-RUNTIME phase 2).
// The device path inlines the same formula with DBuf scratch, since device
// buffer allocation is model-specific. Mirrors vLLM-Omni's base_linear apply
// (base_linear.py:130-131): base weights are never touched.
void DitApplyRuntimeLoraDelta(vt::Queue& q, const vt::Tensor& a,
                               float* out, int64_t rows, int64_t out_features,
                               const DitRuntimeLoraLayer* lora);

// Open the runtime LoRA adapters named by `specs` and build a
// `DitRuntimeLoraState` whose layers are keyed by contract target name. Each
// adapter's A/B factors are read as f32; `alpha/rank` is folded into B when the
// adapter carries `lora_alpha` in its `__metadata__` (mirrors vLLM-Omni's
// `optimize()`, lora_weights.py:36-41), and `strength` is always folded into B.
// The result is a per-forward delta of `(x @ A^T) @ B_eff^T` with no scaling.
//
// `contract_names` is the set of tensor names the DiT actually binds;
// `prefixes` is the ComfyUI prefix set to strip (same as `DitLoraAdapter::Open`).
// Tensors are placed on `device` (CPU for now; device upload is a Phase 7 step).
DitRuntimeLoraState DitLoadRuntimeLoras(
    const std::vector<DitRuntimeLoraSpec>& specs,
    const std::vector<std::string>& contract_names,
    const std::vector<std::string>& prefixes, vt::Device device);

}  // namespace vllm
