// Frozen executing vLLM e126687a9a828d513c01a07cd69f025f27d63280 expressions.
// These boundaries are generated by torch.compile, so standalone layer tests
// cannot express their BF16 stores. See the fixture manifest and row evidence.
#include <doctest/doctest.h>

#include <cmath>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <limits>
#include <map>
#include <nlohmann/json.hpp>
#include <vector>

#include "vt/backend.h"
#include "vt/compiled_gemma.h"
#include "vt/recipes.h"
#ifdef VLLM_CPP_HIP
#include "vt/rocm/rocm_runtime.h"
#endif
namespace {
using Json = nlohmann::json;
using Path = std::filesystem::path;
const Path fixtures = Path(__FILE__).parent_path() / "fixtures/compiled_gemma";
std::vector<char> Read(const Path& path) {
  std::ifstream f(path, std::ios::binary);
  REQUIRE(f.good());
  return {std::istreambuf_iterator<char>(f), std::istreambuf_iterator<char>()};
}
struct FixtureBundle {
  const Json manifest = Json::parse(Read(fixtures / "manifest.json"));
  const std::vector<char> data = Read(fixtures / manifest.at("data_file").get<std::string>());
  FixtureBundle() { REQUIRE(data.size() == manifest.at("data_bytes").get<size_t>()); }
  std::vector<char> Slice(const Json& entry) const {
    const auto offset = entry.at("offset").get<size_t>();
    const auto size = entry.at("bytes").get<size_t>();
    REQUIRE(offset <= data.size());
    REQUIRE(size <= data.size() - offset);
    return {data.begin() + offset, data.begin() + offset + size};
  }
};
struct Storage {
  vt::Backend& backend;
  vt::Queue q;
  std::vector<void*> allocations;
  explicit Storage(vt::DeviceType device)
      : backend(vt::GetBackend(device)), q(backend.CreateQueue()) {}
  ~Storage() {
    backend.Synchronize(q);
    for (void* p : allocations) backend.Free(p);
    backend.DestroyQueue(q);
  }
  vt::Tensor Upload(const FixtureBundle& bundle, const Json& entry, bool poison) {
    auto bytes = bundle.Slice(entry);
    const auto shape = entry.at("shape").get<std::vector<int64_t>>();
    const auto dtype = entry.at("dtype") == "torch.int64" ? vt::DType::kI64 : vt::DType::kBF16;
    size_t size = vt::SizeOf(dtype);
    for (auto n : shape) {
      REQUIRE(n > 0);
      size *= n;
    }
    REQUIRE(bytes.size() == size);
    if (poison) {  // NaN output poison makes a deleted dispatch fail the comparison.
      REQUIRE(dtype == vt::DType::kBF16);
      for (size_t i = 0; i < bytes.size(); i += 2) {
        bytes[i] = char(0xc0);
        bytes[i + 1] = char(0x7f);
      }
    }
    void* p = backend.Alloc(bytes.size());
    allocations.push_back(p);
    backend.Copy(q, p, bytes.data(), bytes.size());
    backend.Synchronize(q);
    if (shape.size() == 1) return vt::Tensor::Contiguous(p, dtype, q.device, {shape[0]});
    if (shape.size() == 2) return vt::Tensor::Contiguous(p, dtype, q.device, {shape[0], shape[1]});
    REQUIRE(shape.size() == 3);
    return vt::Tensor::Contiguous(p, dtype, q.device, {shape[0], shape[1], shape[2]});
  }
  std::vector<uint16_t> Download(const vt::Tensor& t) {
    std::vector<uint16_t> values(t.Numel());
    backend.Copy(q, values.data(), t.data, values.size() * 2);
    backend.Synchronize(q);
    return values;
  }
};
void Run(vt::DeviceType device) {
  const FixtureBundle bundle;
  const auto& manifest = bundle.manifest;
  REQUIRE(manifest.at("pin") == "e126687a9a828d513c01a07cd69f025f27d63280");
  REQUIRE(manifest.at("cases").size() == 7);
  for (const auto& c : manifest.at("cases")) {
    const std::string kind = c.at("kind");
    if (device == vt::DeviceType::kCPU && kind == "qk") continue;
    INFO(c.at("name"));
    Storage s(device);
    std::map<std::string, vt::Tensor> t;
    for (auto it = c.begin(); it != c.end(); ++it) {
      if (!it.value().is_object() || !it.value().contains("offset")) continue;
      const std::string key = it.key();
      t.emplace(key,
                s.Upload(bundle, it.value(),
                         key.starts_with("out") || key == "res" || key == "qo" || key == "ko"));
    }
    std::vector<std::string> outputs;
    if (kind == "sandwich") {
      vt::FusedChain(s.q, t.at("out2"),
                     vt::SandwichNormInputs{t.at("a"), t.at("base"), t.at("wa"), t.at("w")}, 1e-6f);
      vt::FusedChain(s.q, t.at("out3"),
                     vt::SandwichNormInputs{t.at("a"), t.at("base"), t.at("wa"), t.at("w"),
                                            &t.at("delta"), &t.at("wd")},
                     1e-6f, &t.at("res"));
      outputs = {"out2", "out3", "res"};
      // The production call aliases the BF16 residual with base.
      const auto reference = s.Download(t.at("res"));
      vt::FusedChain(s.q, t.at("out3"),
                     vt::SandwichNormInputs{t.at("a"), t.at("base"), t.at("wa"), t.at("w"),
                                            &t.at("delta"), &t.at("wd")},
                     1e-6f, &t.at("base"));
      CHECK(s.Download(t.at("base")) == reference);
    } else if (kind == "scaled") {
      vt::FusedChain(s.q, t.at("out"), t.at("x"), t.at("w"),
                     vt::ScaledRmsNormArgs{c.at("scale"), 1e-6f}, t.at("res"));
      outputs = {"out", "res"};
    } else if (kind == "gelu") {
      vt::CompiledGeluErfMul(s.q, t.at("out"), t.at("x"));
      outputs = {"out"};
    } else {
      REQUIRE(kind == "qk");
      const int64_t rows = c.at("rows");
      auto q2 =
          vt::Tensor::Contiguous(t.at("qo").data, vt::DType::kBF16, s.q.device, {rows * 8, 256});
      auto k2 =
          vt::Tensor::Contiguous(t.at("ko").data, vt::DType::kBF16, s.q.device, {rows * 4, 256});
      for (int64_t row = 0; row < rows; ++row) {
        s.backend.Copy(s.q, static_cast<char*>(q2.data) + row * 4096,
                       static_cast<char*>(t.at("qkv").data) + row * 8192, 4096);
        s.backend.Copy(s.q, static_cast<char*>(k2.data) + row * 2048,
                       static_cast<char*>(t.at("qkv").data) + row * 8192 + 4096, 2048);
      }
      vt::FusedBinding binding{};
      binding.n = 8;
      binding.op[0] = &q2;
      binding.op[1] = &t.at("qw");
      binding.op[2] = &k2;
      binding.op[3] = &t.at("kw");
      binding.op[4] = &t.at("qo");
      binding.op[5] = &t.at("ko");
      binding.op[6] = &t.at("cs");
      binding.op[7] = &t.at("pos");
      vt::FusedParams params{};
      params.eps = 1e-6f;
      params.rope.rotary_dim = 256;
      vt::FusedChain(s.q, vt::kAttnQkNormRopeGemma, binding, params);
      outputs = {"qo", "ko"};
    }
    for (const auto& name : outputs) {
      INFO(name);
      const auto got = s.Download(t.at(name));
      const auto expected_bytes = bundle.Slice(c.at(name));
      REQUIRE(got.size() * 2 == expected_bytes.size());
      std::vector<uint16_t> expected(got.size());
      std::memcpy(expected.data(), expected_bytes.data(), expected_bytes.size());
      CHECK(got == expected);
    }
  }
}
}  // namespace
TEST_CASE("compiled Gemma frozen primary expressions on CPU") {
  Run(vt::DeviceType::kCPU);
}
#ifdef VLLM_CPP_HIP
TEST_CASE("compiled Gemma frozen primary expressions on ROCm") {
  REQUIRE(vt::rocm::DeviceAvailable());
  Run(vt::DeviceType::kROCM);
}
#endif

#ifdef VLLM_CPP_HIP
TEST_CASE("Gemma device RoPE caches match the executing primary") {
  REQUIRE(vt::rocm::DeviceAvailable());
  const FixtureBundle bundle;
  const auto& manifest = bundle.manifest;
  REQUIRE(manifest.at("pin") == "e126687a9a828d513c01a07cd69f025f27d63280");
  REQUIRE(manifest.at("rope_cache").size() == 2);
  for (const auto& c : manifest.at("rope_cache")) {
    INFO(c.at("name"));
    Storage s(vt::DeviceType::kROCM);
    const auto positions = c.at("positions").get<std::vector<int64_t>>();
    const int64_t rows = positions.size();
    auto allocate = [&](vt::DType dtype, std::initializer_list<int64_t> shape) {
      size_t bytes = vt::SizeOf(dtype);
      for (auto n : shape) bytes *= n;
      void* p = s.backend.Alloc(bytes);
      s.allocations.push_back(p);
      return vt::Tensor::Contiguous(p, dtype, s.q.device, shape);
    };
    auto pos = allocate(vt::DType::kI64, {rows});
    auto cache = allocate(vt::DType::kF32, {rows, 256});
    auto narrowed = allocate(vt::DType::kBF16, {rows, 256});
    s.backend.Copy(s.q, pos.data, positions.data(), positions.size() * sizeof(int64_t));
    vt::RopeArgs args;
    args.rotary_dim = 256;
    args.base = c.at("base");
    args.linear_scaling_factor = c.at("factor");
    vt::RopeCosSinCache(s.q, cache, pos, args);
    vt::CastBf16(s.q, narrowed, cache);
    const auto got = s.Download(narrowed);
    const auto expected = bundle.Slice(c);
    REQUIRE(got.size() * sizeof(uint16_t) == expected.size());
    CHECK(std::memcmp(got.data(), expected.data(), expected.size()) == 0);
  }
}
#endif

TEST_CASE("RoPE cache rejects invalid scaling before dispatch") {
  float storage[4]{};
  int64_t position = 0;
  vt::Queue queue{{vt::DeviceType::kCPU, 0}, nullptr};
  auto cache = vt::Tensor::Contiguous(storage, vt::DType::kF32, queue.device, {1, 4});
  auto pos = vt::Tensor::Contiguous(&position, vt::DType::kI64, queue.device, {1});
  vt::RopeArgs args;
  args.rotary_dim = 4;
  for (float invalid : {-1.f, INFINITY, NAN}) {
    args.linear_scaling_factor = invalid;
    CHECK_THROWS_WITH(
        vt::RopeCosSinCache(queue, cache, pos, args),
        doctest::Contains("rope_cos_sin_cache: linear factor must be finite and nonnegative"));
  }
  args.linear_scaling_factor = 8.f;
  args.llama3_scaling_factor = 8.f;
  CHECK_THROWS_WITH(
      vt::RopeCosSinCache(queue, cache, pos, args),
      doctest::Contains("rope_cos_sin_cache: linear and Llama-3 scaling are mutually exclusive"));
  args.llama3_scaling_factor = 0.f;
  args.base = 0.f;
  CHECK_THROWS_WITH(vt::RopeCosSinCache(queue, cache, pos, args),
                    doctest::Contains("rope_cos_sin_cache: base must be finite and positive"));
}

TEST_CASE("compiled Gemma validates ownership and empty batches") {
  vt::Queue queue{{vt::DeviceType::kCPU, 0}, nullptr};
  uint16_t storage[64]{};
  auto row = [&](uint16_t* p) {
    return vt::Tensor::Contiguous(p, vt::DType::kBF16, queue.device, {2, 4});
  };
  auto x = row(storage), base = row(storage + 8), out = row(storage + 16);
  auto res = row(storage + 24), delta = row(storage + 32);
  auto weight = vt::Tensor::Contiguous(storage + 48, vt::DType::kBF16, queue.device, {4});
  vt::ScaledRmsNormArgs scaled{2.f, 1e-6f};
  CHECK_THROWS_WITH(vt::FusedChain(queue, x, x, weight, scaled, res),
                    doctest::Contains("scaled norm outputs overlap inputs"));
  auto partial = row(storage + 1);
  CHECK_THROWS_WITH(vt::FusedChain(queue, partial, x, weight, scaled, res),
                    doctest::Contains("scaled norm outputs overlap inputs"));
  for (float invalid : {0.f, -1.f, INFINITY, NAN}) {
    scaled.scale = invalid;
    CHECK_THROWS_WITH(vt::FusedChain(queue, out, x, weight, scaled, res),
                      doctest::Contains("scale must be finite and positive"));
  }
  scaled.scale = 2.f;
  auto oversized = x;
  oversized.shape[0] = std::numeric_limits<int64_t>::max();
  CHECK_THROWS_WITH(vt::FusedChain(queue, out, oversized, weight, scaled, res),
                    doctest::Contains("row storage overflow"));
  auto wrong = x;
  wrong.dtype = vt::DType::kF32;
  CHECK_THROWS_WITH(vt::FusedChain(queue, out, wrong, weight, scaled, res),
                    doctest::Contains("expected contiguous BF16"));
  auto missing = vt::SandwichNormInputs{x, base, weight, weight, &delta, nullptr};
  CHECK_THROWS_WITH(vt::FusedChain(queue, out, missing, 1e-6f),
                    doctest::Contains("delta requires its normalization weight"));
  auto inputs = vt::SandwichNormInputs{x, base, weight, weight};
  partial = row(storage + 9);
  CHECK_THROWS_WITH(vt::FusedChain(queue, out, inputs, 1e-6f, &partial),
                    doctest::Contains("residual may alias only the complete base tensor"));
  CHECK_THROWS_WITH(vt::FusedChain(queue, out, inputs, NAN),
                    doctest::Contains("epsilon must be finite and nonnegative"));
  CHECK_THROWS_WITH(vt::CompiledGeluErfMul(queue, x, x),
                    doctest::Contains("expected contiguous BF16"));
  auto packed = vt::Tensor::Contiguous(storage, vt::DType::kBF16, queue.device, {2, 8});
  CHECK_THROWS_WITH(vt::CompiledGeluErfMul(queue, x, packed),
                    doctest::Contains("output overlaps input"));
  // Contiguous() rejects zero dimensions; a caller can still pass an empty view.
  auto empty = x;
  empty.data = nullptr;
  empty.shape[0] = 0;
  CHECK_NOTHROW(vt::FusedChain(queue, empty, empty, weight, scaled, empty));
  CHECK_NOTHROW(
      vt::FusedChain(queue, empty, vt::SandwichNormInputs{empty, empty, weight, weight}, 1e-6f));
}
