// vLLM test_pos_encoding.py and allclose_default.py @ e126687a9a828d51.
// Frozen arrays are generated by tools/gemma3_linear_rope/primary.py.
#include <doctest/doctest.h>

#include <cmath>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <limits>
#include <vector>

#include <nlohmann/json.hpp>
#include "vllm/model_executor/layers/rotary_embedding/linear_scaling_rope.h"
#include "vt/dtype.h"

namespace {
using vllm::LinearScalingRotaryEmbedding;
constexpr vt::Device cpu{vt::DeviceType::kCPU, 0};

struct Buffer {
  std::vector<float> f32;
  std::vector<uint16_t> bf16;
  vt::Tensor tensor;
  Buffer(const std::vector<float>& values, vt::DType dtype, int64_t heads) {
    f32 = values;
    if (dtype == vt::DType::kBF16)
      for (float x : values) bf16.push_back(vt::F32ToBF16(x));
    void* data = dtype == vt::DType::kBF16 ? static_cast<void*>(bf16.data()) : f32.data();
    tensor = vt::Tensor::Contiguous(data, dtype, cpu, {4, heads, 16});
  }
};

void Compare(const vt::Tensor& got, const std::vector<float>& expected) {
  REQUIRE(static_cast<size_t>(got.Numel()) == expected.size());
  // These are the primary test's dtype-specific tolerances, unchanged.
  const bool bf16 = got.dtype == vt::DType::kBF16;
  const float atol = bf16 ? 1e-3F : 1e-5F;
  const float rtol = bf16 ? 1.6e-2F : 1.3e-6F;
  for (size_t i = 0; i < expected.size(); ++i) {
    const float value = bf16 ? vt::BF16ToF32(got.Ptr<uint16_t>()[i]) : got.Ptr<float>()[i];
    INFO("element " << i << ": " << value << " expected " << expected[i]);
    REQUIRE(std::isfinite(value));
    CHECK(std::abs(value - expected[i]) <= atol + rtol * std::abs(expected[i]));
  }
}
}  // namespace

TEST_CASE("linear RoPE matches pinned primary cache and rotation arrays") {
  const auto path = std::filesystem::path(__FILE__).parent_path() / "fixtures/linear_rope.json";
  std::ifstream input(path);
  REQUIRE(input.good());
  nlohmann::json fixture;
  input >> fixture;
  REQUIRE(fixture.at("cases").size() == 12);
  for (const auto& entry : fixture.at("cases")) {
    const auto factors = entry.at("factors").get<std::vector<double>>();
    const auto dtype = entry.at("dtype") == "bfloat16" ? vt::DType::kBF16 : vt::DType::kF32;
    LinearScalingRotaryEmbedding rope(16, 8, 17, 1000000., entry.at("neox"), factors, dtype);
    INFO("dtype=" << entry.at("dtype") << " factors=" << entry.at("factors")
         << " neox=" << entry.at("neox"));
    CHECK(rope.cache_rows() == entry.at("rows").get<int64_t>());
    for (const auto& item : entry.at("offsets").items())
      CHECK(rope.scaling_factor_to_offset().at(std::stod(item.key())) == item.value().get<int64_t>());
    Compare(rope.cos_sin_cache(), entry.at("cache").get<std::vector<float>>());
    auto positions = entry.at("positions").get<std::vector<int32_t>>();
    auto pos = vt::Tensor::Contiguous(positions.data(), vt::DType::kI32, cpu, {4});
    Buffer q(entry.at("q").get<std::vector<float>>(), dtype, 2);
    Buffer k(entry.at("k").get<std::vector<float>>(), dtype, 1);
    vt::Queue queue{cpu, nullptr};
    rope.forward_native(queue, pos, q.tensor, &k.tensor);
    Compare(q.tensor, entry.at("q_out").get<std::vector<float>>());
    Compare(k.tensor, entry.at("k_out").get<std::vector<float>>());
    Buffer query_only(entry.at("q").get<std::vector<float>>(), dtype, 2);
    rope.forward_native(queue, pos, query_only.tensor);
    Compare(query_only.tensor, entry.at("q_out").get<std::vector<float>>());
  }
}

TEST_CASE("linear factory caches its effective factor and rejects invalid factors") {
  vllm::RopeParameters params;
  params.rope_type = "linear";
  params.rope_dim = 8;
  params.factor = 8.;
  auto scaled = vllm::get_rope(16, 17, true, params, vt::DType::kBF16);
  CHECK(scaled->type_name() == "LinearScalingRotaryEmbedding");
  CHECK(scaled->cache_rows() == 136);
  CHECK(vllm::get_rope(16, 17, true, params, vt::DType::kBF16) == scaled);
  params.factor = 1.;
  auto unscaled = vllm::get_rope(16, 17, true, params, vt::DType::kBF16);
  CHECK(unscaled != scaled);
  CHECK(unscaled->cache_rows() == 17);
  for (double factor : {0., -1., std::numeric_limits<double>::infinity(),
                         std::numeric_limits<double>::quiet_NaN()})
    CHECK_THROWS_AS(LinearScalingRotaryEmbedding(16, 8, 17, 10000., true,
        factor, vt::DType::kF32), std::invalid_argument);
  CHECK_THROWS_AS(LinearScalingRotaryEmbedding(16, 8, 17, 10000., true,
      std::vector<double>{}, vt::DType::kF32), std::invalid_argument);
  CHECK_THROWS_AS(LinearScalingRotaryEmbedding(16, 8, 17, 10000., true,
      1e300, vt::DType::kF32), std::overflow_error);
  params.factor.reset();
  CHECK_THROWS_AS(vllm::get_rope(16, 17, true, params), std::invalid_argument);
}
