#!/usr/bin/env python3
"""Emit tests/vllm/models/adaln_goldens.inc — S2Mel's adaLN / FinalLayer oracle.

The DiT conditions every block through adaptive layer norm:
`modulate(x, shift, scale) = x * (1 + scale) + shift`, with shift and scale
produced by `SiLU -> Linear(hidden, 2*hidden)` from the conditioning vector.

THE `1 +` IS THE DETAIL. Dropping it leaves a model that still trains and still
generates; it simply centres the modulation on 0 instead of 1.

The FinalLayer's norm is `elementwise_affine=False` -- it has NO gamma/beta, so a
port that applies them is reading tensors that do not exist in the checkpoint.

Usage: DIT_SRC=<path> python3 scripts/gen-adaln-goldens.py --out <inc>
"""
from __future__ import annotations
import argparse, importlib.util, os, sys, types
from pathlib import Path
import numpy as np, torch

MASK = (1 << 64) - 1
def fnv(n):
    h = 0xCBF29CE484222325
    for b in n.encode(): h ^= b; h = (h * 0x100000001B3) & MASK
    return h
def sm(x):
    x = (x + 0x9E3779B97F4A7C15) & MASK
    z = x
    z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & MASK
    z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & MASK
    return z ^ (z >> 31)
def rnd(name, n, scale):
    s = fnv(name); o = np.empty(n)
    for i in range(n): o[i] = (((sm((s + i) & MASK) >> 11) * 2.0**-53) * 2 - 1) * scale
    return o
def P(name, shape, scale=0.3):
    n = 1
    for d in shape: n *= d
    return torch.tensor(rnd(name, n, scale), dtype=torch.float64).reshape(shape).float()

def main() -> int:
    ap = argparse.ArgumentParser(); ap.add_argument("--out", required=True)
    a = ap.parse_args()
    src = Path(os.environ["DIT_SRC"])
    sys.path.insert(0, str(src.parents[3]))
    for name in ("munch",):
        if name not in sys.modules:
            stub = types.ModuleType(name); stub.Munch = dict; sys.modules[name] = stub
    spec = importlib.util.spec_from_file_location("dit", src)
    m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)

    torch.manual_seed(0)
    HIDDEN, OUT_CH, T = 12, 5, 6
    fl = m.FinalLayer(hidden_size=HIDDEN, patch_size=1, out_channels=OUT_CH).eval()
    manifest = []
    with torch.no_grad():
        for n, p in list(fl.named_parameters()) + list(fl.named_buffers()):
            p.copy_(P(n, tuple(p.shape) if p.dim() else (1,)).reshape(p.shape))
            manifest.append((n, list(p.shape)))
    x = P("ax", (1, T, HIDDEN), 1.0)
    c = P("ac", (1, HIDDEN), 1.0)
    with torch.no_grad():
        out = fl(x, c)
        shift, scale = fl.adaLN_modulation(c).chunk(2, dim=1)
        modulated = m.modulate(fl.norm_final(x), shift, scale)

    def emit(f, name, t):
        arr = np.asarray(t.detach().numpy(), dtype=np.float32).reshape(-1)
        f.write(f"inline constexpr float {name}[] = {{\n")
        for i in range(0, len(arr), 6):
            f.write("    " + ", ".join(f"{v:.9e}F" for v in arr[i:i+6]) + ",\n")
        f.write("};\n\n")

    p = Path(a.out)
    with p.open("w") as f:
        f.write("// GENERATED by scripts/gen-adaln-goldens.py -- do not edit.\n")
        f.write("// S2Mel FinalLayer executed DIRECTLY. norm_final has\n")
        f.write("// elementwise_affine=False: NO gamma/beta exist in the checkpoint.\n")
        f.write("#pragma once\n\n#include <cstdint>\n\nnamespace adaln_goldens {\n\n")
        f.write(f"inline constexpr int64_t kHidden = {HIDDEN};\n")
        f.write(f"inline constexpr int64_t kOutCh = {OUT_CH};\n")
        f.write(f"inline constexpr int64_t kFrames = {T};\n\n")
        f.write(f"inline constexpr int64_t kManifestSize = {len(manifest)};\n")
        f.write("struct ManifestEntry { const char* name; int64_t rank; int64_t d0, d1, d2; };\n")
        f.write("inline constexpr ManifestEntry kManifest[] = {\n")
        for nm, sh in manifest:
            d = list(sh) + [1, 1, 1]
            f.write(f'    {{"{nm}", {len(sh)}, {d[0]}, {d[1]}, {d[2]}}},\n')
        f.write("};\n\n")
        emit(f, "kX", x); emit(f, "kC", c)
        emit(f, "kModulated", modulated); emit(f, "kFinalOut", out)
        f.write("}  // namespace adaln_goldens\n")
    print(f"wrote {p}: {len(manifest)} tensors, hidden={HIDDEN}, out_ch={OUT_CH}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
