#!/usr/bin/env python3
"""Emit a C++ tensor-manifest fixture from a REAL safetensors checkpoint header.

A safetensors file starts with an 8-byte little-endian header length followed by a
JSON header naming every tensor with its dtype and shape. That header is a few tens
of KB even for a multi-GB checkpoint, so an HTTP range request over the first few
MiB is enough to capture the whole manifest — the same trick
gen-minimax-h3-gguf-manifest.py uses for GGUF. This is what lets the MiniMax-H3
loader contracts be gated against REAL checkpoints (names, shapes, dtypes) without
downloading, or checking in, a single weight byte.

Used for two MiniMax-H3 arms:

  NVFP4 DiT  (lilcheaty/MiniMax-H3-NVFP4, minimax_h3_ref2va_nvfp4_full.safetensors)
    curl -sL -r 0-16777215 -o nvfp4.head <url>
    python3 scripts/gen-minimax-h3-safetensors-manifest.py nvfp4.head \\
        --symbol H3Nvfp4 --out tests/vllm/models/minimax_h3_nvfp4_manifest.inc

  Video VAE (MiniMaxAI/MiniMax-H3, FL2VA/video_vae/source/model.safetensors)
    curl -sL -r 0-8388607 -o videovae.head <url>
    python3 scripts/gen-minimax-h3-safetensors-manifest.py videovae.head \\
        --symbol H3VideoVae --out tests/vllm/models/minimax_h3_video_vae_manifest.inc

And for LTX-2.5 phase L6, where the two shipped checkpoints sit on the local NAS
and are read in place rather than range-fetched — hence --captured-via / --spec,
which name the real provenance instead of the MiniMax-H3 defaults:

  FP8 DiT
    python3 scripts/gen-minimax-h3-safetensors-manifest.py \\
        "$CHECKPOINT_ROOT/ltx-2.5/vonkaiser-fp8-nvfp4/transformer/ltx-2.5-22b-distilled-fp8.safetensors" \\
        --symbol Ltx25Fp8Dit \\
        --label "vonkaiser/LTX-2.5-FP8-NVFP4 transformer/ltx-2.5-22b-distilled-fp8.safetensors" \\
        --captured-via "a local read of the file on the NAS" \\
        --spec .agents/specs/ltx-2-5.md \\
        --out tests/vllm/models/ltx2_fp8_dit_manifest.inc

  NVFP4 text encoder
    python3 scripts/gen-minimax-h3-safetensors-manifest.py \\
        "$CHECKPOINT_ROOT/ltx-2.5/vonkaiser-fp8-nvfp4/text_encoders/gemma4-12b-with-proj-nvfp4-torchao.safetensors" \\
        --symbol Ltx25Nvfp4Te \\
        --label "vonkaiser/LTX-2.5-FP8-NVFP4 text_encoders/gemma4-12b-with-proj-nvfp4-torchao.safetensors" \\
        --captured-via "a local read of the file on the NAS" \\
        --spec .agents/specs/ltx-2-5.md \\
        --out tests/vllm/models/ltx2_nvfp4_te_manifest.inc

Self-contained: no safetensors library needed, so it runs anywhere the file does.
"""

from __future__ import annotations

import argparse
import json
import struct
from pathlib import Path


def read_header(path: Path) -> dict:
    with path.open("rb") as fh:
        raw = fh.read(8)
        if len(raw) != 8:
            raise SystemExit(f"{path}: too short to hold a safetensors header length")
        length = struct.unpack("<Q", raw)[0]
        if length <= 0 or length > 512 * 1024 * 1024:
            raise SystemExit(
                f"{path}: implausible header length {length} — is this a safetensors file "
                "(an HTML error page will land here if the URL redirected)?"
            )
        payload = fh.read(length)
        if len(payload) != length:
            raise SystemExit(
                f"{path}: header is {length} bytes but only {len(payload)} were fetched; "
                "widen the range request"
            )
    header = json.loads(payload.decode("utf-8"))
    header.pop("__metadata__", None)
    return header


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("header_file", type=Path, help="the checkpoint, or a range-fetched prefix")
    parser.add_argument("--symbol", required=True, help="C++ symbol prefix, e.g. H3Nvfp4")
    parser.add_argument("--out", required=True, type=Path)
    parser.add_argument("--label", default="", help="human label for the generated comment")
    # PROVENANCE, and it has to be told rather than assumed. This script is no
    # longer MiniMax-H3-only: LTX-2.5 phase L6 reads its two checkpoints off the
    # local NAS, and emitting "captured via an HTTP range request. See
    # .agents/specs/minimax-h3.md" over those files stated two things that were
    # not true of them. The defaults keep every MiniMax-H3 regeneration
    # byte-identical.
    parser.add_argument(
        "--captured-via",
        default="an HTTP range request",
        help="how the header was obtained, e.g. 'a local read on the NAS'",
    )
    parser.add_argument(
        "--spec",
        default=".agents/specs/minimax-h3.md",
        help="the spec that owns this fixture",
    )
    args = parser.parse_args()

    header = read_header(args.header_file)
    tensors = sorted(header.items())
    label = args.label or args.header_file.name

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w", encoding="utf-8") as out:
        out.write(
            "// GENERATED by scripts/gen-minimax-h3-safetensors-manifest.py — DO NOT EDIT BY HAND.\n"
            "//\n"
            f"// Tensor manifest of a REAL safetensors checkpoint ({label}): {len(tensors)} tensors,\n"
            "// names/dtypes/shapes only — no weight bytes. Captured from the file's own header via\n"
            f"// {args.captured_via}. See {args.spec}.\n"
            "#pragma once\n\n#include <cstdint>\n\nnamespace vllm_test {\n\n"
        )
        out.write(f"inline constexpr int64_t k{args.symbol}TensorCount = {len(tensors)};\n\n")
        out.write(
            f"struct {args.symbol}Tensor {{\n"
            "  const char* name;\n"
            "  const char* dtype;\n"
            "  int64_t shape[5];  // 0-padded (Conv3d weights are rank 5)\n"
            "  int32_t rank;\n"
            "};\n\n"
        )
        out.write(f"inline constexpr {args.symbol}Tensor k{args.symbol}Tensors[] = {{\n")
        for name, info in tensors:
            shape = list(info.get("shape", []))
            if len(shape) > 5:
                raise SystemExit(f"{name}: rank {len(shape)} exceeds the fixture's 5-dim slots")
            padded = shape + [0] * (5 - len(shape))
            out.write(
                f'    {{"{name}", "{info["dtype"]}", '
                f"{{{', '.join(str(v) for v in padded)}}}, {len(shape)}}},\n"
            )
        out.write("};\n\n}  // namespace vllm_test\n")
    print(f"wrote {args.out} ({len(tensors)} tensors)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
