import importlib.util, sys, types, numpy as np, torch
from pathlib import Path
SRC = Path("/tmp/claude-1000/-home-mudler--git-vllm-cpp/38b1c7ca-4dbc-4077-a36b-a9495dd81893/scratchpad/it2/indextts/s2mel/modules/campplus/layers.py")
# load the UPSTREAM module by file path (no package __init__, no vllm deps)
spec = importlib.util.spec_from_file_location("cp_layers", SRC)
m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)

MASK = (1 << 64) - 1
def fnv(n):
    h = 0xCBF29CE484222325
    for b in n.encode(): h ^= b; h = (h * 0x100000001B3) & MASK
    return h
def sm(x):
    x = (x + 0x9E3779B97F4A7C15) & MASK
    z = x
    z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & MASK
    z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & MASK
    return z ^ (z >> 31)
def rnd(name, n, scale=1.0):
    s = fnv(name); o = np.empty(n)
    for i in range(n): o[i] = (((sm((s + i) & MASK) >> 11) * 2.0**-53) * 2 - 1) * scale
    return o
def P(name, shape, scale=1.0):
    n = int(np.prod(shape))
    return torch.tensor(rnd(name, n, scale), dtype=torch.float64).reshape(shape).float()

torch.manual_seed(0)
C, T, BN, OUT, K, D = 6, 250, 4, 5, 3, 2   # T>100 so seg_pooling's ceil_mode bites
x = P("x", (1, C, T), 1.0)

# ---- StatsPool: mean + UNBIASED std ----
stats = m.StatsPool()(x)

# ---- BatchNorm1d in EVAL mode (running stats, not batch stats) ----
bn = torch.nn.BatchNorm1d(C).eval()
with torch.no_grad():
    bn.weight.copy_(P("bn.w", (C,), 0.5) + 1.0); bn.bias.copy_(P("bn.b", (C,), 0.3))
    bn.running_mean.copy_(P("bn.rm", (C,), 0.4)); bn.running_var.copy_(P("bn.rv", (C,), 0.2).abs() + 0.5)
bn_out = bn(x)

# ---- CAMLayer (incl. seg_pooling with ceil_mode) ----
cam = m.CAMLayer(BN, OUT, K, stride=1, padding=(K-1)//2*D, dilation=D, bias=False).eval()
xb = P("xb", (1, BN, T), 1.0)
with torch.no_grad():
    cam.linear_local.weight.copy_(P("cam.ll.w", tuple(cam.linear_local.weight.shape), 0.3))
    cam.linear1.weight.copy_(P("cam.l1.w", tuple(cam.linear1.weight.shape), 0.3))
    cam.linear1.bias.copy_(P("cam.l1.b", tuple(cam.linear1.bias.shape), 0.2))
    cam.linear2.weight.copy_(P("cam.l2.w", tuple(cam.linear2.weight.shape), 0.3))
    cam.linear2.bias.copy_(P("cam.l2.b", tuple(cam.linear2.bias.shape), 0.2))
cam_out = cam(xb)
seg = cam.seg_pooling(xb)

def emit(f, name, t):
    a = np.asarray(t.detach().numpy(), dtype=np.float32).reshape(-1)
    f.write(f"inline constexpr float {name}[] = {{\n")
    for i in range(0, len(a), 6):
        f.write("    " + ", ".join(f"{v:.9e}F" for v in a[i:i+6]) + ",\n")
    f.write("};\n\n")

out = Path(sys.argv[1])
with out.open("w") as f:
    f.write("// GENERATED by scripts/gen-campplus-goldens.py -- do not edit.\n")
    f.write("// Upstream executed DIRECTLY (indextts/s2mel/modules/campplus/layers.py,\n")
    f.write("// index-tts @ main): it has no vllm dependency, so these are the real\n")
    f.write("// classes rather than a restatement. Weights rebuilt both sides from one\n")
    f.write("// FNV-1a -> splitmix64 stream; no weight byte is checked in.\n")
    f.write("#pragma once\n\n#include <cstdint>\n\nnamespace campplus_goldens {\n\n")
    for n, v in (("kChannels", C), ("kFrames", T), ("kBnChannels", BN), ("kOutChannels", OUT),
                 ("kKernel", K), ("kDilation", D), ("kSegLen", 100)):
        f.write(f"inline constexpr int64_t {n} = {v};\n")
    f.write("\n")
    emit(f, "kStats", stats); emit(f, "kBatchNormEval", bn_out)
    emit(f, "kSegPooling", seg); emit(f, "kCamOut", cam_out)
    f.write("}  // namespace campplus_goldens\n")
print("wrote", out, "T=", T, "seg segments=", -(-T//100))
