#!/usr/bin/env python3
"""Emit tests/vllm/models/cfm_goldens.inc — S2Mel's timestep embedder oracle.

The S2Mel decoder is a flow-matching CFM whose estimator is a DiT. This gates the
scaffolding that surrounds the DiT blocks: the sinusoidal TIMESTEP EMBEDDING and
its MLP.

TWO THINGS UPSTREAM DOES THAT ARE NOT THE COMMON CONVENTION, both pinned here:
  * `scale = 1000` multiplies t BEFORE the frequencies are applied.
  * the embedding is `cat([cos, sin])` -- COSINE FIRST. Most implementations put
    sine first, and swapping them still yields a smooth, well-formed embedding.

Upstream executed directly (indextts/s2mel/modules/diffusion_transformer.py).

Usage: DIT_SRC=<path> python3 scripts/gen-cfm-goldens.py --out <inc>
"""
from __future__ import annotations
import argparse, importlib.util, os, sys, types
from pathlib import Path
import numpy as np, torch

MASK = (1 << 64) - 1
def fnv(n):
    h = 0xCBF29CE484222325
    for b in n.encode(): h ^= b; h = (h * 0x100000001B3) & MASK
    return h
def sm(x):
    x = (x + 0x9E3779B97F4A7C15) & MASK
    z = x
    z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & MASK
    z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & MASK
    return z ^ (z >> 31)
def rnd(name, n, scale):
    s = fnv(name); o = np.empty(n)
    for i in range(n): o[i] = (((sm((s + i) & MASK) >> 11) * 2.0**-53) * 2 - 1) * scale
    return o
def P(name, shape, scale=0.3):
    n = 1
    for d in shape: n *= d
    return torch.tensor(rnd(name, n, scale), dtype=torch.float64).reshape(shape).float()

def main() -> int:
    ap = argparse.ArgumentParser(); ap.add_argument("--out", required=True)
    a = ap.parse_args()
    src = Path(os.environ["DIT_SRC"])
    # The module imports siblings; load it with a stub package so only the
    # class we need is constructed.
    # the module imports its siblings, so the package root must be importable
    sys.path.insert(0, str(src.parents[3]))
    # Stub the third-party helpers the module imports at top level but that the
    # TimestepEmbedder never touches. Stubbing beats installing: it keeps the
    # oracle reproducible with no network and no version drift.
    for name in ("munch",):
        if name not in sys.modules:
            stub = types.ModuleType(name)
            stub.Munch = dict
            sys.modules[name] = stub
    spec = importlib.util.spec_from_file_location("dit", src)
    m = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(m)
    except Exception as exc:  # pragma: no cover - reported, not hidden
        print("could not import upstream DiT module:", exc, file=sys.stderr)
        return 2

    torch.manual_seed(0)
    HIDDEN, FREQ = 16, 8
    te = m.TimestepEmbedder(hidden_size=HIDDEN, frequency_embedding_size=FREQ).eval()
    manifest = []
    with torch.no_grad():
        for n, p in list(te.named_parameters()):
            p.copy_(P(n, tuple(p.shape) if p.dim() else (1,)).reshape(p.shape))
            manifest.append((n, list(p.shape)))
    ts = torch.tensor([0.0, 0.13, 0.5, 0.87, 1.0])
    with torch.no_grad():
        raw = te.timestep_embedding(ts)
        emb = te(ts)

    def emit(f, name, t):
        arr = np.asarray(t.detach().numpy(), dtype=np.float32).reshape(-1)
        f.write(f"inline constexpr float {name}[] = {{\n")
        for i in range(0, len(arr), 6):
            f.write("    " + ", ".join(f"{v:.9e}F" for v in arr[i:i+6]) + ",\n")
        f.write("};\n\n")

    p = Path(a.out)
    with p.open("w") as f:
        f.write("// GENERATED by scripts/gen-cfm-goldens.py -- do not edit.\n")
        f.write("// S2Mel TimestepEmbedder executed DIRECTLY. Note scale=1000 and the\n")
        f.write("// cat([cos, sin]) ordering -- COSINE FIRST, unlike most implementations.\n")
        f.write("#pragma once\n\n#include <cstdint>\n\nnamespace cfm_goldens {\n\n")
        f.write(f"inline constexpr int64_t kHidden = {HIDDEN};\n")
        f.write(f"inline constexpr int64_t kFreqDim = {FREQ};\n")
        f.write(f"inline constexpr int64_t kNumT = {len(ts)};\n")
        f.write(f"inline constexpr double kMaxPeriod = {te.max_period};\n")
        f.write(f"inline constexpr double kScale = {te.scale};\n\n")
        f.write("inline constexpr float kT[] = {" +
                ", ".join(f"{float(v):.9e}F" for v in ts.tolist()) + "};\n\n")
        f.write(f"inline constexpr int64_t kManifestSize = {len(manifest)};\n")
        f.write("struct ManifestEntry { const char* name; int64_t rank; int64_t d0, d1; };\n")
        f.write("inline constexpr ManifestEntry kManifest[] = {\n")
        for nm, sh in manifest:
            d = list(sh) + [1, 1]
            f.write(f'    {{"{nm}", {len(sh)}, {d[0]}, {d[1]}}},\n')
        f.write("};\n\n")
        emit(f, "kRawEmbedding", raw)
        emit(f, "kTimestepEmbedding", emb)
        f.write("}  // namespace cfm_goldens\n")
    print(f"wrote {p}: {len(manifest)} tensors, freq_dim={FREQ}, timesteps={len(ts)}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
