#!/usr/bin/env python3
"""Emit tests/vllm/models/minimax_music3_manifest.inc from the REAL checkpoint.

Names, dtypes and shapes only -- not one weight byte. Every geometry claim
.agents/specs/minimax-music3.md section 1 makes is asserted against this
manifest, so a claim cannot drift from the artifact and CI never needs the
28.5 GB asset.

The four diffusers-only components (`transformer`, `condition_encoder`,
`vocoder`, `rvq_depth_decoder`) are read from their safetensors headers. The
`language_model` is read from its headers too when the shards are present; its
NAME SET comes from `model.safetensors.index.json`, which is what actually
pins which tensors the component owes.

Usage:
    scripts/gen-minimax-music3-manifest.py \
        --checkpoint "$CHECKPOINT_ROOT/minimax-music3" \
        --output tests/vllm/models/minimax_music3_manifest.inc
"""

from __future__ import annotations

import argparse
import json
import struct
from pathlib import Path

# One entry per component: (component name, subdirectory, shard glob, index file).
COMPONENTS = (
    ("transformer", "transformer", "diffusion_pytorch_model*.safetensors",
     "diffusion_pytorch_model.safetensors.index.json"),
    ("condition_encoder", "condition_encoder", "diffusion_pytorch_model.safetensors", None),
    ("rvq_depth_decoder", "rvq_depth_decoder", "diffusion_pytorch_model.safetensors", None),
    ("vocoder", "vocoder", "diffusion_pytorch_model.safetensors", None),
    ("language_model", "language_model", "model-*.safetensors", "model.safetensors.index.json"),
)

MAX_RANK = 3


def read_header(path: Path) -> dict:
    with path.open("rb") as handle:
        (length,) = struct.unpack("<Q", handle.read(8))
        header = json.loads(handle.read(length))
    header.pop("__metadata__", None)
    return header


def collect(root: Path) -> tuple[dict[str, list[tuple[str, str, list[int]]]], list[str]]:
    """Return {component: [(name, dtype, shape)]} plus the components read from an index only."""
    tensors: dict[str, list[tuple[str, str, list[int]]]] = {}
    index_only: list[str] = []
    for component, subdir, pattern, index_name in COMPONENTS:
        directory = root / subdir
        if not directory.is_dir():
            raise SystemExit(f"missing component directory: {directory}")
        shards = sorted(directory.glob(pattern))
        merged: dict[str, tuple[str, list[int]]] = {}
        for shard in shards:
            for name, entry in read_header(shard).items():
                if name in merged:
                    raise SystemExit(f"{component}: {name} appears in more than one shard")
                merged[name] = (entry["dtype"], list(entry["shape"]))
        if index_name is not None:
            index = json.loads((directory / index_name).read_text())
            declared = set(index["weight_map"])
            if not merged:
                raise SystemExit(
                    f"{component}: no shard is present; "
                    f"the index declares {len(declared)} tensors but none can be measured"
                )
            if set(merged) != declared:
                missing = sorted(declared - set(merged))
                extra = sorted(set(merged) - declared)
                raise SystemExit(
                    f"{component}: header/index disagree; "
                    f"missing from shards: {missing[:5]} ({len(missing)}), "
                    f"absent from index: {extra[:5]} ({len(extra)})"
                )
        for name, (dtype, shape) in merged.items():
            if len(shape) > MAX_RANK:
                raise SystemExit(f"{component}: {name} has rank {len(shape)} > {MAX_RANK}")
        tensors[component] = sorted((n, d, s) for n, (d, s) in merged.items())
    return tensors, index_only


def emit(tensors: dict[str, list[tuple[str, str, list[int]]]], checkpoint: Path) -> str:
    lines: list[str] = []
    add = lines.append
    add("// GENERATED by scripts/gen-minimax-music3-manifest.py --- DO NOT EDIT BY HAND.")
    add("//")
    add("// Tensor manifest of the REAL MiniMaxAI/MiniMax-Music3 DIFFUSERS-arm checkpoint:")
    add("// names, dtypes and shapes only, read from each safetensors header. No weight")
    add("// bytes, so the gate that consumes this needs no checkpoint and CI never")
    add("// downloads 28.5 GB. See .agents/specs/minimax-music3.md section 1.")
    add("#pragma once")
    add("")
    add("#include <cstdint>")
    add("")
    add("namespace vllm_test {")
    add("")
    add("struct Music3ManifestTensor {")
    add("  const char* component;")
    add("  const char* name;")
    add("  const char* dtype;")
    add(f"  int64_t shape[{MAX_RANK}];  // 0-padded")
    add("  int32_t rank;")
    add("};")
    add("")
    total = 0
    for component, _, _, _ in COMPONENTS:
        entries = tensors[component]
        params = sum(_numel(shape) for _, _, shape in entries)
        dtypes = sorted({dtype for _, dtype, _ in entries})
        symbol = _symbol(component)
        add(f"// {component}: {len(entries)} tensors, {params} parameters, dtype(s) {'/'.join(dtypes)}.")
        add(f"inline constexpr int64_t kMusic3{symbol}TensorCount = {len(entries)};")
        add(f"inline constexpr int64_t kMusic3{symbol}Parameters = {params};")
        total += len(entries)
    add("")
    add(f"inline constexpr int64_t kMusic3ManifestTensorCount = {total};")
    add("")
    add("inline constexpr Music3ManifestTensor kMusic3Manifest[] = {")
    for component, _, _, _ in COMPONENTS:
        for name, dtype, shape in tensors[component]:
            padded = list(shape) + [0] * (MAX_RANK - len(shape))
            dims = ", ".join(str(d) for d in padded)
            add(f'    {{"{component}", "{name}", "{dtype}", {{{dims}}}, {len(shape)}}},')
    add("};")
    add("")
    add("}  // namespace vllm_test")
    add("")
    return "\n".join(lines)


def _numel(shape: list[int]) -> int:
    out = 1
    for dim in shape:
        out *= dim
    return out


def _symbol(component: str) -> str:
    return "".join(part.capitalize() for part in component.split("_"))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    tensors, _ = collect(args.checkpoint)
    args.output.write_text(emit(tensors, args.checkpoint), encoding="utf-8")
    total = sum(len(v) for v in tensors.values())
    print(f"wrote {args.output} with {total} tensors across {len(tensors)} components")
    for component, entries in tensors.items():
        print(f"  {component}: {len(entries)} tensors")


if __name__ == "__main__":
    main()
