#!/usr/bin/env python3
"""Emit tests/vllm/models/fvq_goldens.inc — the EnhancedCodec quantizer oracle.

`infer_v2_5.py:293` calls `semantic_codec.quantize(inputs)`, whose discrete
output IS the semantic code the talker consumes. The quantizer is Amphion's
FactorizedVectorQuantize with use_l2_normlize=True.

Upstream is executed DIRECTLY (indextts/codec/amphion_codec/quantize), loaded by
file path so no package __init__ is needed.

Usage:
  CODEC_QUANTIZE=<path to factorized_vector_quantize.py> \
  python3 scripts/gen-fvq-goldens.py --out tests/vllm/models/fvq_goldens.inc
"""
from __future__ import annotations
import argparse, importlib.util, os, sys
from pathlib import Path
import numpy as np, torch

MASK = (1 << 64) - 1
def fnv(n):
    h = 0xCBF29CE484222325
    for b in n.encode(): h ^= b; h = (h * 0x100000001B3) & MASK
    return h
def sm(x):
    x = (x + 0x9E3779B97F4A7C15) & MASK
    z = x
    z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & MASK
    z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & MASK
    return z ^ (z >> 31)
def rnd(name, n, scale):
    s = fnv(name); o = np.empty(n)
    for i in range(n): o[i] = (((sm((s + i) & MASK) >> 11) * 2.0**-53) * 2 - 1) * scale
    return o
def P(name, shape, scale=0.3):
    n = 1
    for d in shape: n *= d
    return torch.tensor(rnd(name, n, scale), dtype=torch.float64).reshape(shape).float()

def main() -> int:
    ap = argparse.ArgumentParser(); ap.add_argument("--out", required=True)
    a = ap.parse_args()
    src = Path(os.environ["CODEC_QUANTIZE"])
    spec = importlib.util.spec_from_file_location("fvq", src)
    m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)

    torch.manual_seed(0)
    IN_DIM, CB_DIM, CB_SIZE, T = 12, 4, 32, 9
    q = m.FactorizedVectorQuantize(input_dim=IN_DIM, codebook_size=CB_SIZE,
                                   codebook_dim=CB_DIM, commitment=0.15,
                                   codebook_loss_weight=1.0, use_l2_normlize=True).eval()
    manifest = []
    with torch.no_grad():
        for n, p in list(q.named_parameters()) + list(q.named_buffers()):
            if n.endswith("num_batches_tracked"): continue
            p.copy_(P(n, tuple(p.shape) if p.dim() else (1,)).reshape(p.shape))
            manifest.append((n, list(p.shape)))
    z = P("z", (1, IN_DIM, T), 1.0)
    with torch.no_grad():
        out = q(z)
    z_q, indices = out[0], out[3]

    def emit_f(f, name, t):
        arr = np.asarray(t.detach().numpy(), dtype=np.float32).reshape(-1)
        f.write(f"inline constexpr float {name}[] = {{\n")
        for i in range(0, len(arr), 6):
            f.write("    " + ", ".join(f"{v:.9e}F" for v in arr[i:i+6]) + ",\n")
        f.write("};\n\n")

    p = Path(a.out)
    with p.open("w") as f:
        f.write("// GENERATED by scripts/gen-fvq-goldens.py -- do not edit.\n")
        f.write("// Amphion FactorizedVectorQuantize executed DIRECTLY (the quantizer\n")
        f.write("// EnhancedCodec uses; infer_v2_5.py:293). Weights rebuilt both sides from\n")
        f.write("// one FNV-1a -> splitmix64 stream.\n")
        f.write("#pragma once\n\n#include <cstdint>\n\nnamespace fvq_goldens {\n\n")
        for n, v in (("kInputDim", IN_DIM), ("kCodebookDim", CB_DIM),
                     ("kCodebookSize", CB_SIZE), ("kFrames", T)):
            f.write(f"inline constexpr int64_t {n} = {v};\n")
        f.write(f"\ninline constexpr int64_t kManifestSize = {len(manifest)};\n\n")
        f.write("struct ManifestEntry { const char* name; int64_t rank; int64_t d0, d1, d2; };\n")
        f.write("inline constexpr ManifestEntry kManifest[] = {\n")
        for nm, sh in manifest:
            d = list(sh) + [1, 1, 1]
            f.write(f'    {{"{nm}", {len(sh)}, {d[0]}, {d[1]}, {d[2]}}},\n')
        f.write("};\n\n")
        emit_f(f, "kZ", z)
        emit_f(f, "kZq", z_q)
        f.write("inline constexpr int64_t kIndices[] = {\n    " +
                ", ".join(str(int(v)) for v in indices.reshape(-1).tolist()) + ",\n};\n\n")
        f.write("}  // namespace fvq_goldens\n")
    print(f"wrote {p}: {len(manifest)} tensors, T={T}, codebook={CB_SIZE}x{CB_DIM}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
