#!/usr/bin/env python3
"""Emit tests/vllm/models/lenreg_goldens.inc — the S2Mel length-regulator oracle.

`infer_v2_5.py:650` calls `s2mel.models['length_regulator']` to stretch the
semantic sequence onto the target mel length. Its defining operation is
`F.interpolate(..., mode='nearest')`, whose index rule is
`src = floor(i * in_len / out_len)` -- an off-by-one here shifts every frame and
still produces audio.

The regulator's stack (Conv1d k=3 / GroupNorm / Mish, then a 1x1 Conv1d) is
gated alongside it, plus Mish itself, which is x * tanh(softplus(x)) and is easy
to confuse with SiLU.

Torch is the oracle: these are stock nn modules, so upstream IS torch here.

Usage: python3 scripts/gen-lenreg-goldens.py --out <inc>
"""
from __future__ import annotations
import argparse
from pathlib import Path
import numpy as np, torch
import torch.nn.functional as F

MASK = (1 << 64) - 1
def fnv(n):
    h = 0xCBF29CE484222325
    for b in n.encode(): h ^= b; h = (h * 0x100000001B3) & MASK
    return h
def sm(x):
    x = (x + 0x9E3779B97F4A7C15) & MASK
    z = x
    z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & MASK
    z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & MASK
    return z ^ (z >> 31)
def rnd(name, n, scale):
    s = fnv(name); o = np.empty(n)
    for i in range(n): o[i] = (((sm((s + i) & MASK) >> 11) * 2.0**-53) * 2 - 1) * scale
    return o
def P(name, shape, scale=0.3):
    n = 1
    for d in shape: n *= d
    return torch.tensor(rnd(name, n, scale), dtype=torch.float64).reshape(shape).float()

def main() -> int:
    ap = argparse.ArgumentParser(); ap.add_argument("--out", required=True)
    a = ap.parse_args()
    torch.manual_seed(0)

    CH, IN_T, GROUPS = 8, 7, 4
    x = P("lrx", (1, CH, IN_T), 1.0)
    # Three ratios: upsample by a NON-INTEGER factor (the interesting one),
    # an exact double, and a downsample.
    targets = [17, 14, 3]
    interps = [F.interpolate(x, size=t, mode="nearest") for t in targets]

    gn = torch.nn.GroupNorm(GROUPS, CH).eval()
    with torch.no_grad():
        gn.weight.copy_(P("gn.weight", (CH,), 0.5) + 1.0)
        gn.bias.copy_(P("gn.bias", (CH,), 0.3))
    gn_out = gn(x)

    mish_in = P("mishx", (1, CH, IN_T), 3.0)
    mish_out = F.mish(mish_in)

    def emit(f, name, t):
        arr = np.asarray(t.detach().numpy(), dtype=np.float32).reshape(-1)
        f.write(f"inline constexpr float {name}[] = {{\n")
        for i in range(0, len(arr), 6):
            f.write("    " + ", ".join(f"{v:.9e}F" for v in arr[i:i+6]) + ",\n")
        f.write("};\n\n")

    p = Path(a.out)
    with p.open("w") as f:
        f.write("// GENERATED by scripts/gen-lenreg-goldens.py -- do not edit.\n")
        f.write("// torch is the oracle here: the length regulator's pieces are stock nn\n")
        f.write("// modules, so upstream IS torch. F.interpolate(mode='nearest') uses\n")
        f.write("// src = floor(i * in_len / out_len).\n")
        f.write("#pragma once\n\n#include <cstdint>\n\nnamespace lenreg_goldens {\n\n")
        f.write(f"inline constexpr int64_t kChannels = {CH};\n")
        f.write(f"inline constexpr int64_t kInFrames = {IN_T};\n")
        f.write(f"inline constexpr int64_t kGroups = {GROUPS};\n")
        f.write("inline constexpr int64_t kTargets[] = {" + ", ".join(str(t) for t in targets) + "};\n\n")
        emit(f, "kX", x)
        for t, y in zip(targets, interps):
            emit(f, f"kInterp{t}", y)
        emit(f, "kGroupNorm", gn_out)
        emit(f, "kMishIn", mish_in); emit(f, "kMishOut", mish_out)
        f.write("}  // namespace lenreg_goldens\n")
    print(f"wrote {p}: targets {targets} from {IN_T}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
