#!/usr/bin/env python3
"""Emit C++ goldens for the BigVGAN GENERATOR: mel -> waveform.

Upstream `indextts/s2mel/modules/bigvgan/bigvgan.py` class BigVGAN, index-tts
@4f8792ff120cd3ea470dd511e997a17c86cddd10. This is the last stage of the
IndexTTS-2.5 pipeline: it turns the mel the S2Mel decoder produces into samples.

Every primitive it needs already exists in `vocoder1d`, shared with MiniMax-H3
and LTX-2.5, so the port is composition. What this gates is that composition:
the pre-conv, the upsample stack, the AMP blocks, the AVERAGE over kernels, the
post activation and conv, and the final bound.

Usage: BIGVGAN_SRC=<path to indextts/s2mel/modules/bigvgan> python3 \
           scripts/gen-bigvgan-goldens.py --out tests/vllm/models/bigvgan_goldens.inc
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import sys
import types
from pathlib import Path

import torch


def rnd(name: str, n: int, scale: float = 1.0) -> list:
    h = 0xCBF29CE484222325
    for ch in name.encode():
        h = ((h ^ ch) * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    out = []
    for _ in range(n):
        h = (h + 0x9E3779B97F4A7C15) & 0xFFFFFFFFFFFFFFFF
        z = h
        z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & 0xFFFFFFFFFFFFFFFF
        z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & 0xFFFFFFFFFFFFFFFF
        z ^= z >> 31
        out.append(((z >> 11) * (1.0 / 9007199254740992.0) * 2.0 - 1.0) * scale)
    return out


def tensor(name: str, shape, scale: float = 1.0) -> torch.Tensor:
    n = 1
    for d in shape:
        n *= d
    return torch.tensor(rnd(name, n, scale), dtype=torch.float64).reshape(shape).float()


def fmt(values) -> str:
    lines, row = [], []
    for v in values:
        row.append(f"{float(v):.9e}F")
        if len(row) == 6:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    return "\n".join(lines)


# Reduced dims. The shipped vocoder is 80 mels at 22.05 kHz with a 256x total
# upsample; the RATIOS that matter (two upsample stages, three kernels averaged,
# snakebeta with logscale, no tanh at the end) are preserved.
MELS, INIT_CH, FRAMES = 4, 8, 5
UP_RATES = [2, 2]
UP_KERNELS = [4, 4]
RB_KERNELS = [3, 5, 7]
RB_DILATIONS = [[1, 3], [1, 3], [1, 3]]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    src = Path(os.environ["BIGVGAN_SRC"])
    sys.path.insert(0, str(src.parents[3]))
    for name in ("munch",):
        if name not in sys.modules:
            stub = types.ModuleType(name)
            stub.Munch = dict
            sys.modules[name] = stub
    spec = importlib.util.spec_from_file_location(
        "indextts.s2mel.modules.bigvgan.bigvgan", src / "bigvgan.py"
    )
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)

    h = {
        "num_mels": MELS,
        "upsample_initial_channel": INIT_CH,
        "upsample_rates": UP_RATES,
        "upsample_kernel_sizes": UP_KERNELS,
        "resblock_kernel_sizes": RB_KERNELS,
        "resblock_dilation_sizes": RB_DILATIONS,
        "resblock": "1",
        "activation": "snakebeta",
        "snake_logscale": True,
        "use_tanh_at_final": False,
        "use_bias_at_final": False,
        "use_cuda_kernel": False,
    }
    # Upstream reads `h` both as an attribute bag AND as a mutable mapping
    # (`self.h["use_cuda_kernel"] = ...`), so neither a dict nor a namespace
    # alone will do.
    class AttrDict(dict):
        __getattr__ = dict.__getitem__
        __setattr__ = dict.__setitem__

    cfg = AttrDict(h)

    torch.manual_seed(0)
    gen = m.BigVGAN(cfg, use_cuda_kernel=False).eval()
    gen.remove_weight_norm()

    with torch.no_grad():
        for pname, p in sorted(gen.named_parameters()):
            p.copy_(tensor("bvg." + pname, list(p.shape), 0.3))

    x = tensor("bvg.x", [1, MELS, FRAMES])
    with torch.no_grad():
        y = gen(x)

    names = sorted(n for n, _ in gen.named_parameters())
    body = [
        "// GENERATED by scripts/gen-bigvgan-goldens.py -- do not edit.",
        "// Oracle: indextts/s2mel/modules/bigvgan/bigvgan.py BigVGAN, index-tts",
        "// @4f8792ff120cd3ea470dd511e997a17c86cddd10, weight-norm ALREADY folded",
        "// (remove_weight_norm) so the goldens carry effective weights.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace bigvgan_goldens {",
        "",
        f"inline constexpr int64_t kMels = {MELS};",
        f"inline constexpr int64_t kInitCh = {INIT_CH};",
        f"inline constexpr int64_t kFrames = {FRAMES};",
        f"inline constexpr int64_t kUpRates[] = {{{', '.join(map(str, UP_RATES))}}};",
        f"inline constexpr int64_t kUpKernels[] = {{{', '.join(map(str, UP_KERNELS))}}};",
        f"inline constexpr int64_t kRbKernels[] = {{{', '.join(map(str, RB_KERNELS))}}};",
        f"inline constexpr int64_t kNumUpsamples = {len(UP_RATES)};",
        f"inline constexpr int64_t kNumKernels = {len(RB_KERNELS)};",
        f"inline constexpr int64_t kSamples = {int(y.shape[-1])};",
        "",
        "inline constexpr const char* kParamNames[] = {",
    ]
    body += [f'    "bvg.{n}",' for n in names]
    body += [
        "};",
        "",
        "// The waveform -- [1, kSamples].",
        "inline constexpr float kWave[] = {",
        fmt(y.reshape(-1).tolist()),
        "};",
        "",
        "}  // namespace bigvgan_goldens",
        "",
    ]
    Path(a.out).write_text("\n".join(body))
    print(f"wrote {a.out}: {len(names)} params, {int(y.shape[-1])} samples "
          f"from {FRAMES} frames")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
