#!/usr/bin/env python3
"""Generate golden logits for the kev PointerHead test.

The generator and the C++ test rebuild the same weights from the same
FNV-1a -> splitmix64 stream, so no weight byte is checked in.  The golden
file contains only config constants, the input tensors, and the expected
logits.  The q/k projection order, the bias terms, and the scale factor
are features this port has to get right; each is gated by a perturbation
test in test_kev.cpp.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path

import numpy as np
import torch
from torch import nn

_MASK64 = (1 << 64) - 1


def fnv1a64(name: str) -> int:
    h = 0xCBF29CE484222325
    for byte in name.encode("utf-8"):
        h ^= byte
        h = (h * 0x100000001B3) & _MASK64
    return h


def splitmix64(x: int) -> int:
    x = (x + 0x9E3779B97F4A7C15) & _MASK64
    z = x
    z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & _MASK64
    z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & _MASK64
    return z ^ (z >> 31)


def rand(name: str, count: int) -> np.ndarray:
    """`count` values uniform in [-1, 1), reproducible from `name` alone."""
    seed = fnv1a64(name)
    out = np.empty(count, dtype=np.float64)
    for i in range(count):
        u = splitmix64((seed + i) & _MASK64)
        out[i] = ((u >> 11) * (2.0**-53)) * 2.0 - 1.0
    return out


def param(name: str, shape, scale: float) -> torch.Tensor:
    count = 1
    for s in shape:
        count *= s
    return torch.tensor(rand(name, count).reshape(shape) * scale, dtype=torch.float32)


# ── Config (reduced dims for fast test) ────────────────────────────────
D = 32
DP = 16


class PointerHead(nn.Module):
    """Exact restatement of jaredpalmer/kev model.py:PointerHead."""

    def __init__(self, d: int, dp: int) -> None:
        super().__init__()
        self.q = nn.Linear(d, dp)
        self.k = nn.Linear(d, dp)
        self.scale = 1.0 / math.sqrt(dp)

    def forward(self, h_decide: torch.Tensor, h_opts: torch.Tensor) -> torch.Tensor:
        # [d], [K,d] -> [K]
        return (self.k(h_opts) @ self.q(h_decide)) * self.scale


def build_head() -> PointerHead:
    head = PointerHead(D, DP)
    head.eval()
    with torch.no_grad():
        head.q.weight.copy_(param("q.weight", (DP, D), 0.3))
        head.q.bias.copy_(param("q.bias", (DP,), 0.3))
        head.k.weight.copy_(param("k.weight", (DP, D), 0.3))
        head.k.bias.copy_(param("k.bias", (DP,), 0.3))
    return head


def emit_f32(out, name: str, values) -> None:
    flat = np.asarray(values, dtype=np.float32).ravel()
    out.append(f"inline constexpr float {name}[] = {{")
    for i, v in enumerate(flat):
        if i % 6 == 0:
            out.append("\n    ")
        out.append(f"{v:.9e}F, ")
    out.append("\n};\n\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output", type=Path, default=Path("tests/vllm/models/kev_head_goldens.inc")
    )
    args = parser.parse_args()

    head = build_head()

    # Test case 1: 2 options (noul-like: yes/no).
    h_decide_1 = param("h_decide_1", (D,), 0.5)
    h_opts_1 = param("h_opts_1", (2, D), 0.5)
    with torch.no_grad():
        logits_1 = head(h_decide_1, h_opts_1)

    # Test case 2: 3 options (choice-like).
    h_decide_2 = param("h_decide_2", (D,), 0.5)
    h_opts_2 = param("h_opts_2", (3, D), 0.5)
    with torch.no_grad():
        logits_2 = head(h_decide_2, h_opts_2)

    # Test case 3: 5 options (score-like).
    h_decide_3 = param("h_decide_3", (D,), 0.5)
    h_opts_3 = param("h_opts_3", (5, D), 0.5)
    with torch.no_grad():
        logits_3 = head(h_decide_3, h_opts_3)

    # Emit goldens.
    out = []
    out.append("// GENERATED by scripts/gen-kev-head-goldens.py -- do not edit.\n")
    out.append("//\n")
    out.append("// kev PointerHead goldens: a restatement of\n")
    out.append("// jaredpalmer/kev kev/model.py @ 19dcae9b6e,\n")
    out.append("// executed at reduced dimensions on CPU. Weights are rebuilt on\n")
    out.append("// both sides from the same FNV-1a -> splitmix64 stream, so no\n")
    out.append("// weight byte is checked in.\n")
    out.append("#pragma once\n\n")
    out.append("#include <cstdint>\n\n")
    out.append("namespace kev_head_goldens {\n\n")

    out.append(f"inline constexpr int64_t kHiddenSize = {D};\n")
    out.append(f"inline constexpr int64_t kHeadDim = {DP};\n\n")

    # Test case 1.
    out.append("// Test case 1: 2 options (noul-like: yes/no).\n")
    emit_f32(out, "kHDecide1", h_decide_1.numpy())
    emit_f32(out, "kHOpts1", h_opts_1.numpy())
    emit_f32(out, "kLogits1", logits_1.numpy())

    # Test case 2.
    out.append("// Test case 2: 3 options (choice-like).\n")
    emit_f32(out, "kHDecide2", h_decide_2.numpy())
    emit_f32(out, "kHOpts2", h_opts_2.numpy())
    emit_f32(out, "kLogits2", logits_2.numpy())

    # Test case 3.
    out.append("// Test case 3: 5 options (score-like).\n")
    emit_f32(out, "kHDecide3", h_decide_3.numpy())
    emit_f32(out, "kHOpts3", h_opts_3.numpy())
    emit_f32(out, "kLogits3", logits_3.numpy())

    out.append("}  // namespace kev_head_goldens\n")
    args.output.write_text("".join(out))
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
