#!/usr/bin/env python3
"""Emit tests/vllm/models/vocos_goldens.inc — EnhancedCodec's VocosBackbone oracle.

`EnhancedCodec.quantize` runs its input through a VocosBackbone before the
quantizer (indextts/codec/models.py:187). The backbone is ConvNeXt-1D: depthwise
conv, layer norm at eps=1e-6, two pointwise linears with GELU, and a LEARNED
per-channel layer scale.

Upstream executed DIRECTLY, loaded by file path.

Usage:
  VOCOS_SRC=<path to vocos.py> python3 scripts/gen-vocos-goldens.py --out <inc>
"""
from __future__ import annotations
import argparse, importlib.util, os
from pathlib import Path
import numpy as np, torch

MASK = (1 << 64) - 1
def fnv(n):
    h = 0xCBF29CE484222325
    for b in n.encode(): h ^= b; h = (h * 0x100000001B3) & MASK
    return h
def sm(x):
    x = (x + 0x9E3779B97F4A7C15) & MASK
    z = x
    z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & MASK
    z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & MASK
    return z ^ (z >> 31)
def rnd(name, n, scale):
    s = fnv(name); o = np.empty(n)
    for i in range(n): o[i] = (((sm((s + i) & MASK) >> 11) * 2.0**-53) * 2 - 1) * scale
    return o
def P(name, shape, scale=0.3):
    n = 1
    for d in shape: n *= d
    return torch.tensor(rnd(name, n, scale), dtype=torch.float64).reshape(shape).float()

def main() -> int:
    ap = argparse.ArgumentParser(); ap.add_argument("--out", required=True)
    a = ap.parse_args()
    spec = importlib.util.spec_from_file_location("vocos", Path(os.environ["VOCOS_SRC"]))
    m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)

    torch.manual_seed(0)
    IN_CH, DIM, INTER, LAYERS, T = 6, 8, 16, 3, 11
    b = m.VocosBackbone(input_channels=IN_CH, dim=DIM, intermediate_dim=INTER,
                        num_layers=LAYERS, adanorm_num_embeddings=None).eval()
    manifest = []
    with torch.no_grad():
        for n, p in list(b.named_parameters()) + list(b.named_buffers()):
            if n.endswith("num_batches_tracked"): continue
            # pwconv1 gets a LARGER scale on purpose. The LayerNorm before it
            # normalizes the input away, so the pre-activation magnitude is set
            # by THESE weights alone. At the default 0.3 the pre-activations sit
            # near |x| ~ 0.85, where exact-erf and tanh-approx GELU differ by
            # ~1.5e-4 -- which pwconv2 and the 1/num_layers layer scale then
            # attenuate below any sane tolerance, letting a wrong activation
            # pass. At 1.0 the pre-activations reach |x| ~ 2.8 and the
            # difference survives to the output. Found by mutation.
            scale = 1.0 if "pwconv1.weight" in n else 0.3
            p.copy_(P(n, tuple(p.shape) if p.dim() else (1,), scale).reshape(p.shape))
            manifest.append((n, list(p.shape)))
    # Scale 4.0, not 1.0: the pointwise pre-activations must reach |x| ~ 2-3,
    # where the exact-erf and tanh-approximation GELUs differ by ~1e-3. At
    # scale 1.0 they agree to ~1e-6 and a wrong activation passes the gate --
    # found by mutation, which is what a fixture gap looks like.
    x = P("vx", (1, IN_CH, T), 4.0)
    with torch.no_grad():
        out = b(x)          # NOTE: returns (B, T, C) -- not transposed back

    def emit(f, name, t):
        arr = np.asarray(t.detach().numpy(), dtype=np.float32).reshape(-1)
        f.write(f"inline constexpr float {name}[] = {{\n")
        for i in range(0, len(arr), 6):
            f.write("    " + ", ".join(f"{v:.9e}F" for v in arr[i:i+6]) + ",\n")
        f.write("};\n\n")

    p = Path(a.out)
    with p.open("w") as f:
        f.write("// GENERATED by scripts/gen-vocos-goldens.py -- do not edit.\n")
        f.write("// VocosBackbone executed DIRECTLY (indextts/codec/kmeans/vocos.py).\n")
        f.write("// The backbone returns (B, T, C): its final layer norm is applied to the\n")
        f.write("// TRANSPOSED tensor and never transposed back, which is why EnhancedCodec\n")
        f.write("// writes `self.encoder(x.transpose(1,2)).transpose(1,2)`.\n")
        f.write("#pragma once\n\n#include <cstdint>\n\nnamespace vocos_goldens {\n\n")
        for n, v in (("kInChannels", IN_CH), ("kDim", DIM), ("kIntermediate", INTER),
                     ("kLayers", LAYERS), ("kFrames", T)):
            f.write(f"inline constexpr int64_t {n} = {v};\n")
        f.write(f"\ninline constexpr int64_t kManifestSize = {len(manifest)};\n\n")
        f.write("struct ManifestEntry { const char* name; int64_t rank; int64_t d0, d1, d2; };\n")
        f.write("inline constexpr ManifestEntry kManifest[] = {\n")
        for nm, sh in manifest:
            d = list(sh) + [1, 1, 1]
            f.write(f'    {{"{nm}", {len(sh)}, {d[0]}, {d[1]}, {d[2]}}},\n')
        f.write("};\n\n")
        emit(f, "kVx", x); emit(f, "kVocosOut", out)
        f.write("}  // namespace vocos_goldens\n")
    print(f"wrote {p}: {len(manifest)} tensors, layers={LAYERS}, out shape {tuple(out.shape)}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
