#!/usr/bin/env python3
"""Emit tests/vllm/models/dit_goldens.inc — the S2Mel DiT block primitives.

The DiT's transformer is gpt-fast's, wrapped so every block is conditioned by an
AdaptiveLayerNorm around an RMSNorm, with rotary position embeddings.

TWO CONVENTIONS THAT DIFFER FROM THEIR NEIGHBOURS IN THE SAME MODEL:

  * This AdaptiveLayerNorm is `weight * norm(x) + bias` -- NO `1 +`, unlike the
    `modulate()` used by the DiT's FinalLayer. Two adaLN conventions coexist, so
    porting one over the other is an easy and silent error.
  * The rotary embedding pairs ADJACENT components (`reshape(..., -1, 2)`), not
    halves of the vector. The half-split convention is far more common and
    produces a rotation that is smooth, norm-preserving and wrong.

Usage: GPTFAST_SRC=<path to gpt_fast/model.py> python3 ... --out <inc>
"""
from __future__ import annotations
import argparse, importlib.util, os, sys, types
from pathlib import Path
import numpy as np, torch

MASK = (1 << 64) - 1
def fnv(n):
    h = 0xCBF29CE484222325
    for b in n.encode(): h ^= b; h = (h * 0x100000001B3) & MASK
    return h
def sm(x):
    x = (x + 0x9E3779B97F4A7C15) & MASK
    z = x
    z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & MASK
    z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & MASK
    return z ^ (z >> 31)
def rnd(name, n, scale):
    s = fnv(name); o = np.empty(n)
    for i in range(n): o[i] = (((sm((s + i) & MASK) >> 11) * 2.0**-53) * 2 - 1) * scale
    return o
def P(name, shape, scale=0.3):
    n = 1
    for d in shape: n *= d
    return torch.tensor(rnd(name, n, scale), dtype=torch.float64).reshape(shape).float()

def main() -> int:
    ap = argparse.ArgumentParser(); ap.add_argument("--out", required=True)
    a = ap.parse_args()
    src = Path(os.environ["GPTFAST_SRC"])
    sys.path.insert(0, str(src.parents[4]))
    spec = importlib.util.spec_from_file_location("gf", src)
    m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)

    torch.manual_seed(0)
    DIM, T, HEADS = 8, 5, 2
    HEAD_DIM = DIM // HEADS

    rms = m.RMSNorm(DIM, eps=1e-5).eval()
    with torch.no_grad():
        rms.weight.copy_(P("rms.weight", (DIM,), 0.5) + 1.0)
    x = P("dx", (1, T, DIM), 1.5)
    rms_out = rms(x)

    aln = m.AdaptiveLayerNorm(DIM, m.RMSNorm(DIM, eps=1e-5)).eval()
    with torch.no_grad():
        aln.project_layer.weight.copy_(P("aln.project_layer.weight", (2 * DIM, DIM)))
        aln.project_layer.bias.copy_(P("aln.project_layer.bias", (2 * DIM,)))
        aln.norm.weight.copy_(P("aln.norm.weight", (DIM,), 0.5) + 1.0)
    emb = P("aemb", (1, 1, DIM), 1.0)
    aln_out = aln(x, emb)

    # rotary: freqs_cis is [T, head_dim/2, 2]
    freqs = m.precompute_freqs_cis(T, HEAD_DIM, base=10000)
    q = P("dq", (1, T, HEADS, HEAD_DIM), 1.0)
    rot = m.apply_rotary_emb(q, freqs)

    def emit(f, name, t):
        # .float() first: precompute_freqs_cis returns BFLOAT16 upstream, so the
        # rotary table already carries bf16 precision before any rotation runs.
        arr = np.asarray(t.detach().float().numpy(), dtype=np.float32).reshape(-1)
        f.write(f"inline constexpr float {name}[] = {{\n")
        for i in range(0, len(arr), 6):
            f.write("    " + ", ".join(f"{v:.9e}F" for v in arr[i:i+6]) + ",\n")
        f.write("};\n\n")

    p = Path(a.out)
    with p.open("w") as f:
        f.write("// GENERATED by scripts/gen-dit-goldens.py -- do not edit.\n")
        f.write("// gpt-fast primitives as S2Mel's DiT uses them. NOTE the AdaptiveLayerNorm\n")
        f.write("// here is `weight * norm(x) + bias` -- NO `1 +`, unlike modulate() in the\n")
        f.write("// FinalLayer -- and the rotary pairs ADJACENT components, not halves.\n")
        f.write("#pragma once\n\n#include <cstdint>\n\nnamespace dit_goldens {\n\n")
        for n, v in (("kDim", DIM), ("kFrames", T), ("kHeads", HEADS), ("kHeadDim", HEAD_DIM)):
            f.write(f"inline constexpr int64_t {n} = {v};\n")
        f.write("\n")
        emit(f, "kX", x); emit(f, "kRmsOut", rms_out)
        emit(f, "kEmb", emb); emit(f, "kAlnOut", aln_out)
        emit(f, "kFreqs", freqs); emit(f, "kQ", q); emit(f, "kRotOut", rot)
        f.write("}  // namespace dit_goldens\n")
    print(f"wrote {p}: dim={DIM} heads={HEADS} head_dim={HEAD_DIM} T={T}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
