#!/usr/bin/env python3
"""Generate golden merged weights for the kev LoRA merge test.

The generator and the C++ test rebuild the same base/lora_A/lora_B tensors
from the same FNV-1a -> splitmix64 stream, so no weight byte is checked in.
The golden file carries only config constants, the input tensors, and the
expected merged weights.

The merge formula is W' = W + scaling * (lora_B @ lora_A), where
lora_A is [rank, in], lora_B is [out, rank], and W is [out, in].
This is the rank-r LoRA delta applied to a PyTorch nn.Linear weight.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path

import numpy as np

_MASK64 = (1 << 64) - 1


def fnv1a64(name: str) -> int:
    h = 0xCBF29CE484222325
    for byte in name.encode("utf-8"):
        h ^= byte
        h = (h * 0x100000001B3) & _MASK64
    return h


def splitmix64(x: int) -> int:
    x = (x + 0x9E3779B97F4A7C15) & _MASK64
    z = x
    z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & _MASK64
    z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & _MASK64
    return z ^ (z >> 31)


def rand(name: str, count: int) -> np.ndarray:
    """`count` values uniform in [-1, 1), reproducible from `name` alone."""
    seed = fnv1a64(name)
    out = np.empty(count, dtype=np.float64)
    for i in range(count):
        u = splitmix64((seed + i) & _MASK64)
        out[i] = ((u >> 11) * (2.0**-53)) * 2.0 - 1.0
    return out


def param(name: str, shape, scale: float) -> np.ndarray:
    count = 1
    for s in shape:
        count *= s
    return (rand(name, count).reshape(shape) * scale).astype(np.float32)


def emit_f32(out, name: str, values) -> None:
    flat = np.asarray(values, dtype=np.float32).ravel()
    out.append(f"inline constexpr float {name}[] = {{")
    for i, v in enumerate(flat):
        if i % 6 == 0:
            out.append("\n    ")
        out.append(f"{v:.9e}F, ")
    out.append("\n};\n\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("tests/vllm/models/kev_lora_goldens.inc"),
    )
    args = parser.parse_args()

    # ── Test case 1: small matrix, rank=2 ─────────────────────────────
    out1, in1, rank1, scaling1 = 6, 4, 2, 2.0
    base1 = param("lora_base_1", (out1, in1), 0.3)
    a1 = param("lora_a_1", (rank1, in1), 0.3)
    b1 = param("lora_b_1", (out1, rank1), 0.3)
    delta1 = scaling1 * (b1 @ a1)
    merged1 = (base1 + delta1).astype(np.float32)

    # ── Test case 2: different dimensions, rank=3, fractional scaling ──
    out2, in2, rank2, scaling2 = 8, 5, 3, 1.5
    base2 = param("lora_base_2", (out2, in2), 0.3)
    a2 = param("lora_a_2", (rank2, in2), 0.3)
    b2 = param("lora_b_2", (out2, rank2), 0.3)
    delta2 = scaling2 * (b2 @ a2)
    merged2 = (base2 + delta2).astype(np.float32)

    # ── Emit goldens ───────────────────────────────────────────────────
    out = []
    out.append("// GENERATED by scripts/gen-kev-lora-goldens.py -- do not edit.\n")
    out.append("//\n")
    out.append("// kev LoRA merge goldens: W' = W + scaling * (lora_B @ lora_A)\n")
    out.append("// computed in f64 with numpy.  Inputs and expected merged\n")
    out.append("// weights are rebuilt on both sides from the same FNV-1a ->\n")
    out.append("// splitmix64 stream, so no weight byte is checked in.\n")
    out.append("#pragma once\n\n")
    out.append("#include <cstdint>\n\n")
    out.append("namespace kev_lora_goldens {\n\n")

    out.append(f"inline constexpr int64_t kOut1 = {out1};\n")
    out.append(f"inline constexpr int64_t kIn1 = {in1};\n")
    out.append(f"inline constexpr int64_t kRank1 = {rank1};\n")
    out.append(f"inline constexpr float kScaling1 = {scaling1:.1f}f;\n\n")

    out.append("// Test case 1: base [6,4], rank=2, scaling=2.0.\n")
    emit_f32(out, "kBase1", base1)
    emit_f32(out, "kLoraA1", a1)
    emit_f32(out, "kLoraB1", b1)
    emit_f32(out, "kMerged1", merged1)

    out.append(f"inline constexpr int64_t kOut2 = {out2};\n")
    out.append(f"inline constexpr int64_t kIn2 = {in2};\n")
    out.append(f"inline constexpr int64_t kRank2 = {rank2};\n")
    out.append(f"inline constexpr float kScaling2 = {scaling2:.1f}f;\n\n")

    out.append("// Test case 2: base [8,5], rank=3, scaling=1.5.\n")
    emit_f32(out, "kBase2", base2)
    emit_f32(out, "kLoraA2", a2)
    emit_f32(out, "kLoraB2", b2)
    emit_f32(out, "kMerged2", merged2)

    out.append("}  // namespace kev_lora_goldens\n")
    args.output.write_text("".join(out))
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
