#!/usr/bin/env python3
"""Emit C++ goldens for SeamlessM4TFeatureExtractor: waveform -> w2v-bert input.

The extractor `infer_v2_5.py:173` instantiates, gated against `transformers`
executed directly -- the same secondary oracle `w2vbert.h` already uses, and
admissible for the same reason: it is the reference implementation the model
ships against.

Emitted in THREE pieces so a failure localises instead of just being red:
the povey window, the kaldi mel filterbank, and the final features. Each is a
different kind of mistake.

Usage: python3 scripts/gen-w2v-fbank-goldens.py --out tests/vllm/models/w2v_fbank_goldens.inc
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
from transformers.audio_utils import mel_filter_bank, window_function
from transformers import SeamlessM4TFeatureExtractor


def fmt(values, per_row=6) -> str:
    lines, row = [], []
    for v in values:
        row.append(f"{float(v):.9e}F")
        if len(row) == per_row:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    a = ap.parse_args()

    fe = SeamlessM4TFeatureExtractor(feature_size=80, num_mel_bins=80,
                                     sampling_rate=16000, stride=2,
                                     padding_value=1, return_attention_mask=True)

    window = window_function(400, "povey", periodic=False)
    mel = mel_filter_bank(num_frequency_bins=257, num_mel_filters=80,
                          min_frequency=20, max_frequency=8000,
                          sampling_rate=16000, norm=None, mel_scale="kaldi",
                          triangularize_in_mel_space=True)

    # A deterministic waveform: two tones plus a DC offset, so `remove_dc_offset`
    # and `preemphasis` both have something to do. A zero-mean input cannot tell
    # a port that skips DC removal from one that does not.
    n = 4000
    t = np.arange(n) / 16000.0
    audio = (0.3 * np.sin(2 * np.pi * 220 * t)
             + 0.1 * np.sin(2 * np.pi * 1310 * t)
             + 0.05).astype(np.float32)

    raw = fe._extract_fbank_features(audio)  # [raw_frames, 80], pre-norm
    out = fe(audio, sampling_rate=16000, return_tensors="np")
    feats = np.asarray(out["input_features"])[0]  # [frames, 160]

    body = [
        "// GENERATED by scripts/gen-w2v-fbank-goldens.py -- do not edit.",
        "// Oracle: transformers SeamlessM4TFeatureExtractor, the class",
        "// indextts/infer_v2_5.py:173 instantiates.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace w2v_fbank_goldens {",
        "",
        f"inline constexpr int64_t kSamples = {n};",
        f"inline constexpr int64_t kFrameLength = 400;",
        f"inline constexpr int64_t kHop = 160;",
        f"inline constexpr int64_t kFftLength = 512;",
        f"inline constexpr int64_t kMelBins = 80;",
        f"inline constexpr int64_t kFreqBins = 257;",
        f"inline constexpr int64_t kStride = 2;",
        f"inline constexpr int64_t kFrames = {int(feats.shape[0])};",
        f"inline constexpr int64_t kFeatureWidth = {int(feats.shape[1])};",
        "",
        "// The povey window, length 400. hann^0.85 -- a plain hann still",
        "// produces a spectrogram, just a differently-tapered one.",
        "inline constexpr float kWindow[] = {",
        fmt(window.reshape(-1).tolist()),
        "};",
        "",
        "// The KALDI mel filterbank, [kFreqBins, kMelBins], unnormalized and",
        "// triangularized IN MEL SPACE. The slaney scale is the other common",
        "// choice and gives finite, wrong filters.",
        "inline constexpr float kMelFilters[] = {",
        fmt(mel.reshape(-1).tolist()),
        "};",
        "",
        "// The input waveform, so both sides start from identical samples.",
        "inline constexpr float kAudio[] = {",
        fmt(audio.reshape(-1).tolist()),
        "};",
        "",
        f"inline constexpr int64_t kRawFrames = {int(raw.shape[0])};",
        "",
        "// The log-mel BEFORE normalization, [kRawFrames, kMelBins]. This is",
        "// the well-conditioned quantity and carries the tight tolerance.",
        "inline constexpr float kRawLogMel[] = {",
        fmt(raw.reshape(-1).tolist()),
        "};",
        "",
        "// The extractor's output, [kFrames, kFeatureWidth].",
        "inline constexpr float kFeatures[] = {",
        fmt(feats.reshape(-1).tolist()),
        "};",
        "",
        "}  // namespace w2v_fbank_goldens",
        "",
    ]
    Path(a.out).write_text("\n".join(body))
    print(f"wrote {a.out}: window {window.shape}, mel {mel.shape}, "
          f"features {feats.shape}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
