#!/usr/bin/env python3
"""Emit C++ goldens for the S2Mel DiT's WaveNet final layer.

The shipped `s2mel.pth` carries `net.cfm.estimator.wavenet.*`, and the config
sets `DiT.final_layer_type: wavenet`, so this stack is on the render path, not an
alternative branch. It was missing from the port map entirely until the
checkpoint manifest named it (#634).

Usage: WAVENET_SRC=<path to indextts/s2mel/modules> python3 \
           scripts/gen-wavenet-goldens.py --out tests/vllm/models/wavenet_goldens.inc

Both sides rebuild the same weights from one FNV-1a -> splitmix64 stream, so no
weight bytes are committed and the C++ test needs no fixture file.
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import sys
import types
from pathlib import Path

import torch


def rnd(name: str, n: int, scale: float = 1.0) -> list:
    """FNV-1a over the name seeds splitmix64; the C++ side repeats this."""
    h = 0xCBF29CE484222325
    for ch in name.encode():
        h = ((h ^ ch) * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    out = []
    for _ in range(n):
        h = (h + 0x9E3779B97F4A7C15) & 0xFFFFFFFFFFFFFFFF
        z = h
        z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & 0xFFFFFFFFFFFFFFFF
        z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & 0xFFFFFFFFFFFFFFFF
        z ^= z >> 31
        out.append(((z >> 11) * (1.0 / 9007199254740992.0) * 2.0 - 1.0) * scale)
    return out


def tensor(name: str, shape, scale: float = 1.0) -> torch.Tensor:
    n = 1
    for d in shape:
        n *= d
    return torch.tensor(rnd(name, n, scale), dtype=torch.float64).reshape(shape).float()


def load_wn(src: Path):
    """Import upstream `wavenet.py` with its siblings stubbed."""
    root = src.parents[2]  # .../<repo>/indextts/s2mel/modules -> <repo>
    sys.path.insert(0, str(root))
    for name in ("munch",):
        if name not in sys.modules:
            stub = types.ModuleType(name)
            stub.Munch = dict
            sys.modules[name] = stub
    spec = importlib.util.spec_from_file_location(
        "indextts.s2mel.modules.wavenet", src / "wavenet.py"
    )
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return m.WN


def fmt(values) -> str:
    lines, row = [], []
    for v in values:
        row.append(f"{float(v):.9e}F")
        if len(row) == 6:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    src = Path(os.environ["WAVENET_SRC"])
    WN = load_wn(src)

    # Reduced dims. kernel_size must be odd (upstream asserts it); dilation_rate
    # is 1 in the shipped config, so a value > 1 here is DELIBERATE: it exercises
    # the dilated padding arithmetic the shipped model happens not to reach.
    HIDDEN, KERNEL, DILATION, LAYERS, GIN, FRAMES = 6, 3, 2, 3, 4, 9

    torch.manual_seed(0)
    wn = WN(
        hidden_channels=HIDDEN,
        kernel_size=KERNEL,
        dilation_rate=DILATION,
        n_layers=LAYERS,
        gin_channels=GIN,
        p_dropout=0.0,
        causal=False,
    ).eval()

    # Overwrite every parameter from the shared stream so the C++ side can
    # rebuild them without a fixture. Weight-norm parametrisation keeps (g, v).
    with torch.no_grad():
        for pname, p in sorted(wn.named_parameters()):
            p.copy_(tensor("wn." + pname, list(p.shape), 0.5))

    x = tensor("wn.x", [1, HIDDEN, FRAMES])
    g = tensor("wn.g", [1, GIN, 1])
    mask = torch.ones(1, 1, FRAMES)

    # A mask with trailing zeros. Upstream masks the residual update and the
    # final output but NOT the input to `in_layers`, so a masked run is not the
    # same as a shorter run, and that asymmetry is what this pins.
    masked = torch.ones(1, 1, FRAMES)
    masked[0, 0, FRAMES - 3 :] = 0.0

    with torch.no_grad():
        out_cond = wn(x, mask, g=g)
        out_masked = wn(x, masked, g=g)
        out_nocond = wn(x, mask, g=None) if wn.gin_channels == 0 else None

    names = sorted(n for n, _ in wn.named_parameters())

    body = [
        "// GENERATED by scripts/gen-wavenet-goldens.py -- do not edit.",
        "// Oracle: indextts/s2mel/modules/wavenet.py WN, upstream index-tts",
        "// @4f8792ff120cd3ea470dd511e997a17c86cddd10. The DiT selects this stack",
        "// via config `DiT.final_layer_type: wavenet`, so it is on the render path.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace wavenet_goldens {",
        "",
        f"inline constexpr int64_t kHidden = {HIDDEN};",
        f"inline constexpr int64_t kKernel = {KERNEL};",
        f"inline constexpr int64_t kDilationRate = {DILATION};",
        f"inline constexpr int64_t kLayers = {LAYERS};",
        f"inline constexpr int64_t kGin = {GIN};",
        f"inline constexpr int64_t kFrames = {FRAMES};",
        "",
        "// Parameter names, in the order the C++ side must rebuild them.",
        "inline constexpr const char* kParamNames[] = {",
    ]
    body += [f'    "wn.{n}",' for n in names]
    body += [
        "};",
        "",
        "// Output of WN(x, ones_mask, g) -- [kHidden, kFrames], channel-major.",
        "inline constexpr float kOutCond[] = {",
        fmt(out_cond.reshape(-1).tolist()),
        "};",
        "",
    ]
    body += [
        "// The same run under a mask whose last three frames are zero.",
        "inline constexpr float kMask[] = {",
        fmt(masked.reshape(-1).tolist()),
        "};",
        "",
        "inline constexpr float kOutMasked[] = {",
        fmt(out_masked.reshape(-1).tolist()),
        "};",
        "",
    ]
    if out_nocond is not None:
        body += [
            "inline constexpr float kOutNoCond[] = {",
            fmt(out_nocond.reshape(-1).tolist()),
            "};",
            "",
        ]
    body += ["}  // namespace wavenet_goldens", ""]

    Path(a.out).write_text("\n".join(body))
    print(f"wrote {a.out}: {len(names)} params, out {tuple(out_cond.shape)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
