#!/usr/bin/env python3
"""Emit C++ goldens for the whole S2Mel DiT transformer STACK.

Upstream `indextts/s2mel/modules/gpt_fast/model.py:161-191` (Transformer.forward)
plus its TransformerBlock, index-tts @4f8792ff120cd3ea470dd511e997a17c86cddd10.
This is what sits BETWEEN the ported front end and the ported tail: N blocks,
the U-Net skip routing across them, and a final AdaptiveLayerNorm.

The rotary table is emitted as an INPUT rather than recomputed on our side, so
this gates the stack's composition and not a second implementation of
`precompute_freqs_cis`.

Usage: DIT_SRC=<path to indextts/s2mel/modules> python3 \
           scripts/gen-dit-stack-goldens.py --out tests/vllm/models/dit_stack_goldens.inc
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import sys
import types
from pathlib import Path

import torch


def rnd(name: str, n: int, scale: float = 1.0) -> list:
    h = 0xCBF29CE484222325
    for ch in name.encode():
        h = ((h ^ ch) * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    out = []
    for _ in range(n):
        h = (h + 0x9E3779B97F4A7C15) & 0xFFFFFFFFFFFFFFFF
        z = h
        z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & 0xFFFFFFFFFFFFFFFF
        z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & 0xFFFFFFFFFFFFFFFF
        z ^= z >> 31
        out.append(((z >> 11) * (1.0 / 9007199254740992.0) * 2.0 - 1.0) * scale)
    return out


def tensor(name: str, shape, scale: float = 1.0) -> torch.Tensor:
    n = 1
    for d in shape:
        n *= d
    return torch.tensor(rnd(name, n, scale), dtype=torch.float64).reshape(shape).float()


def fmt(values) -> str:
    lines, row = [], []
    for v in values:
        row.append(f"{float(v):.9e}F")
        if len(row) == 6:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    return "\n".join(lines)


DIM, HEADS, HEAD_DIM, DEPTH, FRAMES = 8, 2, 4, 5, 6
INTERMEDIATE = None  # taken from the constructed model


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    src = Path(os.environ["DIT_SRC"])
    sys.path.insert(0, str(src.parents[2]))
    for name in ("munch",):
        if name not in sys.modules:
            stub = types.ModuleType(name)
            stub.Munch = dict
            sys.modules[name] = stub
    spec = importlib.util.spec_from_file_location(
        "indextts.s2mel.modules.gpt_fast.model", src / "gpt_fast" / "model.py"
    )
    gm = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(gm)

    torch.manual_seed(0)
    args = gm.ModelArgs(block_size=64, n_layer=DEPTH, n_head=HEADS, dim=DIM,
                        head_dim=HEAD_DIM, vocab_size=16,
                        uvit_skip_connection=True, time_as_token=False)
    tr = gm.Transformer(args)
    tr.setup_caches(1, 32, use_kv_cache=False)
    tr.eval()

    with torch.no_grad():
        for pname, p in sorted(tr.named_parameters()):
            p.copy_(tensor("stack." + pname, list(p.shape), 0.5))

    x = tensor("stack.x", [1, FRAMES, DIM])
    c = tensor("stack.c", [1, 1, DIM])
    input_pos = torch.arange(FRAMES)
    mask = torch.ones(1, 1, FRAMES, FRAMES, dtype=torch.bool)

    with torch.no_grad():
        out = tr(x, c, input_pos, mask)
        freqs = tr.freqs_cis[input_pos]  # [FRAMES, head_dim/2, 2]

    inter = tr.layers[0].feed_forward.w1.weight.shape[0]
    names = sorted(n for n, _ in tr.named_parameters())

    body = [
        "// GENERATED by scripts/gen-dit-stack-goldens.py -- do not edit.",
        "// Oracle: gpt_fast/model.py Transformer.forward + TransformerBlock,",
        "// index-tts @4f8792ff120cd3ea470dd511e997a17c86cddd10, with",
        "// uvit_skip_connection: true as the shipped config sets.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace dit_stack_goldens {",
        "",
        f"inline constexpr int64_t kDim = {DIM};",
        f"inline constexpr int64_t kHeads = {HEADS};",
        f"inline constexpr int64_t kHeadDim = {HEAD_DIM};",
        f"inline constexpr int64_t kDepth = {DEPTH};",
        f"inline constexpr int64_t kFrames = {FRAMES};",
        f"inline constexpr int64_t kIntermediate = {int(inter)};",
        f"inline constexpr double kEps = {float(args.norm_eps):.9e};",
        "",
        "inline constexpr const char* kParamNames[] = {",
    ]
    body += [f'    "stack.{n}",' for n in names]
    body += [
        "};",
        "",
        "// The rotary table upstream used, [kFrames, kHeadDim/2, 2]. Emitted as",
        "// an INPUT so this gates composition, not a second rotary implementation.",
        "inline constexpr float kFreqs[] = {",
        fmt(freqs.reshape(-1).tolist()),
        "};",
        "",
        "// Transformer.forward output -- [kFrames, kDim].",
        "inline constexpr float kOut[] = {",
        fmt(out.reshape(-1).tolist()),
        "};",
        "",
        "}  // namespace dit_stack_goldens",
        "",
    ]
    Path(a.out).write_text("\n".join(body))
    print(f"wrote {a.out}: depth {DEPTH}, intermediate {int(inter)}, "
          f"{len(names)} params, out {tuple(out.shape)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
