#!/usr/bin/env python3
"""Emit a `__device__` codebook for `src/vt/cuda/cuda_quant_iq_tables.cuh`.

`cuda_quant_iq_tables.cuh` holds the SAME literals as
`src/vt/cpu/cpu_quant_iq_tables.h` in a second address space, and until this
script existed every one of those tables was a HAND transcription. The runtime
seal (`vt::cuda::SnapshotIqTablesFromDevice`, gated in
`tests/vt/test_cuda_quant_dot.cpp`) catches a slipped literal, but only on a
host that has a CUDA device -- so on the CPU CI leg a drifted table is green.
This script removes the transcription step instead of watching it.

It reads the CPU header, which is the single source of truth, and prints one
array. It never writes the `.cuh`: the caller redirects, so the diff is
reviewable and the generator cannot silently rewrite a table nobody asked about.

    scripts/gen-cuda-iq-tables.py kIq2xsGrid --name d_iq2xs_grid --storage global
    scripts/gen-cuda-iq-tables.py kValuesIq4nl --name d_kvalues_iq4nl

`--storage global` emits a plain `__device__` array and `constant` (the default)
emits `__device__ __constant__`. That choice is a MEASURED one and not a style:
in the warp-per-output matvec the 32 lanes own different super-blocks and so
read different codebook rows, and `__constant__` serialises a divergent read.
Grids indexed by weight bits are therefore `global`; a 16-entry value table is
small enough to stay `constant`, as `d_kvalues_mxfp4` already is.
"""

import argparse
import pathlib
import re
import sys

CPU_HEADER = pathlib.Path(__file__).resolve().parents[1] / "src/vt/cpu/cpu_quant_iq_tables.h"

# One C++ scalar type per array element, mapped to how it must be printed back
# out. The suffix matters: a bare 0x0808080808080808 is not a u64 literal to
# every compiler, and `int8_t` entries are decimal in the CPU header and stay
# decimal here so the two files diff by eye.
FORMATS = {
    "uint64_t": lambda v: "0x%016xULL" % v,
    "uint32_t": lambda v: "0x%08xu" % v,
    "uint16_t": lambda v: "0x%04xu" % v,
    "uint8_t": lambda v: "%d" % v,
    "int8_t": lambda v: "%d" % v,
}
PER_LINE = {"uint64_t": 4, "uint32_t": 6, "uint16_t": 8, "uint8_t": 16, "int8_t": 16}


def read_table(name):
    src = CPU_HEADER.read_text(encoding="utf-8")
    m = re.search(
        r"inline constexpr\s+(\w+)\s+" + re.escape(name) + r"\s*\[\s*(\d+)\s*\]\s*=\s*\{(.*?)\}\s*;",
        src,
        re.S,
    )
    if m is None:
        sys.exit("no `inline constexpr <type> %s[N] = {...};` in %s" % (name, CPU_HEADER))
    ctype, declared, body = m.group(1), int(m.group(2)), m.group(3)
    if ctype not in FORMATS:
        sys.exit("unhandled element type %r for %s" % (ctype, name))
    # Strip // and /* */ comments before splitting, so a commented-out entry
    # cannot be read as a value.
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    body = re.sub(r"//[^\n]*", "", body)
    values = []
    for tok in body.split(","):
        tok = tok.strip()
        if not tok:
            continue
        values.append(int(tok.rstrip("uUlL"), 0))
    if len(values) != declared:
        sys.exit("%s declares [%d] but holds %d values" % (name, declared, len(values)))
    return ctype, values


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("cpu_symbol", help="the `vt::cpu::` table to mirror, e.g. kIq2xsGrid")
    ap.add_argument("--name", required=True, help="the device symbol to emit, e.g. d_iq2xs_grid")
    ap.add_argument("--storage", choices=("constant", "global"), default="constant")
    args = ap.parse_args()

    ctype, values = read_table(args.cpu_symbol)
    per = PER_LINE[ctype]
    fmt = FORMATS[ctype]
    qualifier = "__device__" if args.storage == "global" else "__device__ __constant__"
    trailer = "  // GLOBAL (not __constant__)" if args.storage == "global" else ""

    print("// GENERATED by scripts/gen-cuda-iq-tables.py from")
    print("// src/vt/cpu/cpu_quant_iq_tables.h::%s -- do not hand edit." % args.cpu_symbol)
    print("%s %s %s[%d] = {%s" % (qualifier, ctype, args.name, len(values), trailer))
    for i in range(0, len(values), per):
        print("    " + ", ".join(fmt(v) for v in values[i : i + per]) + ",")
    print("};")


if __name__ == "__main__":
    main()
