/*
 * vllm.cpp VENDORED Triton AOT artifact — GENERATED CODE. DO NOT EDIT.
 *
 * Generated by `python -m triton.tools.compile` / `triton.tools.link` from
 * triton_kernels/wy_fast.py (kernel recompute_w_u_fwd_kernel); the embedded byte
 * array (if any) is the compiled cubin for the arch named by this
 * directory. Generator versions, kernel-source hashes and the exact
 * generation parameters are recorded in the MANIFEST next to this file.
 *
 * Regenerate (MAINTAINER task; needs Python + Triton + a visible GPU):
 *   scripts/regen-triton-aot.sh
 *
 * The generating kernel source (triton_kernels/wy_fast.py) is ported
 * verbatim from flash-linear-attention via vLLM (MIT; see its header);
 * this generated artifact is distributed under the repository's
 * Apache-2.0 license (see LICENSE and NOTICE).
 */
#include <cuda.h>

CUresult gdn_wu_h48_48x16x128x128x64x64x64x1_warps4xstages3(CUstream stream, CUdeviceptr k, CUdeviceptr v, CUdeviceptr beta, CUdeviceptr w, CUdeviceptr u, CUdeviceptr A, CUdeviceptr g, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);
void load_gdn_wu_h48_48x16x128x128x64x64x64x1_warps4xstages3();
void unload_gdn_wu_h48_48x16x128x128x64x64x64x1_warps4xstages3();

int gdn_wu_h48_get_num_algos(void);

CUresult gdn_wu_h48_default(CUstream stream, CUdeviceptr k, CUdeviceptr v, CUdeviceptr beta, CUdeviceptr w, CUdeviceptr u, CUdeviceptr A, CUdeviceptr g, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);
CUresult gdn_wu_h48(CUstream stream, CUdeviceptr k, CUdeviceptr v, CUdeviceptr beta, CUdeviceptr w, CUdeviceptr u, CUdeviceptr A, CUdeviceptr g, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT, int algo_id);
void load_gdn_wu_h48();
void unload_gdn_wu_h48();
