/*
 * vllm.cpp VENDORED Triton AOT artifact — GENERATED CODE. DO NOT EDIT.
 *
 * Generated by `scripts/triton-aot-compile.py` / `triton.tools.link` from
 * triton_kernels/wy_fast.py (kernel recompute_w_u_fwd_kernel); the embedded byte
 * array (if any) is the compiled cubin for the arch named by this
 * directory. Generator versions, kernel-source hashes and the exact
 * generation parameters are recorded in the MANIFEST next to this file.
 *
 * Regenerate (MAINTAINER task; needs Python + Triton + ptxas):
 *   scripts/regen-triton-aot.sh
 *
 * The generating kernel source (triton_kernels/wy_fast.py) is ported
 * verbatim from flash-linear-attention via vLLM (MIT; see its header);
 * this generated artifact is distributed under the repository's
 * Apache-2.0 license (see LICENSE and NOTICE).
 */
#ifndef TT_KERNEL_INCLUDES
#define TT_KERNEL_INCLUDES

#include <cuda.h>
#include <inttypes.h>
#include <stdint.h>
#include <stdio.h>

#endif

void unload_gdn_wu_h48_f1c2dbdd_0d1d2d3d4d5d6d7d8d9101112131415161718(void);
void load_gdn_wu_h48_f1c2dbdd_0d1d2d3d4d5d6d7d8d9101112131415161718(void);
// tt-linker: gdn_wu_h48_f1c2dbdd_0d1d2d3d4d5d6d7d8d9101112131415161718:CUdeviceptr k, CUdeviceptr v, CUdeviceptr beta, CUdeviceptr w, CUdeviceptr u, CUdeviceptr A, CUdeviceptr g, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT:48x16x128x128x64x64x64x1_warps4xstages3
CUresult gdn_wu_h48_f1c2dbdd_0d1d2d3d4d5d6d7d8d9101112131415161718(CUstream stream, CUdeviceptr k, CUdeviceptr v, CUdeviceptr beta, CUdeviceptr w, CUdeviceptr u, CUdeviceptr A, CUdeviceptr g, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);
