/*
 * vllm.cpp VENDORED Triton AOT artifact — GENERATED CODE. DO NOT EDIT.
 *
 * Generated by `python -m triton.tools.compile` / `triton.tools.link` from
 * triton_kernels/chunk_delta_h.py (kernel chunk_gated_delta_rule_fwd_kernel_h_blockdim64); the embedded byte
 * array (if any) is the compiled cubin for the arch named by this
 * directory. Generator versions, kernel-source hashes and the exact
 * generation parameters are recorded in the MANIFEST next to this file.
 *
 * Regenerate (MAINTAINER task; needs Python + Triton + a visible GPU):
 *   scripts/regen-triton-aot.sh
 *
 * The generating kernel source (triton_kernels/chunk_delta_h.py) is ported
 * verbatim from flash-linear-attention via vLLM (MIT; see its header);
 * this generated artifact is distributed under the repository's
 * Apache-2.0 license (see LICENSE and NOTICE).
 */
#include <cuda.h>

CUresult gdn_deltah_h32_32x16x128x128x64x64x1x0x1x1x1x1x0_warps4xstages3(CUstream stream, CUdeviceptr k, CUdeviceptr v, CUdeviceptr w, CUdeviceptr v_new, CUdeviceptr g, CUdeviceptr gk, CUdeviceptr h, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr cu_seqlens, CUdeviceptr chunk_offsets, int32_t T, int32_t NH);
void load_gdn_deltah_h32_32x16x128x128x64x64x1x0x1x1x1x1x0_warps4xstages3();
void unload_gdn_deltah_h32_32x16x128x128x64x64x1x0x1x1x1x1x0_warps4xstages3();

int gdn_deltah_h32_get_num_algos(void);

CUresult gdn_deltah_h32_default(CUstream stream, CUdeviceptr k, CUdeviceptr v, CUdeviceptr w, CUdeviceptr v_new, CUdeviceptr g, CUdeviceptr gk, CUdeviceptr h, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr cu_seqlens, CUdeviceptr chunk_offsets, int32_t T, int32_t NH);
CUresult gdn_deltah_h32(CUstream stream, CUdeviceptr k, CUdeviceptr v, CUdeviceptr w, CUdeviceptr v_new, CUdeviceptr g, CUdeviceptr gk, CUdeviceptr h, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr cu_seqlens, CUdeviceptr chunk_offsets, int32_t T, int32_t NH, int algo_id);
void load_gdn_deltah_h32();
void unload_gdn_deltah_h32();
