/*
 * vllm.cpp VENDORED Triton AOT artifact — GENERATED CODE. DO NOT EDIT.
 *
 * Generated by `scripts/triton-aot-compile.py` / `triton.tools.link` from
 * triton_kernels/chunk_scaled_dot_kkt.py (kernel chunk_scaled_dot_kkt_fwd_kernel); the embedded byte
 * array (if any) is the compiled cubin for the arch named by this
 * directory. Generator versions, kernel-source hashes and the exact
 * generation parameters are recorded in the MANIFEST next to this file.
 *
 * Regenerate (MAINTAINER task; needs Python + Triton + ptxas):
 *   scripts/regen-triton-aot.sh
 *
 * The generating kernel source (triton_kernels/chunk_scaled_dot_kkt.py) is ported
 * verbatim from flash-linear-attention via vLLM (MIT; see its header);
 * this generated artifact is distributed under the repository's
 * Apache-2.0 license (see LICENSE and NOTICE).
 */
#include <cuda.h>
#include <stdint.h>
#include <assert.h>

// launcher for: gdn_kkt_h48_48x16x128x64x128x1x1_warps8xstages3
CUresult gdn_kkt_h48_6c65858f_0d1d2d3d4d5d67891011121314(CUstream stream, CUdeviceptr k, CUdeviceptr beta, CUdeviceptr g, CUdeviceptr A, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);

CUresult gdn_kkt_h48_48x16x128x64x128x1x1_warps8xstages3(CUstream stream, CUdeviceptr k, CUdeviceptr beta, CUdeviceptr g, CUdeviceptr A, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT){
  if ((k % 16 == 0) && (beta % 16 == 0) && (g % 16 == 0) && (A % 16 == 0) && (cu_seqlens % 16 == 0) && (chunk_indices % 16 == 0))
    return gdn_kkt_h48_6c65858f_0d1d2d3d4d5d67891011121314(stream, k, beta, g, A, cu_seqlens, chunk_indices, T, NT);

  return CUDA_ERROR_INVALID_VALUE;
}

// load for: gdn_kkt_h48_48x16x128x64x128x1x1_warps8xstages3
void load_gdn_kkt_h48_6c65858f_0d1d2d3d4d5d67891011121314();
void load_gdn_kkt_h48_48x16x128x64x128x1x1_warps8xstages3() {
  load_gdn_kkt_h48_6c65858f_0d1d2d3d4d5d67891011121314();
}

// unload for: gdn_kkt_h48_48x16x128x64x128x1x1_warps8xstages3
void unload_gdn_kkt_h48_6c65858f_0d1d2d3d4d5d67891011121314();
void unload_gdn_kkt_h48_48x16x128x64x128x1x1_warps8xstages3() {
  unload_gdn_kkt_h48_6c65858f_0d1d2d3d4d5d67891011121314();
}

typedef CUresult (*kernel_func_t)(CUstream stream, CUdeviceptr k, CUdeviceptr beta, CUdeviceptr g, CUdeviceptr A, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);
kernel_func_t gdn_kkt_h48_kernels[] = {
  gdn_kkt_h48_48x16x128x64x128x1x1_warps8xstages3,
};

int gdn_kkt_h48_get_num_algos(void){
  return (int)(sizeof(gdn_kkt_h48_kernels) / sizeof(gdn_kkt_h48_kernels[0]));
}

CUresult gdn_kkt_h48(CUstream stream, CUdeviceptr k, CUdeviceptr beta, CUdeviceptr g, CUdeviceptr A, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT, int algo_id){
  assert (algo_id < (int)sizeof(gdn_kkt_h48_kernels));
  return gdn_kkt_h48_kernels[algo_id](stream, k, beta, g, A, cu_seqlens, chunk_indices, T, NT);
}

void load_gdn_kkt_h48(void){
  load_gdn_kkt_h48_48x16x128x64x128x1x1_warps8xstages3();
}

void unload_gdn_kkt_h48(void){
  unload_gdn_kkt_h48_48x16x128x64x128x1x1_warps8xstages3();
}


CUresult gdn_kkt_h48_default(CUstream stream, CUdeviceptr k, CUdeviceptr beta, CUdeviceptr g, CUdeviceptr A, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT){
  return gdn_kkt_h48(stream, k, beta, g, A, cu_seqlens, chunk_indices, T, NT, 0);
}
