/*
 * vllm.cpp VENDORED Triton AOT artifact — GENERATED CODE. DO NOT EDIT.
 *
 * Generated by `scripts/triton-aot-compile.py` / `triton.tools.link` from
 * triton_kernels/fused_recurrent_packed_decode.py (kernel fused_recurrent_gated_delta_rule_packed_decode_kernel); the embedded byte
 * array (if any) is the compiled cubin for the arch named by this
 * directory. Generator versions, kernel-source hashes and the exact
 * generation parameters are recorded in the MANIFEST next to this file.
 *
 * Regenerate (MAINTAINER task; needs Python + Triton + ptxas):
 *   scripts/regen-triton-aot.sh
 *
 * The generating kernel source (triton_kernels/fused_recurrent_packed_decode.py) is ported
 * verbatim from flash-linear-attention via vLLM (MIT; see its header);
 * this generated artifact is distributed under the repository's
 * Apache-2.0 license (see LICENSE and NOTICE).
 */
#include <cuda.h>
#include <stdint.h>
#include <assert.h>

// launcher for: gdn_decode_h32_8192x64x64x524288x524288x1x16x32x128x128x128x32x20x1_warps1xstages3
CUresult gdn_decode_h32_d32e909a_0d1d2d3d4d5d6d7d8d91011121314151617181920212223(CUstream stream, CUdeviceptr mixed_qkv, CUdeviceptr a, CUdeviceptr b, CUdeviceptr A_log, CUdeviceptr dt_bias, CUdeviceptr o, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr ssm_state_indices, int32_t NBH);

CUresult gdn_decode_h32_8192x64x64x524288x524288x1x16x32x128x128x128x32x20x1_warps1xstages3(CUstream stream, CUdeviceptr mixed_qkv, CUdeviceptr a, CUdeviceptr b, CUdeviceptr A_log, CUdeviceptr dt_bias, CUdeviceptr o, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr ssm_state_indices, int32_t NBH){
  if ((mixed_qkv % 16 == 0) && (a % 16 == 0) && (b % 16 == 0) && (A_log % 16 == 0) && (dt_bias % 16 == 0) && (o % 16 == 0) && (h0 % 16 == 0) && (ht % 16 == 0) && (ssm_state_indices % 16 == 0))
    return gdn_decode_h32_d32e909a_0d1d2d3d4d5d6d7d8d91011121314151617181920212223(stream, mixed_qkv, a, b, A_log, dt_bias, o, h0, ht, ssm_state_indices, NBH);

  return CUDA_ERROR_INVALID_VALUE;
}

// load for: gdn_decode_h32_8192x64x64x524288x524288x1x16x32x128x128x128x32x20x1_warps1xstages3
void load_gdn_decode_h32_d32e909a_0d1d2d3d4d5d6d7d8d91011121314151617181920212223();
void load_gdn_decode_h32_8192x64x64x524288x524288x1x16x32x128x128x128x32x20x1_warps1xstages3() {
  load_gdn_decode_h32_d32e909a_0d1d2d3d4d5d6d7d8d91011121314151617181920212223();
}

// unload for: gdn_decode_h32_8192x64x64x524288x524288x1x16x32x128x128x128x32x20x1_warps1xstages3
void unload_gdn_decode_h32_d32e909a_0d1d2d3d4d5d6d7d8d91011121314151617181920212223();
void unload_gdn_decode_h32_8192x64x64x524288x524288x1x16x32x128x128x128x32x20x1_warps1xstages3() {
  unload_gdn_decode_h32_d32e909a_0d1d2d3d4d5d6d7d8d91011121314151617181920212223();
}

typedef CUresult (*kernel_func_t)(CUstream stream, CUdeviceptr mixed_qkv, CUdeviceptr a, CUdeviceptr b, CUdeviceptr A_log, CUdeviceptr dt_bias, CUdeviceptr o, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr ssm_state_indices, int32_t NBH);
kernel_func_t gdn_decode_h32_kernels[] = {
  gdn_decode_h32_8192x64x64x524288x524288x1x16x32x128x128x128x32x20x1_warps1xstages3,
};

int gdn_decode_h32_get_num_algos(void){
  return (int)(sizeof(gdn_decode_h32_kernels) / sizeof(gdn_decode_h32_kernels[0]));
}

CUresult gdn_decode_h32(CUstream stream, CUdeviceptr mixed_qkv, CUdeviceptr a, CUdeviceptr b, CUdeviceptr A_log, CUdeviceptr dt_bias, CUdeviceptr o, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr ssm_state_indices, int32_t NBH, int algo_id){
  assert (algo_id < (int)sizeof(gdn_decode_h32_kernels));
  return gdn_decode_h32_kernels[algo_id](stream, mixed_qkv, a, b, A_log, dt_bias, o, h0, ht, ssm_state_indices, NBH);
}

void load_gdn_decode_h32(void){
  load_gdn_decode_h32_8192x64x64x524288x524288x1x16x32x128x128x128x32x20x1_warps1xstages3();
}

void unload_gdn_decode_h32(void){
  unload_gdn_decode_h32_8192x64x64x524288x524288x1x16x32x128x128x128x32x20x1_warps1xstages3();
}


CUresult gdn_decode_h32_default(CUstream stream, CUdeviceptr mixed_qkv, CUdeviceptr a, CUdeviceptr b, CUdeviceptr A_log, CUdeviceptr dt_bias, CUdeviceptr o, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr ssm_state_indices, int32_t NBH){
  return gdn_decode_h32(stream, mixed_qkv, a, b, A_log, dt_bias, o, h0, ht, ssm_state_indices, NBH, 0);
}
