/*
 * vllm.cpp VENDORED Triton AOT artifact — GENERATED CODE. DO NOT EDIT.
 *
 * Generated by `python -m triton.tools.compile` / `triton.tools.link` from
 * triton_kernels/solve_tril.py (kernel merge_16x16_to_64x64_inverse_kernel); the embedded byte
 * array (if any) is the compiled cubin for the arch named by this
 * directory. Generator versions, kernel-source hashes and the exact
 * generation parameters are recorded in the MANIFEST next to this file.
 *
 * Regenerate (MAINTAINER task; needs Python + Triton + a visible GPU):
 *   scripts/regen-triton-aot.sh
 *
 * The generating kernel source (triton_kernels/solve_tril.py) is ported
 * verbatim from flash-linear-attention via vLLM (MIT; see its header);
 * this generated artifact is distributed under the repository's
 * Apache-2.0 license (see LICENSE and NOTICE).
 */
#include <cuda.h>
#include <stdint.h>
#include <assert.h>

// launcher for: gdn_tril_h48_48x64x1_warps4xstages3
CUresult gdn_tril_h48_db00fe7c_0d1d2d3d45678(CUstream stream, CUdeviceptr A, CUdeviceptr Ai, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);

CUresult gdn_tril_h48_48x64x1_warps4xstages3(CUstream stream, CUdeviceptr A, CUdeviceptr Ai, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT){
  if ((A % 16 == 0) && (Ai % 16 == 0) && (cu_seqlens % 16 == 0) && (chunk_indices % 16 == 0))
    return gdn_tril_h48_db00fe7c_0d1d2d3d45678(stream, A, Ai, cu_seqlens, chunk_indices, T, NT);

  return CUDA_ERROR_INVALID_VALUE;
}

// load for: gdn_tril_h48_48x64x1_warps4xstages3
void load_gdn_tril_h48_db00fe7c_0d1d2d3d45678();
void load_gdn_tril_h48_48x64x1_warps4xstages3() {
  load_gdn_tril_h48_db00fe7c_0d1d2d3d45678();
}

// unload for: gdn_tril_h48_48x64x1_warps4xstages3
void unload_gdn_tril_h48_db00fe7c_0d1d2d3d45678();
void unload_gdn_tril_h48_48x64x1_warps4xstages3() {
  unload_gdn_tril_h48_db00fe7c_0d1d2d3d45678();
}

typedef CUresult (*kernel_func_t)(CUstream stream, CUdeviceptr A, CUdeviceptr Ai, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);
kernel_func_t gdn_tril_h48_kernels[] = {
  gdn_tril_h48_48x64x1_warps4xstages3,
};

int gdn_tril_h48_get_num_algos(void){
  return (int)(sizeof(gdn_tril_h48_kernels) / sizeof(gdn_tril_h48_kernels[0]));
}

CUresult gdn_tril_h48(CUstream stream, CUdeviceptr A, CUdeviceptr Ai, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT, int algo_id){
  assert (algo_id < (int)sizeof(gdn_tril_h48_kernels));
  return gdn_tril_h48_kernels[algo_id](stream, A, Ai, cu_seqlens, chunk_indices, T, NT);
}

void load_gdn_tril_h48(void){
  load_gdn_tril_h48_48x64x1_warps4xstages3();
}

void unload_gdn_tril_h48(void){
  unload_gdn_tril_h48_48x64x1_warps4xstages3();
}


CUresult gdn_tril_h48_default(CUstream stream, CUdeviceptr A, CUdeviceptr Ai, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT){
  return gdn_tril_h48(stream, A, Ai, cu_seqlens, chunk_indices, T, NT, 0);
}
