/*
 * vllm.cpp VENDORED Triton AOT artifact — GENERATED CODE. DO NOT EDIT.
 *
 * Generated by `scripts/triton-aot-compile.py` / `triton.tools.link` from
 * triton_kernels/solve_tril.py (kernel merge_16x16_to_64x64_inverse_kernel); the embedded byte
 * array (if any) is the compiled cubin for the arch named by this
 * directory. Generator versions, kernel-source hashes and the exact
 * generation parameters are recorded in the MANIFEST next to this file.
 *
 * Regenerate (MAINTAINER task; needs Python + Triton + ptxas):
 *   scripts/regen-triton-aot.sh
 *
 * The generating kernel source (triton_kernels/solve_tril.py) is ported
 * verbatim from flash-linear-attention via vLLM (MIT; see its header);
 * this generated artifact is distributed under the repository's
 * Apache-2.0 license (see LICENSE and NOTICE).
 */
#include <cuda.h>

CUresult gdn_tril_h32_32x64x1_warps4xstages3(CUstream stream, CUdeviceptr A, CUdeviceptr Ai, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);
void load_gdn_tril_h32_32x64x1_warps4xstages3();
void unload_gdn_tril_h32_32x64x1_warps4xstages3();

int gdn_tril_h32_get_num_algos(void);

CUresult gdn_tril_h32_default(CUstream stream, CUdeviceptr A, CUdeviceptr Ai, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);
CUresult gdn_tril_h32(CUstream stream, CUdeviceptr A, CUdeviceptr Ai, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT, int algo_id);
void load_gdn_tril_h32();
void unload_gdn_tril_h32();
