/*
 * vllm.cpp VENDORED Triton AOT artifact — GENERATED CODE. DO NOT EDIT.
 *
 * Generated by `scripts/triton-aot-compile.py` / `triton.tools.link` from
 * triton_kernels/chunk_scaled_dot_kkt.py (kernel chunk_scaled_dot_kkt_fwd_kernel); the embedded byte
 * array (if any) is the compiled cubin for the arch named by this
 * directory. Generator versions, kernel-source hashes and the exact
 * generation parameters are recorded in the MANIFEST next to this file.
 *
 * Regenerate (MAINTAINER task; needs Python + Triton + ptxas):
 *   scripts/regen-triton-aot.sh
 *
 * The generating kernel source (triton_kernels/chunk_scaled_dot_kkt.py) is ported
 * verbatim from flash-linear-attention via vLLM (MIT; see its header);
 * this generated artifact is distributed under the repository's
 * Apache-2.0 license (see LICENSE and NOTICE).
 */
#ifndef TT_KERNEL_INCLUDES
#define TT_KERNEL_INCLUDES

#include <cuda.h>
#include <inttypes.h>
#include <stdint.h>
#include <stdio.h>

#endif

void unload_gdn_kkt_h32_8538f717_0d1d2d3d4d5d67891011121314(void);
void load_gdn_kkt_h32_8538f717_0d1d2d3d4d5d67891011121314(void);
// tt-linker: gdn_kkt_h32_8538f717_0d1d2d3d4d5d67891011121314:CUdeviceptr k, CUdeviceptr beta, CUdeviceptr g, CUdeviceptr A, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT:32x16x128x64x64x1x1_warps4xstages3
CUresult gdn_kkt_h32_8538f717_0d1d2d3d4d5d67891011121314(CUstream stream, CUdeviceptr k, CUdeviceptr beta, CUdeviceptr g, CUdeviceptr A, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);
