/*
 * vllm.cpp VENDORED Triton AOT artifact — GENERATED CODE. DO NOT EDIT.
 *
 * Generated by `scripts/triton-aot-compile.py` / `triton.tools.link` from
 * triton_kernels/chunk_delta_h.py (kernel chunk_gated_delta_rule_fwd_kernel_h_blockdim64); the embedded byte
 * array (if any) is the compiled cubin for the arch named by this
 * directory. Generator versions, kernel-source hashes and the exact
 * generation parameters are recorded in the MANIFEST next to this file.
 *
 * Regenerate (MAINTAINER task; needs Python + Triton + ptxas):
 *   scripts/regen-triton-aot.sh
 *
 * The generating kernel source (triton_kernels/chunk_delta_h.py) is ported
 * verbatim from flash-linear-attention via vLLM (MIT; see its header);
 * this generated artifact is distributed under the repository's
 * Apache-2.0 license (see LICENSE and NOTICE).
 */
#include <cuda.h>
#include <stdint.h>
#include <assert.h>

// launcher for: gdn_deltah_h48_48x16x128x128x64x64x1x0x1x1x1x1x0_warps4xstages3
CUresult gdn_deltah_h48_4841de36_0d1d2d3d4d56d7d8d9d10d111213141516171819202122232425(CUstream stream, CUdeviceptr k, CUdeviceptr v, CUdeviceptr w, CUdeviceptr v_new, CUdeviceptr g, CUdeviceptr gk, CUdeviceptr h, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr cu_seqlens, CUdeviceptr chunk_offsets, int32_t T, int32_t NH);

CUresult gdn_deltah_h48_48x16x128x128x64x64x1x0x1x1x1x1x0_warps4xstages3(CUstream stream, CUdeviceptr k, CUdeviceptr v, CUdeviceptr w, CUdeviceptr v_new, CUdeviceptr g, CUdeviceptr gk, CUdeviceptr h, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr cu_seqlens, CUdeviceptr chunk_offsets, int32_t T, int32_t NH){
  if ((k % 16 == 0) && (v % 16 == 0) && (w % 16 == 0) && (v_new % 16 == 0) && (g % 16 == 0) && (h % 16 == 0) && (h0 % 16 == 0) && (ht % 16 == 0) && (cu_seqlens % 16 == 0) && (chunk_offsets % 16 == 0))
    return gdn_deltah_h48_4841de36_0d1d2d3d4d56d7d8d9d10d111213141516171819202122232425(stream, k, v, w, v_new, g, gk, h, h0, ht, cu_seqlens, chunk_offsets, T, NH);

  return CUDA_ERROR_INVALID_VALUE;
}

// load for: gdn_deltah_h48_48x16x128x128x64x64x1x0x1x1x1x1x0_warps4xstages3
void load_gdn_deltah_h48_4841de36_0d1d2d3d4d56d7d8d9d10d111213141516171819202122232425();
void load_gdn_deltah_h48_48x16x128x128x64x64x1x0x1x1x1x1x0_warps4xstages3() {
  load_gdn_deltah_h48_4841de36_0d1d2d3d4d56d7d8d9d10d111213141516171819202122232425();
}

// unload for: gdn_deltah_h48_48x16x128x128x64x64x1x0x1x1x1x1x0_warps4xstages3
void unload_gdn_deltah_h48_4841de36_0d1d2d3d4d56d7d8d9d10d111213141516171819202122232425();
void unload_gdn_deltah_h48_48x16x128x128x64x64x1x0x1x1x1x1x0_warps4xstages3() {
  unload_gdn_deltah_h48_4841de36_0d1d2d3d4d56d7d8d9d10d111213141516171819202122232425();
}

typedef CUresult (*kernel_func_t)(CUstream stream, CUdeviceptr k, CUdeviceptr v, CUdeviceptr w, CUdeviceptr v_new, CUdeviceptr g, CUdeviceptr gk, CUdeviceptr h, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr cu_seqlens, CUdeviceptr chunk_offsets, int32_t T, int32_t NH);
kernel_func_t gdn_deltah_h48_kernels[] = {
  gdn_deltah_h48_48x16x128x128x64x64x1x0x1x1x1x1x0_warps4xstages3,
};

int gdn_deltah_h48_get_num_algos(void){
  return (int)(sizeof(gdn_deltah_h48_kernels) / sizeof(gdn_deltah_h48_kernels[0]));
}

CUresult gdn_deltah_h48(CUstream stream, CUdeviceptr k, CUdeviceptr v, CUdeviceptr w, CUdeviceptr v_new, CUdeviceptr g, CUdeviceptr gk, CUdeviceptr h, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr cu_seqlens, CUdeviceptr chunk_offsets, int32_t T, int32_t NH, int algo_id){
  assert (algo_id < (int)sizeof(gdn_deltah_h48_kernels));
  return gdn_deltah_h48_kernels[algo_id](stream, k, v, w, v_new, g, gk, h, h0, ht, cu_seqlens, chunk_offsets, T, NH);
}

void load_gdn_deltah_h48(void){
  load_gdn_deltah_h48_48x16x128x128x64x64x1x0x1x1x1x1x0_warps4xstages3();
}

void unload_gdn_deltah_h48(void){
  unload_gdn_deltah_h48_48x16x128x128x64x64x1x0x1x1x1x1x0_warps4xstages3();
}


CUresult gdn_deltah_h48_default(CUstream stream, CUdeviceptr k, CUdeviceptr v, CUdeviceptr w, CUdeviceptr v_new, CUdeviceptr g, CUdeviceptr gk, CUdeviceptr h, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr cu_seqlens, CUdeviceptr chunk_offsets, int32_t T, int32_t NH){
  return gdn_deltah_h48(stream, k, v, w, v_new, g, gk, h, h0, ht, cu_seqlens, chunk_offsets, T, NH, 0);
}
