/*
 * vllm.cpp VENDORED Triton AOT artifact — GENERATED CODE. DO NOT EDIT.
 *
 * Generated by `python -m triton.tools.compile` / `triton.tools.link` from
 * triton_kernels/solve_tril.py (kernel merge_16x16_to_64x64_inverse_kernel); the embedded byte
 * array (if any) is the compiled cubin for the arch named by this
 * directory. Generator versions, kernel-source hashes and the exact
 * generation parameters are recorded in the MANIFEST next to this file.
 *
 * Regenerate (MAINTAINER task; needs Python + Triton + a visible GPU):
 *   scripts/regen-triton-aot.sh
 *
 * The generating kernel source (triton_kernels/solve_tril.py) is ported
 * verbatim from flash-linear-attention via vLLM (MIT; see its header);
 * this generated artifact is distributed under the repository's
 * Apache-2.0 license (see LICENSE and NOTICE).
 */
#ifndef TT_KERNEL_INCLUDES
#define TT_KERNEL_INCLUDES

#include <cuda.h>
#include <inttypes.h>
#include <stdint.h>
#include <stdio.h>

#endif

void unload_gdn_tril_h32_31103791_0d1d2d3d45678(void);
void load_gdn_tril_h32_31103791_0d1d2d3d45678(void);
// tt-linker: gdn_tril_h32_31103791_0d1d2d3d45678:CUdeviceptr A, CUdeviceptr Ai, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT:32x64x1_warps4xstages3
CUresult gdn_tril_h32_31103791_0d1d2d3d45678(CUstream stream, CUdeviceptr A, CUdeviceptr Ai, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);
