/*
 * vllm.cpp VENDORED Triton AOT artifact — GENERATED CODE. DO NOT EDIT.
 *
 * Generated by `scripts/triton-aot-compile.py` / `triton.tools.link` from
 * triton_kernels/fused_recurrent_packed_decode.py (kernel fused_recurrent_gated_delta_rule_packed_decode_kernel); the embedded byte
 * array (if any) is the compiled cubin for the arch named by this
 * directory. Generator versions, kernel-source hashes and the exact
 * generation parameters are recorded in the MANIFEST next to this file.
 *
 * Regenerate (MAINTAINER task; needs Python + Triton + ptxas):
 *   scripts/regen-triton-aot.sh
 *
 * The generating kernel source (triton_kernels/fused_recurrent_packed_decode.py) is ported
 * verbatim from flash-linear-attention via vLLM (MIT; see its header);
 * this generated artifact is distributed under the repository's
 * Apache-2.0 license (see LICENSE and NOTICE).
 */
#include <cuda.h>

CUresult gdn_decode_h32_8192x64x64x524288x524288x1x16x32x128x128x128x32x20x1_warps1xstages3(CUstream stream, CUdeviceptr mixed_qkv, CUdeviceptr a, CUdeviceptr b, CUdeviceptr A_log, CUdeviceptr dt_bias, CUdeviceptr o, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr ssm_state_indices, int32_t NBH);
void load_gdn_decode_h32_8192x64x64x524288x524288x1x16x32x128x128x128x32x20x1_warps1xstages3();
void unload_gdn_decode_h32_8192x64x64x524288x524288x1x16x32x128x128x128x32x20x1_warps1xstages3();

int gdn_decode_h32_get_num_algos(void);

CUresult gdn_decode_h32_default(CUstream stream, CUdeviceptr mixed_qkv, CUdeviceptr a, CUdeviceptr b, CUdeviceptr A_log, CUdeviceptr dt_bias, CUdeviceptr o, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr ssm_state_indices, int32_t NBH);
CUresult gdn_decode_h32(CUstream stream, CUdeviceptr mixed_qkv, CUdeviceptr a, CUdeviceptr b, CUdeviceptr A_log, CUdeviceptr dt_bias, CUdeviceptr o, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr ssm_state_indices, int32_t NBH, int algo_id);
void load_gdn_decode_h32();
void unload_gdn_decode_h32();
