/*
 * vllm.cpp VENDORED Triton AOT artifact — GENERATED CODE. DO NOT EDIT.
 *
 * Generated by `scripts/triton-aot-compile.py` / `triton.tools.link` from
 * triton_kernels/chunk_delta_h.py (kernel chunk_gated_delta_rule_fwd_kernel_h_blockdim64); the embedded byte
 * array (if any) is the compiled cubin for the arch named by this
 * directory. Generator versions, kernel-source hashes and the exact
 * generation parameters are recorded in the MANIFEST next to this file.
 *
 * Regenerate (MAINTAINER task; needs Python + Triton + ptxas):
 *   scripts/regen-triton-aot.sh
 *
 * The generating kernel source (triton_kernels/chunk_delta_h.py) is ported
 * verbatim from flash-linear-attention via vLLM (MIT; see its header);
 * this generated artifact is distributed under the repository's
 * Apache-2.0 license (see LICENSE and NOTICE).
 */
#ifndef TT_KERNEL_INCLUDES
#define TT_KERNEL_INCLUDES

#include <cuda.h>
#include <inttypes.h>
#include <stdint.h>
#include <stdio.h>

#endif

void unload_gdn_deltah_h48_4841de36_0d1d2d3d4d56d7d8d9d10d111213141516171819202122232425(void);
void load_gdn_deltah_h48_4841de36_0d1d2d3d4d56d7d8d9d10d111213141516171819202122232425(void);
// tt-linker: gdn_deltah_h48_4841de36_0d1d2d3d4d56d7d8d9d10d111213141516171819202122232425:CUdeviceptr k, CUdeviceptr v, CUdeviceptr w, CUdeviceptr v_new, CUdeviceptr g, CUdeviceptr gk, CUdeviceptr h, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr cu_seqlens, CUdeviceptr chunk_offsets, int32_t T, int32_t NH:48x16x128x128x64x64x1x0x1x1x1x1x0_warps4xstages3
CUresult gdn_deltah_h48_4841de36_0d1d2d3d4d56d7d8d9d10d111213141516171819202122232425(CUstream stream, CUdeviceptr k, CUdeviceptr v, CUdeviceptr w, CUdeviceptr v_new, CUdeviceptr g, CUdeviceptr gk, CUdeviceptr h, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr cu_seqlens, CUdeviceptr chunk_offsets, int32_t T, int32_t NH);
