/*
 * vllm.cpp VENDORED Triton AOT artifact — GENERATED CODE. DO NOT EDIT.
 *
 * Generated by `scripts/triton-aot-compile.py` / `triton.tools.link` from
 * triton_kernels/chunk_scaled_dot_kkt.py (kernel chunk_scaled_dot_kkt_fwd_kernel); the embedded byte
 * array (if any) is the compiled cubin for the arch named by this
 * directory. Generator versions, kernel-source hashes and the exact
 * generation parameters are recorded in the MANIFEST next to this file.
 *
 * Regenerate (MAINTAINER task; needs Python + Triton + ptxas):
 *   scripts/regen-triton-aot.sh
 *
 * The generating kernel source (triton_kernels/chunk_scaled_dot_kkt.py) is ported
 * verbatim from flash-linear-attention via vLLM (MIT; see its header);
 * this generated artifact is distributed under the repository's
 * Apache-2.0 license (see LICENSE and NOTICE).
 */
#include <cuda.h>

CUresult gdn_kkt_h48_48x16x128x64x128x1x1_warps8xstages3(CUstream stream, CUdeviceptr k, CUdeviceptr beta, CUdeviceptr g, CUdeviceptr A, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);
void load_gdn_kkt_h48_48x16x128x64x128x1x1_warps8xstages3();
void unload_gdn_kkt_h48_48x16x128x64x128x1x1_warps8xstages3();

int gdn_kkt_h48_get_num_algos(void);

CUresult gdn_kkt_h48_default(CUstream stream, CUdeviceptr k, CUdeviceptr beta, CUdeviceptr g, CUdeviceptr A, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);
CUresult gdn_kkt_h48(CUstream stream, CUdeviceptr k, CUdeviceptr beta, CUdeviceptr g, CUdeviceptr A, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT, int algo_id);
void load_gdn_kkt_h48();
void unload_gdn_kkt_h48();
