/*
 * vllm.cpp VENDORED Triton AOT artifact — GENERATED CODE. DO NOT EDIT.
 *
 * Generated by `scripts/triton-aot-compile.py` / `triton.tools.link` from
 * triton_kernels/fused_recurrent_packed_decode.py (kernel fused_recurrent_gated_delta_rule_packed_decode_kernel); the embedded byte
 * array (if any) is the compiled cubin for the arch named by this
 * directory. Generator versions, kernel-source hashes and the exact
 * generation parameters are recorded in the MANIFEST next to this file.
 *
 * Regenerate (MAINTAINER task; needs Python + Triton + ptxas):
 *   scripts/regen-triton-aot.sh
 *
 * The generating kernel source (triton_kernels/fused_recurrent_packed_decode.py) is ported
 * verbatim from flash-linear-attention via vLLM (MIT; see its header);
 * this generated artifact is distributed under the repository's
 * Apache-2.0 license (see LICENSE and NOTICE).
 */
#ifndef TT_KERNEL_INCLUDES
#define TT_KERNEL_INCLUDES

#include <cuda.h>
#include <inttypes.h>
#include <stdint.h>
#include <stdio.h>

#endif

void unload_gdn_decode_h48_81e5f031_0d1d2d3d4d5d6d7d8d91011121314151617181920212223(void);
void load_gdn_decode_h48_81e5f031_0d1d2d3d4d5d6d7d8d91011121314151617181920212223(void);
// tt-linker: gdn_decode_h48_81e5f031_0d1d2d3d4d5d6d7d8d91011121314151617181920212223:CUdeviceptr mixed_qkv, CUdeviceptr a, CUdeviceptr b, CUdeviceptr A_log, CUdeviceptr dt_bias, CUdeviceptr o, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr ssm_state_indices, int32_t NBH:10240x96x96x786432x786432x1x16x48x128x128x128x32x20x1_warps1xstages3
CUresult gdn_decode_h48_81e5f031_0d1d2d3d4d5d6d7d8d91011121314151617181920212223(CUstream stream, CUdeviceptr mixed_qkv, CUdeviceptr a, CUdeviceptr b, CUdeviceptr A_log, CUdeviceptr dt_bias, CUdeviceptr o, CUdeviceptr h0, CUdeviceptr ht, CUdeviceptr ssm_state_indices, int32_t NBH);
