/*
 * vllm.cpp VENDORED Triton AOT artifact — GENERATED CODE. DO NOT EDIT.
 *
 * Generated by `scripts/triton-aot-compile.py` / `triton.tools.link` from
 * triton_kernels/chunk_o.py (kernel chunk_fwd_kernel_o); the embedded byte
 * array (if any) is the compiled cubin for the arch named by this
 * directory. Generator versions, kernel-source hashes and the exact
 * generation parameters are recorded in the MANIFEST next to this file.
 *
 * Regenerate (MAINTAINER task; needs Python + Triton + ptxas):
 *   scripts/regen-triton-aot.sh
 *
 * The generating kernel source (triton_kernels/chunk_o.py) is ported
 * verbatim from flash-linear-attention via vLLM (MIT; see its header);
 * this generated artifact is distributed under the repository's
 * Apache-2.0 license (see LICENSE and NOTICE).
 */
#include <cuda.h>
#include <stdint.h>
#include <assert.h>

// launcher for: gdn_chunko_bf16_h32_32x16x128x128x64x64x64x1x1_warps4xstages3
CUresult gdn_chunko_bf16_h32_b8ddc694_0d1d2d3d4d5d6d7d89101112131415161718(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr v, CUdeviceptr h, CUdeviceptr g, CUdeviceptr o, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);

CUresult gdn_chunko_bf16_h32_32x16x128x128x64x64x64x1x1_warps4xstages3(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr v, CUdeviceptr h, CUdeviceptr g, CUdeviceptr o, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT){
  if ((q % 16 == 0) && (k % 16 == 0) && (v % 16 == 0) && (h % 16 == 0) && (g % 16 == 0) && (o % 16 == 0) && (cu_seqlens % 16 == 0) && (chunk_indices % 16 == 0))
    return gdn_chunko_bf16_h32_b8ddc694_0d1d2d3d4d5d6d7d89101112131415161718(stream, q, k, v, h, g, o, cu_seqlens, chunk_indices, T, NT);

  return CUDA_ERROR_INVALID_VALUE;
}

// load for: gdn_chunko_bf16_h32_32x16x128x128x64x64x64x1x1_warps4xstages3
void load_gdn_chunko_bf16_h32_b8ddc694_0d1d2d3d4d5d6d7d89101112131415161718();
void load_gdn_chunko_bf16_h32_32x16x128x128x64x64x64x1x1_warps4xstages3() {
  load_gdn_chunko_bf16_h32_b8ddc694_0d1d2d3d4d5d6d7d89101112131415161718();
}

// unload for: gdn_chunko_bf16_h32_32x16x128x128x64x64x64x1x1_warps4xstages3
void unload_gdn_chunko_bf16_h32_b8ddc694_0d1d2d3d4d5d6d7d89101112131415161718();
void unload_gdn_chunko_bf16_h32_32x16x128x128x64x64x64x1x1_warps4xstages3() {
  unload_gdn_chunko_bf16_h32_b8ddc694_0d1d2d3d4d5d6d7d89101112131415161718();
}

typedef CUresult (*kernel_func_t)(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr v, CUdeviceptr h, CUdeviceptr g, CUdeviceptr o, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT);
kernel_func_t gdn_chunko_bf16_h32_kernels[] = {
  gdn_chunko_bf16_h32_32x16x128x128x64x64x64x1x1_warps4xstages3,
};

int gdn_chunko_bf16_h32_get_num_algos(void){
  return (int)(sizeof(gdn_chunko_bf16_h32_kernels) / sizeof(gdn_chunko_bf16_h32_kernels[0]));
}

CUresult gdn_chunko_bf16_h32(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr v, CUdeviceptr h, CUdeviceptr g, CUdeviceptr o, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT, int algo_id){
  assert (algo_id < (int)sizeof(gdn_chunko_bf16_h32_kernels));
  return gdn_chunko_bf16_h32_kernels[algo_id](stream, q, k, v, h, g, o, cu_seqlens, chunk_indices, T, NT);
}

void load_gdn_chunko_bf16_h32(void){
  load_gdn_chunko_bf16_h32_32x16x128x128x64x64x64x1x1_warps4xstages3();
}

void unload_gdn_chunko_bf16_h32(void){
  unload_gdn_chunko_bf16_h32_32x16x128x128x64x64x64x1x1_warps4xstages3();
}


CUresult gdn_chunko_bf16_h32_default(CUstream stream, CUdeviceptr q, CUdeviceptr k, CUdeviceptr v, CUdeviceptr h, CUdeviceptr g, CUdeviceptr o, CUdeviceptr cu_seqlens, CUdeviceptr chunk_indices, int32_t T, int32_t NT){
  return gdn_chunko_bf16_h32(stream, q, k, v, h, g, o, cu_seqlens, chunk_indices, T, NT, 0);
}
