#!/usr/bin/env python3
"""Regenerate `qwen3_5_stacked_shapes.inc` from the PUBLISHED Qwen repos.

Issue #740, `.agents/specs/moe-bf16-stacked-experts.md`. Same shape as
`scripts/gen-minimax-h3-safetensors-manifest.py`: names, dtypes and shapes only,
never a weight byte.

WHY THE SHAPES ARE NOT IN THE INDEX. `model.safetensors.index.json` carries only
`weight_map` (name -> shard) and `metadata.total_size`. The per-tensor shape and
dtype live in each shard's own safetensors header, which is a length-prefixed
JSON blob at offset 0 of the file. This script reads exactly that, via HTTP range
requests, so capturing 4.8 TB of checkpoint costs a few hundred KB of transfer.

WHY THAT CAPTURE IS TRUSTWORTHY RATHER THAN JUST ASSERTED. Every tensor's
`numel * sizeof(dtype)` is summed and compared against the `metadata.total_size`
that the published index declares independently. The two agree exactly for both
repos, and the generated `.inc` carries that total so the C++ side re-checks it
at test time. A mis-transcribed shape cannot survive that sum.

Usage:  python3 tests/vllm/models/fixtures/gen_qwen3_5_stacked_shapes.py
"""

import concurrent.futures
import json
import math
import pathlib
import struct
import sys
import urllib.request

# (C++ identifier infix, HF repo id, PINNED commit revision).
#
# THE REVISION IS PART OF THE CAPTURE, not decoration. `main` is a moving target
# -- `unsloth/...-27B` was silently re-quantized from NVFP4 to FP8 under its own
# name -- so a manifest captured from `main` records shapes nobody can re-derive.
# Every fetch below goes through `/resolve/<rev>/` and `/raw/<rev>/`, and the
# revisions are emitted into the generated header so the C++ side names them too.
REPOS = [
    ("Qwen38_2_4T", "Qwen/Qwen3.8-2.4T-A95B",
     "207bd685a7e3696cfaff12ded7c6a7ea0f88c996"),
    ("Qwen36_35B", "Qwen/Qwen3.6-35B-A3B",
     "995ad96eacd98c81ed38be0c5b274b04031597b0"),
]

# Byte width of every safetensors dtype these repos use. A dtype outside this
# table is a hard error rather than a guess -- the total-size cross-check below
# is only meaningful if every width is known.
DTYPE_BYTES = {"BF16": 2, "F32": 4, "F16": 2, "F8_E4M3": 1, "U8": 1, "I8": 1}

MAX_RANK = 5  # model.visual.patch_embed.proj.weight is rank 5 on the 35B.


def _get(url, start, end):
    req = urllib.request.Request(url, headers={"Range": f"bytes={start}-{end}"})
    return urllib.request.urlopen(req, timeout=90).read()


def shard_header(base, shard):
    """names -> {dtype, shape} for one shard, from its own safetensors header."""
    url = base + shard
    last = None
    for _ in range(4):
        try:
            n = struct.unpack("<Q", _get(url, 0, 7))[0]
            head = json.loads(_get(url, 8, 8 + n - 1))
            head.pop("__metadata__", None)
            return {k: {"dtype": v["dtype"], "shape": v["shape"]} for k, v in head.items()}
        except Exception as exc:  # noqa: BLE001 - retried, then re-raised
            last = exc
    raise RuntimeError(f"could not read header of {shard}: {last}")


def capture(repo, revision):
    base = f"https://huggingface.co/{repo}/resolve/{revision}/"
    index = json.loads(
        urllib.request.urlopen(base.replace("/resolve/", "/raw/") + "model.safetensors.index.json", timeout=90).read()
    )
    shards = sorted(set(index["weight_map"].values()))
    print(f"{repo}: {len(index['weight_map'])} tensors over {len(shards)} shards", file=sys.stderr)
    tensors = {}
    with concurrent.futures.ThreadPoolExecutor(max_workers=8) as pool:
        for head in pool.map(lambda s: shard_header(base, s), shards):
            tensors.update(head)

    if set(tensors) != set(index["weight_map"]):
        raise RuntimeError(f"{repo}: shard headers and index disagree on the tensor set")
    total = 0
    for name, t in tensors.items():
        if t["dtype"] not in DTYPE_BYTES:
            raise RuntimeError(f"{repo}: unknown dtype {t['dtype']} on {name}")
        if len(t["shape"]) > MAX_RANK:
            raise RuntimeError(f"{repo}: rank {len(t['shape'])} exceeds MAX_RANK on {name}")
        total += math.prod(t["shape"]) * DTYPE_BYTES[t["dtype"]]
    declared = int(index["metadata"]["total_size"])
    if total != declared:
        raise RuntimeError(f"{repo}: summed {total} bytes but the index declares {declared}")
    print(f"{repo}: total_size {declared} confirmed against the summed shapes", file=sys.stderr)
    return tensors, declared, len(shards)


def main():
    out = [
        "// GENERATED by tests/vllm/models/fixtures/gen_qwen3_5_stacked_shapes.py",
        "// -- DO NOT EDIT BY HAND.",
        "//",
        "// Tensor manifests of the two PUBLISHED Qwen3.5-family MoE repos (issue #740,",
        "// .agents/specs/moe-bf16-stacked-experts.md): names, dtypes and shapes only, no",
        "// weight bytes. Captured from each shard's own safetensors header over HTTP",
        "// range requests; `model.safetensors.index.json` itself carries NO shapes, only",
        "// a name -> shard map and a `metadata.total_size`.",
        "//",
        "// Each repo's `TotalSize` below is that published `metadata.total_size`, and the",
        "// generator refuses to emit unless the summed `numel * sizeof(dtype)` over every",
        "// tensor equals it exactly. The C++ side re-checks the same sum, so this file",
        "// cannot drift from the published index without a test going red.",
        "//",
        "// Every fetch is PINNED to the commit revision named beside each repo below. A",
        "// capture from `main` records shapes nobody can re-derive once the repo moves,",
        "// and Qwen repos do move under their own names.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace vllm_test {",
        "",
        "// One published tensor. `shape` is 0-padded to rank 5 (the 35B's vision patch",
        "// embed is rank 5); `rank` is how many entries are meaningful.",
        "struct StackedRepoTensor {",
        "  const char* name;",
        "  const char* dtype;",
        f"  int64_t shape[{MAX_RANK}];",
        "  int32_t rank;",
        "};",
        "",
    ]
    for ident, repo, revision in REPOS:
        tensors, total, shards = capture(repo, revision)
        out += [
            f"// {repo} @ {revision}",
            f"// -- {len(tensors)} tensors over {shards} shards.",
            f'inline constexpr const char* k{ident}Repo = "{repo}";',
            f'inline constexpr const char* k{ident}Revision = "{revision}";',
            f"inline constexpr int64_t k{ident}TensorCount = {len(tensors)};",
            f"inline constexpr int64_t k{ident}TotalSize = {total};",
            f"inline constexpr StackedRepoTensor k{ident}Tensors[] = {{",
        ]
        for name in sorted(tensors):
            t = tensors[name]
            dims = list(t["shape"]) + [0] * (MAX_RANK - len(t["shape"]))
            out.append(
                f'    {{"{name}", "{t["dtype"]}", '
                f'{{{", ".join(str(d) for d in dims)}}}, {len(t["shape"])}}},'
            )
        out += ["};", ""]
    out += ["}  // namespace vllm_test", ""]

    dest = pathlib.Path(__file__).with_name("qwen3_5_stacked_shapes.inc")
    dest.write_text("\n".join(out))
    print(f"wrote {dest} ({dest.stat().st_size} bytes)", file=sys.stderr)


if __name__ == "__main__":
    main()
