// QUANT-QWEN38-27B-GGUF-ARM (issue #821, W2) — the tensor accounting this
// family has never had.
//
// Before this file NO Qwen3.5-family checkpoint-index accounting test existed
// anywhere under `tests/`: `test_gguf_qwen36_loader.cpp` builds synthetic files
// and asserts what the loader does with the tensors it ASKS FOR, and a fixture
// cannot disagree with its own author about which tensors a real checkpoint
// ships. So the direction that had no gate is the one that is silent — a tensor
// the file carries and no loader reads is dropped without a word.
//
// That direction is not hypothetical on this artifact. `Qwen3.8-27B-Q4_K_M.gguf`
// states `qwen35.block_count = 65` and `qwen35.nextn_predict_layers = 1`: 64
// decoder blocks plus an MTP drafter at `blk.64`. A reader that spends the whole
// 65 on the trunk builds a 65-layer model out of a 64-layer checkpoint plus a
// drafter, loads, decodes fluently, and is the wrong graph.
//
// The manifest (`qwen38_27b_q4km_gguf_manifest.inc`, generated by
// `scripts/gen-qwen38-27b-gguf-manifest.py`) freezes that file's 866 tensor
// names, ggml dims and type ids plus its scalar metadata — no weight bytes — so
// this runs in CI with no asset. The two live cases at the bottom re-derive the
// same numbers from the shipped bytes and SKIP LOUDLY when the env vars are
// unset, exactly as `test_clip_mmproj_gguf`'s live case does.
#include <doctest/doctest.h>

#include <cstdint>
#include <cstdlib>
#include <set>
#include <string>
#include <vector>

#include "vllm/gguf_builder.h"
#include "vllm/model_executor/model_loader/gguf_reader.h"
#include "vllm/model_executor/models/clip_mmproj_gguf.h"
#include "vllm/model_executor/models/qwen3_5_gguf_weights.h"
#include "vllm/model_executor/models/qwen3_5_mtp.h"
#include "vllm/transformers_utils/hf_config.h"

#include "qwen38_27b_mmproj_gguf_manifest.inc"
#include "qwen38_27b_q4km_gguf_manifest.inc"

namespace {

using gguf_test::GgufModelBuilder;
using gguf_test::TempFile;

std::vector<std::string> Q4KMNames() {
  std::vector<std::string> out;
  for (const auto& t : vllm_test::kQwen38Q4KMTensors) out.emplace_back(t.name);
  return out;
}

std::vector<std::string> MmprojNames() {
  std::vector<std::string> out;
  for (const auto& t : vllm_test::kQwen38MmprojTensors) out.emplace_back(t.name);
  return out;
}

// A KV-ONLY GGUF carrying the manifest's `qwen35.*` scalars, so
// `HfConfigFromGguf` — the PRODUCTION config builder — is what derives the
// decoder depth here, rather than this test restating its arithmetic.
//
// ONE key is added that the file does not ship: `qwen35.vocab_size`. The real
// artifact states its vocabulary only through `token_embd.weight`'s shape, and
// that tensor is 1.27e9 Q4_K elements, which is not a thing a hermetic fixture
// can carry. The value comes from the MANIFEST's own record of that shape
// (`kQwen38Q4KMVocabSize`, the generator reading the file's dims), and the case
// below asserts the two agree, so the injection is bound to the bytes rather
// than hand-written. The env-gated live case exercises the shape fallback
// itself, on the real file, with nothing injected.
std::string BuildQ4KMMetadataOnlyGguf() {
  GgufModelBuilder b;
  for (const auto& kv : vllm_test::kQwen38Q4KMStringKv) {
    const std::string key(kv.key);
    if (key == "general.architecture") b.AddKv(gguf_test::StrKv(key, kv.value));
  }
  for (const auto& kv : vllm_test::kQwen38Q4KMIntKv) {
    const std::string key(kv.key);
    if (key.rfind("qwen35.", 0) != 0) continue;
    if (kv.value <= 0xffffffffLL) {
      b.AddKv(gguf_test::U32Kv(key, static_cast<uint32_t>(kv.value)));
    } else {
      b.AddKv(gguf_test::U64Kv(key, static_cast<uint64_t>(kv.value)));
    }
  }
  for (const auto& kv : vllm_test::kQwen38Q4KMFloatKv) {
    const std::string key(kv.key);
    if (key.rfind("qwen35.", 0) != 0) continue;
    b.AddKv(gguf_test::F32Kv(key, static_cast<float>(kv.value)));
  }
  b.AddKv(gguf_test::U32Kv(
      "qwen35.vocab_size",
      static_cast<uint32_t>(vllm_test::kQwen38Q4KMVocabSize)));
  return b.Build();
}

int64_t ManifestInt(const char* key) {
  for (const auto& kv : vllm_test::kQwen38Q4KMIntKv) {
    if (std::string(kv.key) == key) return kv.value;
  }
  return -1;
}

int64_t MmprojInt(const char* key) {
  for (const auto& kv : vllm_test::kQwen38MmprojIntKv) {
    if (std::string(kv.key) == key) return kv.value;
  }
  return -1;
}

std::string Join(const std::vector<std::string>& names) {
  std::string s;
  for (size_t i = 0; i < names.size() && i < 12; ++i) {
    s += (i == 0 ? "" : ", ") + names[i];
  }
  if (names.size() > 12) s += ", ...";
  return s;
}

}  // namespace

TEST_CASE("q4km manifest: the frozen header is this artifact's own") {
  CHECK(vllm_test::kQwen38Q4KMVersion == 3);
  CHECK(std::string(vllm_test::kQwen38Q4KMArchitecture) == "qwen35");
  CHECK(vllm_test::kQwen38Q4KMTensorCount == 866);
  CHECK(vllm_test::kQwen38Q4KMKvCount == 51);
  CHECK(static_cast<int64_t>(std::size(vllm_test::kQwen38Q4KMTensors)) ==
        vllm_test::kQwen38Q4KMTensorCount);
  // The three facts #821 recorded and the two it did not. `block_count` is 65
  // while the BF16 GGUF of the SAME model carries 64, and the difference is the
  // drafter; `padding_token_id` is 248055 against that file's 248044, which is
  // why the tokenizer gate belongs to the ARM rather than to the model.
  CHECK(ManifestInt("qwen35.block_count") == 65);
  CHECK(ManifestInt("qwen35.nextn_predict_layers") == 1);
  CHECK(ManifestInt("qwen35.full_attention_interval") == 4);
  CHECK(ManifestInt("tokenizer.ggml.padding_token_id") == 248055);
  CHECK(ManifestInt("tokenizer.ggml.bos_token_id") == 248044);
  CHECK(ManifestInt("tokenizer.ggml.eos_token_id") == 248046);

  // The encodings, so a manifest regenerated from some OTHER quant does not
  // pass as this one: F32 456, Q8_0 1, Q4_K 294, Q5_K 48, Q6_K 67.
  int f32 = 0, q8_0 = 0, q4_k = 0, q5_k = 0, q6_k = 0, other = 0;
  for (const auto& t : vllm_test::kQwen38Q4KMTensors) {
    switch (t.ggml_type) {
      case 0: ++f32; break;
      case 8: ++q8_0; break;
      case 12: ++q4_k; break;
      case 13: ++q5_k; break;
      case 14: ++q6_k; break;
      default: ++other; break;
    }
  }
  CHECK(f32 == 456);
  CHECK(q8_0 == 1);
  CHECK(q4_k == 294);
  CHECK(q5_k == 48);
  CHECK(q6_k == 67);
  CHECK(other == 0);
  CHECK(f32 + q8_0 + q4_k + q5_k + q6_k == vllm_test::kQwen38Q4KMTensorCount);
}

TEST_CASE("q4km manifest: block_count MINUS nextn_predict_layers is the depth") {
  // The vocabulary the fixture injects is the one the MANIFEST read off
  // `token_embd.weight`, not a number written here.
  for (const auto& t : vllm_test::kQwen38Q4KMTensors) {
    if (std::string(t.name) != "token_embd.weight") continue;
    REQUIRE(t.n_dims == 2);
    // GGUF ne order is the reverse of torch's, so the vocabulary is the OUTER
    // (last) ggml dim and the hidden size is the inner one.
    CHECK(t.dims[1] == vllm_test::kQwen38Q4KMVocabSize);
    CHECK(t.dims[0] == ManifestInt("qwen35.embedding_length"));
  }

  TempFile f(BuildQ4KMMetadataOnlyGguf());
  const vllm::GgufFile g = vllm::GgufFile::Open(f.path());
  const vllm::HfConfig c = vllm::HfConfigFromGguf(g);

  // THE CORRECTION. 65 blocks minus a 1-block MTP head is a 64-layer trunk.
  CHECK(c.num_hidden_layers == 64);
  CHECK(vllm::NumMtpLayers(c) == 1);
  CHECK(c.num_hidden_layers + vllm::NumMtpLayers(c) ==
        ManifestInt("qwen35.block_count"));
  CHECK(c.vocab_size == vllm_test::kQwen38Q4KMVocabSize);
  CHECK(c.num_experts == 0);  // dense: the MoE arm must not be selected

  // And the trunk's own composition, because a 64 that is 64 of the wrong kind
  // is the same defect one level down: `full_attention_interval = 4` makes
  // every 4th layer full attention, 16 of them, and the other 48 GDN.
  REQUIRE(static_cast<int64_t>(c.layer_types.size()) == 64);
  int full = 0, linear = 0;
  for (size_t i = 0; i < c.layer_types.size(); ++i) {
    if (c.layer_types[i] == "full_attention") {
      ++full;
      CHECK((i + 1) % 4 == 0);
    } else {
      ++linear;
    }
  }
  CHECK(full == 16);
  CHECK(linear == 48);

  // The manifest agrees, from the NAMES rather than from the metadata: a GDN
  // block ships `attn_qkv` and no `attn_q`, a full-attention block the reverse.
  const std::set<std::string> names = [] {
    const std::vector<std::string> v = Q4KMNames();
    return std::set<std::string>(v.begin(), v.end());
  }();
  for (int il = 0; il < 64; ++il) {
    const std::string blk = "blk." + std::to_string(il) + ".";
    const bool file_says_full = names.count(blk + "attn_q.weight") != 0;
    CHECK(file_says_full == (c.layer_types[static_cast<size_t>(il)] ==
                             "full_attention"));
  }
  // blk.64 is the DRAFTER: a full-attention block plus the four `nextn.*`
  // tensors `LoadQwen3_5MTPFromGguf` reads, and it is NOT in layer_types.
  CHECK(names.count("blk.64.nextn.eh_proj.weight") == 1);
  CHECK(names.count("blk.64.nextn.enorm.weight") == 1);
  CHECK(names.count("blk.64.nextn.hnorm.weight") == 1);
  CHECK(names.count("blk.64.nextn.shared_head_norm.weight") == 1);
  CHECK(names.count("blk.64.attn_q.weight") == 1);
  CHECK(names.count("blk.65.attn_norm.weight") == 0);
}

TEST_CASE("q4km manifest: enumerated == present, ZERO unaccounted BOTH ways") {
  TempFile f(BuildQ4KMMetadataOnlyGguf());
  const vllm::GgufFile g = vllm::GgufFile::Open(f.path());
  const vllm::HfConfig c = vllm::HfConfigFromGguf(g);

  const std::vector<std::string> present = Q4KMNames();
  const vllm::Qwen3_5GgufAccounting acct =
      vllm::Qwen3_5GgufAccountTensors(c, present);

  CAPTURE(Join(acct.missing));
  CAPTURE(Join(acct.unaccounted));
  CHECK(acct.missing.empty());
  CHECK(acct.unaccounted.empty());
  CHECK(acct.present == vllm_test::kQwen38Q4KMTensorCount);
  CHECK(acct.enumerated == vllm_test::kQwen38Q4KMTensorCount);

  // The arithmetic behind that total, stated so a coincidence cannot pass:
  // 48 GDN blocks x 14 + 16 full-attention blocks x 11 + one 15-tensor MTP
  // block + token_embd/output/output_norm.
  CHECK(48 * 14 + 16 * 11 + 15 + 3 == vllm_test::kQwen38Q4KMTensorCount);
}

TEST_CASE("mmproj manifest: enumerated == present, ZERO unaccounted BOTH ways") {
  CHECK(vllm_test::kQwen38MmprojVersion == 3);
  CHECK(std::string(vllm_test::kQwen38MmprojArchitecture) == "clip");
  CHECK(vllm_test::kQwen38MmprojTensorCount == 334);
  CHECK(vllm_test::kQwen38MmprojKvCount == 35);
  CHECK(static_cast<int64_t>(std::size(vllm_test::kQwen38MmprojTensors)) ==
        vllm_test::kQwen38MmprojTensorCount);

  const std::vector<std::string> present = MmprojNames();
  const std::set<std::string> have(present.begin(), present.end());

  // The geometry the enumeration needs, from the projector's OWN metadata, and
  // the DeepStack list from its own tensor names: this artifact taps nothing,
  // which is the file agreeing with `deepstack_visual_indexes: []` on the
  // safetensors side. Asserting the emptiness from the NAMES is what makes the
  // config below justified by the bytes rather than assumed.
  for (const std::string& n : present) {
    CHECK(n.rfind("v.deepstack.", 0) != 0);
  }
  vllm::multimodal::Qwen3VLVisionConfig cfg;
  cfg.depth = MmprojInt("clip.vision.block_count");
  cfg.deepstack_visual_indexes.clear();
  REQUIRE(cfg.depth == 27);

  const std::vector<std::string> want =
      vllm::Qwen3VLClipMmprojExpectedTensors(cfg);
  const std::set<std::string> wanted(want.begin(), want.end());

  std::vector<std::string> missing;
  for (const std::string& n : wanted) {
    if (have.count(n) == 0) missing.push_back(n);
  }
  std::vector<std::string> unaccounted;
  for (const std::string& n : have) {
    if (wanted.count(n) == 0) unaccounted.push_back(n);
  }
  CAPTURE(Join(missing));
  CAPTURE(Join(unaccounted));
  CHECK(missing.empty());
  CHECK(unaccounted.empty());
  CHECK(static_cast<int64_t>(wanted.size()) ==
        vllm_test::kQwen38MmprojTensorCount);
  // 27 blocks x 12 + the two patch-embedding halves, the patch bias, the
  // position table, `v.post_ln` weight+bias and `mm.0`/`mm.2` weight+bias.
  CHECK(27 * 12 + 10 == vllm_test::kQwen38MmprojTensorCount);
}

// ── The live confirmations ──────────────────────────────────────────────────
//
// The same accounting over the SHIPPED bytes. A fixture cannot catch a name its
// own author got wrong, and a manifest cannot catch a manifest regenerated from
// the wrong file; the artifact can. Both skip loudly when unset, so CI reads no
// file on a share.
//
//   VLLM_CPP_QWEN38_27B_GGUF=/path/to/Qwen3.8-27B-Q4_K_M.gguf
//   VLLM_CPP_QWEN38_27B_MMPROJ=/path/to/mmproj-BF16.gguf
//
// Both are pinned by bytes and sha256 in `docs/USAGE.md` §"The exact files this
// was gated against" (`unsloth/Qwen3.8-27B-GGUF` @
// `fe1e2a23d973adb629709749dc4f6756df66ef10`).

TEST_CASE("q4km LIVE: the shipped file accounts to zero, and the manifest is it") {
  const char* env = std::getenv("VLLM_CPP_QWEN38_27B_GGUF");
  if (env == nullptr) {
    MESSAGE(
        "SKIPPED: set VLLM_CPP_QWEN38_27B_GGUF to the real "
        "Qwen3.8-27B-Q4_K_M.gguf to account the shipped 866 tensors "
        "(docs/USAGE.md pins the file)");
    return;
  }
  const vllm::GgufFile g = vllm::GgufFile::Open(env);
  // The config comes off the REAL metadata here, with nothing injected, so the
  // `token_embd.weight` vocabulary fallback the hermetic fixture cannot carry
  // is exercised on the bytes that need it.
  const vllm::HfConfig c = vllm::HfConfigFromGguf(g);
  CHECK(c.num_hidden_layers == 64);
  CHECK(vllm::NumMtpLayers(c) == 1);
  CHECK(c.vocab_size == vllm_test::kQwen38Q4KMVocabSize);

  std::vector<std::string> present;
  for (const vllm::GgufTensorInfo& t : g.Tensors()) present.push_back(t.name);
  CHECK(static_cast<int64_t>(present.size()) ==
        vllm_test::kQwen38Q4KMTensorCount);

  const vllm::Qwen3_5GgufAccounting acct =
      vllm::Qwen3_5GgufAccountTensors(c, present);
  CAPTURE(Join(acct.missing));
  CAPTURE(Join(acct.unaccounted));
  CHECK(acct.missing.empty());
  CHECK(acct.unaccounted.empty());

  // And the committed manifest IS this file: same names, same ggml dims, same
  // type ids. Without this the manifest could be some other quantization's and
  // every hermetic case above would still pass.
  const std::set<std::string> frozen = [] {
    const std::vector<std::string> v = Q4KMNames();
    return std::set<std::string>(v.begin(), v.end());
  }();
  const std::set<std::string> shipped(present.begin(), present.end());
  CHECK(frozen == shipped);
  for (const auto& t : vllm_test::kQwen38Q4KMTensors) {
    const vllm::GgufTensorInfo& info = g.Get(t.name);
    CHECK(info.ggml_type == t.ggml_type);
    REQUIRE(static_cast<int32_t>(info.shape.size()) == t.n_dims);
    // GgufTensorInfo::shape is torch order; the manifest froze the ggml ne
    // order, so they are reverses of each other.
    for (int32_t d = 0; d < t.n_dims; ++d) {
      CHECK(info.shape[static_cast<size_t>(t.n_dims - 1 - d)] == t.dims[d]);
    }
  }
}

TEST_CASE("mmproj LIVE: the shipped projector accounts to zero") {
  const char* env = std::getenv("VLLM_CPP_QWEN38_27B_MMPROJ");
  if (env == nullptr) {
    MESSAGE(
        "SKIPPED: set VLLM_CPP_QWEN38_27B_MMPROJ to the real mmproj-BF16.gguf "
        "to account the shipped 334 tensors (docs/USAGE.md pins the file)");
    return;
  }
  const vllm::GgufFile g = vllm::GgufFile::Open(env);
  const vllm::multimodal::Qwen3VLVisionConfig cfg =
      vllm::ClipMmprojVisionConfig(g);
  const std::vector<std::string> want =
      vllm::Qwen3VLClipMmprojExpectedTensors(cfg);
  const std::set<std::string> wanted(want.begin(), want.end());

  std::set<std::string> shipped;
  for (const vllm::GgufTensorInfo& t : g.Tensors()) shipped.insert(t.name);
  CHECK(static_cast<int64_t>(shipped.size()) ==
        vllm_test::kQwen38MmprojTensorCount);
  CHECK(wanted == shipped);

  const std::set<std::string> frozen = [] {
    const std::vector<std::string> v = MmprojNames();
    return std::set<std::string>(v.begin(), v.end());
  }();
  CHECK(frozen == shipped);
  for (const auto& t : vllm_test::kQwen38MmprojTensors) {
    const vllm::GgufTensorInfo& info = g.Get(t.name);
    CHECK(info.ggml_type == t.ggml_type);
    REQUIRE(static_cast<int32_t>(info.shape.size()) == t.n_dims);
    for (int32_t d = 0; d < t.n_dims; ++d) {
      CHECK(info.shape[static_cast<size_t>(t.n_dims - 1 - d)] == t.dims[d]);
    }
  }
}
