// GLM-5.3-Flash W5b-1 gate — `Glm5NextTextAttention` and its CROSS-LAYER top-k
// sharing, against the RUN output of `transformers` v5.16.1.
//
// Row MODEL-MM-glm5-next-glm5-next-for-conditional-generation, issue #2241,
// `.agents/specs/glm5-next-flash.md` section W5b.
//
// ─── WHAT MAKES THIS FIXTURE ABLE TO FAIL ───────────────────────────────────
//
// Four properties, each present because dropping it makes the file a tautology
// a wrong port passes:
//
//  1. `kv_lora_rank` 8, `qk_nope_head_dim` 4 and `v_head_dim` 6 are ALL
//     DIFFERENT, so reading either `kv_b_proj` half at the other's orientation
//     is a shape error. And because a shape error is the EASY failure, a SQUARE
//     case follows at `kv_lora == qk_nope == v_head == 6` where the untransposed
//     reading of `k_b` is perfectly shape-valid and merely WRONG. That case
//     carries the wrong value beside the right one.
//  2. `seq_len` 25 is STRICTLY GREATER than `index_topk` 8, so the DSA selection
//     is not the identity and the top-k mask actually masks something.
//  3. A `shared` layer is driven by the previous layer's selection, and the
//     fixture ALSO carries what a RECOMPUTING port would produce from a decoy
//     indexer. The gate asserts ours is the first and not the second, and prints
//     the separation. This is the highest-value assertion in the wave: a layer
//     that recomputes runs, selects a plausible key set, and emits plausible
//     tokens, and nothing about the output's shape, finiteness or scale says
//     otherwise.
//  4. Row 1 is LEFT-PADDED by three tokens, so its padded query rows reach a
//     state where EVERY key is masked. Upstream fills that with
//     `torch.finfo(dtype).min` and NOT `-inf` (`:1253`), so the softmax is
//     UNIFORM and the output FINITE; a port that writes `-inf` produces NaN and
//     poisons the residual stream for the rest of the stack.
//
// ─── EVERY GOLDEN IN THE `.inc` IS READ BY AN ASSERTION IN THIS FILE ─────────
//
// That is a requirement on this row and not a courtesy. W3 captured a
// `kIndexScores` golden that no case consumed, and two real scale defects then
// passed 1602 assertions (spec `## Owed`). The last case below re-states the
// obligation for the next reader.
//
// ─── THE ORACLE ─────────────────────────────────────────────────────────────
// `glm5_next_attn_goldens.inc` is GENERATED by
// `fixtures/gen_glm5_next_attn_goldens.py`, which RUNS the unmodified
// `Glm5NextTextAttention` at transformers v5.16.1 — the lane revision W0 (#2096)
// recorded — through its own `forward`, `expand_kv` and
// `build_attention_mask_from_topk`. The generator ASSERTS the sha256 of the
// installed `modeling_glm5_next.py` rather than trusting the version string.
// Nothing in the `.inc` is transcribed from our C++.
#include <doctest/doctest.h>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <fstream>
#include <string>
#include <vector>

#include "glm5_next_attn_goldens.inc"
#include "nlohmann/json.hpp"
#include "vllm/model_executor/models/glm5_next.h"
#include "vllm/model_executor/models/glm5_next_attn.h"
#include "vllm/model_executor/models/glm5_next_dsa.h"
#include "vllm/transformers_utils/hf_config.h"

namespace g = glm5_next_attn_goldens;
using vllm::Glm5NextIndexerKind;
using vllm::Glm5NextParams;
using vllm::glm5_next::Attention;
using vllm::glm5_next::AttentionResult;
using vllm::glm5_next::BuildAttentionMaskFromTopk;
using vllm::glm5_next::CompressKv;
using vllm::glm5_next::ExpandedKv;
using vllm::glm5_next::ExpandKv;
using vllm::glm5_next::IndexerDims;
using vllm::glm5_next::IndexerRole;
using vllm::glm5_next::IndexerRoleFor;
using vllm::glm5_next::IndexerWeights;
using vllm::glm5_next::MlaDims;
using vllm::glm5_next::MlaDimsFrom;
using vllm::glm5_next::MlaWeights;
using vllm::glm5_next::QResid;

namespace {

template <typename T, size_t N>
std::vector<float> Vec(const T (&a)[N]) {
  return std::vector<float>(a, a + N);
}

template <size_t N>
std::vector<int32_t> IVec(const int32_t (&a)[N]) {
  return std::vector<int32_t>(a, a + N);
}

template <size_t N>
std::vector<uint8_t> BVec(const int32_t (&a)[N]) {
  std::vector<uint8_t> v(N);
  for (size_t i = 0; i < N; ++i) v[i] = a[i] != 0 ? 1U : 0U;
  return v;
}

// The fixture's own MLA geometry.
MlaDims Dims() {
  MlaDims d;
  d.hidden_size = g::kHidden;
  d.num_heads = g::kNumHeads;
  d.q_lora_rank = g::kQLora;
  d.kv_lora_rank = g::kKvLora;
  d.qk_nope_head_dim = g::kQkNope;
  d.qk_rope_head_dim = g::kQkRope;
  d.v_head_dim = g::kVHead;
  // `Glm5NextTextConfig`'s own default, which the generator did not override.
  d.rms_norm_eps = 1e-5;
  return d;
}

IndexerDims IdxDims() {
  IndexerDims d;
  d.hidden_size = g::kHidden;
  d.q_lora_rank = g::kQLora;
  d.n_heads = g::kIdxNHeads;
  d.head_dim = g::kIdxHeadDim;
  d.index_topk = g::kIndexTopk;
  d.index_kpool = g::kIndexKpool;
  d.always_select_tail = true;
  return d;
}

MlaWeights L0Weights() {
  MlaWeights w;
  w.q_a_proj = Vec(g::kL0QAProj);
  w.q_a_layernorm = Vec(g::kL0QANorm);
  w.q_b_proj = Vec(g::kL0QBProj);
  w.kv_a_proj_with_mqa = Vec(g::kL0KvAProj);
  w.kv_a_layernorm = Vec(g::kL0KvANorm);
  w.k_b_proj = Vec(g::kL0KB);
  w.v_b_proj = Vec(g::kL0VB);
  w.o_proj = Vec(g::kL0OProj);
  return w;
}

MlaWeights L1Weights() {
  MlaWeights w;
  w.q_a_proj = Vec(g::kL1QAProj);
  w.q_a_layernorm = Vec(g::kL1QANorm);
  w.q_b_proj = Vec(g::kL1QBProj);
  w.kv_a_proj_with_mqa = Vec(g::kL1KvAProj);
  w.kv_a_layernorm = Vec(g::kL1KvANorm);
  w.k_b_proj = Vec(g::kL1KB);
  w.v_b_proj = Vec(g::kL1VB);
  w.o_proj = Vec(g::kL1OProj);
  return w;
}

// The storage the `const float*` view points into has to outlive the view, so
// every indexer case builds both together.
struct IndexerStore {
  std::vector<float> wq_b, wk, k_norm_w, k_norm_b, weights_proj, ape, gate;
  IndexerWeights View() const {
    IndexerWeights w;
    w.wq_b = wq_b.data();
    w.wk = wk.data();
    w.k_norm_weight = k_norm_w.data();
    w.k_norm_bias = k_norm_b.data();
    w.weights_proj = weights_proj.data();
    w.kpool_ape = ape.data();
    w.kpool_gate = gate.data();
    return w;
  }
};

IndexerStore L0Indexer() {
  IndexerStore s;
  s.wq_b = Vec(g::kL0IdxWqB);
  s.wk = Vec(g::kL0IdxWk);
  s.k_norm_w = Vec(g::kL0IdxKNormWeight);
  s.k_norm_b = Vec(g::kL0IdxKNormBias);
  s.weights_proj = Vec(g::kL0IdxWeightsProj);
  s.ape = Vec(g::kL0IdxKpoolApe);
  s.gate = Vec(g::kL0IdxKpoolGate);
  return s;
}

// Layer 2's indexer. Layer 1 is `shared` and has none of its own; this is what
// a port that RECOMPUTES would have to reach for.
IndexerStore DecoyIndexer() {
  IndexerStore s;
  s.wq_b = Vec(g::kL1DecoyIdxWqB);
  s.wk = Vec(g::kL1DecoyIdxWk);
  s.k_norm_w = Vec(g::kL1DecoyIdxKNormWeight);
  s.k_norm_b = Vec(g::kL1DecoyIdxKNormBias);
  s.weights_proj = Vec(g::kL1DecoyIdxWeightsProj);
  s.ape = Vec(g::kL1DecoyIdxKpoolApe);
  s.gate = Vec(g::kL1DecoyIdxKpoolGate);
  return s;
}

// The fixture's own 4-layer schedule, as a resolved `Glm5NextParams`.
Glm5NextParams FixtureParams() {
  Glm5NextParams p;
  p.hidden_size = g::kHidden;
  p.num_attention_heads = g::kNumHeads;
  p.num_hidden_layers = g::kNumLayers;
  p.rms_norm_eps = 1e-5;
  p.mla.q_lora_rank = g::kQLora;
  p.mla.kv_lora_rank = g::kKvLora;
  p.mla.qk_nope_head_dim = g::kQkNope;
  p.mla.qk_rope_head_dim = g::kQkRope;
  p.mla.v_head_dim = g::kVHead;
  for (int64_t i = 0; i < g::kNumLayers; ++i) {
    p.indexer_types.push_back(g::kIndexerShared[i] ? Glm5NextIndexerKind::kShared
                                                   : Glm5NextIndexerKind::kFull);
  }
  return p;
}

vllm::HfConfig PublishedConfig() {
  const std::string path = std::string(GLM5_NEXT_CKPT_FIXTURE_DIR) + "/config.json";
  std::ifstream in(path);
  REQUIRE_MESSAGE(in.good(), "missing fixture: " << path);
  return vllm::ParseHfConfig(nlohmann::json::parse(in), path);
}

// The largest absolute difference, and the index it happened at.
struct Diff {
  double max_abs = 0.0;
  size_t at = 0;
  size_t n_differing = 0;
  bool any_nonfinite = false;
};

Diff Compare(const std::vector<float>& got, const float* want, size_t n,
             double tol) {
  Diff d;
  REQUIRE(got.size() == n);
  for (size_t i = 0; i < n; ++i) {
    if (!std::isfinite(got[i])) d.any_nonfinite = true;
    const double e = std::fabs(static_cast<double>(got[i]) - want[i]);
    if (e > tol) ++d.n_differing;
    if (e > d.max_abs) {
      d.max_abs = e;
      d.at = i;
    }
  }
  return d;
}

// f32 host arithmetic against a torch f32 reference: the tolerance is a few
// ULPs of the accumulated magnitude, not a fudge. Every value in this fixture
// is O(1).
constexpr double kTol = 2e-5;

}  // namespace

// --- (1) the projections and the two absorbed halves ------------------------

TEST_CASE("glm5_next attn: q_a_proj -> q_a_layernorm -> q_resid") {
  const MlaDims d = Dims();
  const Diff x = Compare(QResid(d, L0Weights(), Vec(g::kHiddenStates),
                                g::kBatch, g::kSeqLen),
                         g::kL0QResid,
                         sizeof(g::kL0QResid) / sizeof(float), kTol);
  CHECK(x.n_differing == 0);
  CHECK(x.max_abs < kTol);
  MESSAGE("q_resid max|delta| = " << x.max_abs);
}

TEST_CASE("glm5_next attn: kv_a_proj_with_mqa -> kv_a_layernorm -> k_pass") {
  const MlaDims d = Dims();
  // `qk_rope_head_dim` is ZERO, so the `[kv_lora_rank, qk_rope_head_dim]` split
  // at `:1171` takes the whole projection and `k_rot` has no width. The
  // projection's own row count is what says so.
  CHECK(g::kQkRope == 0);
  CHECK(sizeof(g::kL0KvAProj) / sizeof(float) ==
        static_cast<size_t>((g::kKvLora + g::kQkRope) * g::kHidden));
  const Diff x = Compare(CompressKv(d, L0Weights(), Vec(g::kHiddenStates),
                                    g::kBatch, g::kSeqLen),
                         g::kL0KPass, sizeof(g::kL0KPass) / sizeof(float), kTol);
  CHECK(x.n_differing == 0);
  MESSAGE("k_pass max|delta| = " << x.max_abs);
}

TEST_CASE("glm5_next attn: expand_kv over the SPLIT, half-transposed halves") {
  const MlaDims d = Dims();
  const ExpandedKv kv =
      ExpandKv(d, L0Weights(), Vec(g::kL0KPass), g::kBatch, g::kSeqLen);

  // The rope half has no width, so `key_states` IS `k_nope` (`:1150-1152`).
  CHECK(d.qk_head_dim() == g::kQkNope);
  CHECK(kv.key_states.size() ==
        static_cast<size_t>(g::kBatch * g::kNumHeads * g::kSeqLen * g::kQkNope));

  const Diff k = Compare(kv.key_states, g::kL0KeyStates,
                         sizeof(g::kL0KeyStates) / sizeof(float), kTol);
  const Diff v = Compare(kv.value_states, g::kL0ValueStates,
                         sizeof(g::kL0ValueStates) / sizeof(float), kTol);
  CHECK(k.n_differing == 0);
  CHECK(v.n_differing == 0);
  MESSAGE("key max|delta| = " << k.max_abs << ", value max|delta| = " << v.max_abs);

  // The three widths are DIFFERENT on this fixture, which is what makes the
  // orientation swap a shape error here and a silent one in the square case.
  CHECK(g::kKvLora != g::kQkNope);
  CHECK(g::kVHead != g::kQkNope);
  CHECK(g::kKvLora != g::kVHead);
}

TEST_CASE("glm5_next attn: the SQUARE case — the untransposed k_b is WRONG") {
  // `kv_lora == qk_nope == v_head`, so BOTH readings of `k_b_proj` are
  // shape-valid and only the values separate them. This is the case a shape
  // check cannot make.
  MlaDims d = Dims();
  d.kv_lora_rank = g::kSqDim;
  d.qk_nope_head_dim = g::kSqDim;
  d.v_head_dim = g::kSqDim;

  MlaWeights w = L0Weights();  // only the four square tensors are used below
  w.kv_a_proj_with_mqa = Vec(g::kSqKvAProj);
  w.kv_a_layernorm = Vec(g::kSqKvANorm);
  w.k_b_proj = Vec(g::kSqKB);
  w.v_b_proj = Vec(g::kSqVB);

  const std::vector<float> k_pass =
      CompressKv(d, w, Vec(g::kHiddenStates), g::kBatch, g::kSeqLen);
  const Diff p = Compare(k_pass, g::kSqKPass,
                         sizeof(g::kSqKPass) / sizeof(float), kTol);
  CHECK(p.n_differing == 0);

  const ExpandedKv kv = ExpandKv(d, w, k_pass, g::kBatch, g::kSeqLen);
  const Diff k = Compare(kv.key_states, g::kSqKeyStates,
                         sizeof(g::kSqKeyStates) / sizeof(float), kTol);
  const Diff v = Compare(kv.value_states, g::kSqValueStates,
                         sizeof(g::kSqValueStates) / sizeof(float), kTol);
  CHECK(k.n_differing == 0);
  CHECK(v.n_differing == 0);

  // And this is what the UNTRANSPOSED reading yields. Built here from the same
  // inputs so the comparison is against a value, not a claim; the oracle
  // computed the same tensor independently.
  const int64_t r = g::kSqDim;
  std::vector<float> wrong(kv.key_states.size(), 0.0F);
  for (int64_t b = 0; b < g::kBatch; ++b) {
    for (int64_t h = 0; h < g::kNumHeads; ++h) {
      for (int64_t t = 0; t < g::kSeqLen; ++t) {
        for (int64_t dd = 0; dd < r; ++dd) {
          double acc = 0.0;
          for (int64_t i = 0; i < r; ++i) {
            // `k_b[h][d][i]` — the swapped inner axes.
            acc += static_cast<double>(k_pass[(b * g::kSeqLen + t) * r + i]) *
                   g::kSqKB[(h * r + dd) * r + i];
          }
          wrong[static_cast<size_t>(((b * g::kNumHeads + h) * g::kSeqLen + t) * r +
                                    dd)] = static_cast<float>(acc);
        }
      }
    }
  }
  const Diff wcheck = Compare(wrong, g::kSqKNopeUntransposed,
                              sizeof(g::kSqKNopeUntransposed) / sizeof(float),
                              kTol);
  CHECK(wcheck.n_differing == 0);  // the decoy really is the untransposed read

  // ...and it is NOT what we produce. A tolerance would pass a swap whose
  // values happened to be close, so the separation is printed.
  double sep = 0.0;
  size_t differing = 0;
  for (size_t i = 0; i < wrong.size(); ++i) {
    const double e = std::fabs(kv.key_states[i] - wrong[i]);
    if (e > kTol) ++differing;
    sep = std::max(sep, e);
  }
  CHECK(differing == wrong.size());
  CHECK(sep > 0.1);
  MESSAGE("square k_b: transposed vs untransposed separation = " << sep
          << " over " << differing << " of " << wrong.size() << " values");
}

// --- (2) the mask ------------------------------------------------------------

TEST_CASE("glm5_next attn: build_attention_mask_from_topk") {
  const std::vector<uint8_t> got = BuildAttentionMaskFromTopk(
      IVec(g::kL0Topk), g::kBatch, g::kSeqLen, g::kTopkWidth, g::kSeqLen);
  const std::vector<uint8_t> want = BVec(g::kL0BoolMask);
  REQUIRE(got.size() == want.size());
  size_t bad = 0;
  size_t visible = 0;
  for (size_t i = 0; i < got.size(); ++i) {
    if (got[i] != want[i]) ++bad;
    if (want[i] != 0U) ++visible;
  }
  CHECK(bad == 0);
  // A mask that is all-visible masks nothing and the case is a tautology. This
  // one hides more than half the pairs.
  CHECK(visible < got.size());
  MESSAGE("mask: " << visible << " visible of " << got.size());

  // The `-1` sentinel and an out-of-range index BOTH contribute nothing, and a
  // duplicate contributes once (`:1235-1246`).
  const std::vector<int32_t> odd = {-1, 0, 0, 2, 99, -5};
  const std::vector<uint8_t> m =
      BuildAttentionMaskFromTopk(odd, 1, 1, 6, 4);
  CHECK(m == std::vector<uint8_t>{1U, 0U, 1U, 0U});
}

// --- (3) the whole block, and the finfo.min row ------------------------------

TEST_CASE("glm5_next attn: a FULL layer's forward") {
  const MlaDims d = Dims();
  const IndexerDims id = IdxDims();
  const IndexerStore ix = L0Indexer();
  const IndexerWeights view = ix.View();
  const Glm5NextParams p = FixtureParams();
  const IndexerRole role = IndexerRoleFor(p, 0);
  REQUIRE_FALSE(role.skip_topk);

  std::vector<uint8_t> mask = BVec(g::kMask);
  const AttentionResult r =
      Attention(d, L0Weights(), id, &view, role, Vec(g::kHiddenStates), mask,
                nullptr, 0, g::kBatch, g::kSeqLen);

  CHECK(r.topk_width == g::kTopkWidth);
  CHECK(r.topk_width == id.OutputWidth());
  REQUIRE(r.topk_indices.size() == sizeof(g::kL0Topk) / sizeof(int32_t));
  size_t topk_bad = 0;
  for (size_t i = 0; i < r.topk_indices.size(); ++i) {
    if (r.topk_indices[i] != g::kL0Topk[i]) ++topk_bad;
  }
  CHECK(topk_bad == 0);

  const Diff x = Compare(r.attn_output, g::kL0AttnOut,
                         sizeof(g::kL0AttnOut) / sizeof(float), kTol);
  CHECK(x.n_differing == 0);
  CHECK_FALSE(x.any_nonfinite);
  MESSAGE("layer 0 attn_output max|delta| = " << x.max_abs);

  // Layer 1 of this schedule is `shared`, so layer 0 PROPAGATES (`:1216`).
  CHECK(role.next_skip_topk);
  CHECK(r.propagates_topk);
}

TEST_CASE("glm5_next attn: the all-masked padded row is FINITE, not NaN") {
  // `torch.finfo(dtype).min` and not `-inf` (`:1253`). Row 1's first
  // `kPadRow1` query positions are padding: the indexer marks them invisible,
  // so every key is masked and their softmax is UNIFORM. With `-inf` every
  // term is NaN and the NaN reaches `o_proj` and then the residual stream.
  const MlaDims d = Dims();
  const IndexerDims id = IdxDims();
  const IndexerStore ix = L0Indexer();
  const IndexerWeights view = ix.View();
  const AttentionResult r =
      Attention(d, L0Weights(), id, &view, IndexerRoleFor(FixtureParams(), 0),
                Vec(g::kHiddenStates), BVec(g::kMask), nullptr, 0, g::kBatch,
                g::kSeqLen);

  const std::vector<uint8_t> vis = BuildAttentionMaskFromTopk(
      r.topk_indices, g::kBatch, g::kSeqLen, r.topk_width, g::kSeqLen);
  int64_t all_masked_rows = 0;
  for (int64_t t = 0; t < g::kPadRow1; ++t) {
    int64_t seen = 0;
    for (int64_t s = 0; s < g::kSeqLen; ++s) {
      seen += vis[static_cast<size_t>((1 * g::kSeqLen + t) * g::kSeqLen + s)];
    }
    if (seen == 0) ++all_masked_rows;
    for (int64_t h = 0; h < g::kHidden; ++h) {
      const float v = r.attn_output[static_cast<size_t>(
          (1 * g::kSeqLen + t) * g::kHidden + h)];
      CHECK(std::isfinite(v));
    }
  }
  // The case is only a case if such a row EXISTS. A fixture whose padded rows
  // still see a key would pass a `-inf` port.
  CHECK(all_masked_rows == g::kPadRow1);
  MESSAGE("all-masked query rows exercised: " << all_masked_rows);
}

// --- (4) CROSS-LAYER TOP-K SHARING — the highest-value case in the wave ------

TEST_CASE("glm5_next attn: IndexerRoleFor mirrors skip_topk / next_skip_topk") {
  const Glm5NextParams p = FixtureParams();
  REQUIRE(p.indexer_types.size() == static_cast<size_t>(g::kNumLayers));

  // `["full", "shared", "full", "full"]`.
  const IndexerRole r0 = IndexerRoleFor(p, 0);
  const IndexerRole r1 = IndexerRoleFor(p, 1);
  const IndexerRole r2 = IndexerRoleFor(p, 2);
  const IndexerRole r3 = IndexerRoleFor(p, 3);
  CHECK_FALSE(r0.skip_topk);
  CHECK(r0.next_skip_topk);   // layer 1 is shared, so layer 0 propagates
  CHECK(r1.skip_topk);
  CHECK_FALSE(r1.next_skip_topk);  // a shared layer never propagates (`:1132-1133`)
  CHECK_FALSE(r2.skip_topk);
  CHECK_FALSE(r2.next_skip_topk);
  CHECK_FALSE(r3.skip_topk);
  // The `min(layer_idx + 1, len - 1)` CLAMP: the last layer looks at ITSELF.
  CHECK_FALSE(r3.next_skip_topk);
  for (int64_t i = 0; i < g::kNumLayers; ++i) {
    CHECK(IndexerRoleFor(p, i).skip_topk == g::kIndexerShared[i]);
  }

  // A `shared` LAST layer makes its own predecessor propagate, which is the
  // clamp's arithmetic and not a guard. Stated as a case so a "fix" that
  // special-cases the tail is caught.
  Glm5NextParams tail = p;
  tail.indexer_types.back() = Glm5NextIndexerKind::kShared;
  CHECK(IndexerRoleFor(tail, 2).next_skip_topk);
  CHECK(IndexerRoleFor(tail, 3).skip_topk);
  CHECK_FALSE(IndexerRoleFor(tail, 3).next_skip_topk);

  // THE CLAMP, discriminated. `min(layer_idx + 1, len - 1)` and a WRAPPING
  // `(layer_idx + 1) % len` agree on every schedule above, so neither would
  // catch a port that wrapped. They disagree exactly when the LAST layer is
  // `full` and the FIRST is `shared`: the clamp reads the last layer itself
  // (`full`, no propagation) and a wrap reads layer 0 (`shared`, propagation).
  // A `shared` first layer is not a runnable schedule -- it has no predecessor
  // to inherit from -- but `IndexerRoleFor` is arithmetic over the array and
  // this is the shape that separates the two readings.
  Glm5NextParams wrap = p;
  wrap.indexer_types[0] = Glm5NextIndexerKind::kShared;
  wrap.indexer_types[1] = Glm5NextIndexerKind::kFull;
  CHECK(wrap.indexer_types.back() == Glm5NextIndexerKind::kFull);
  CHECK_FALSE(IndexerRoleFor(wrap, g::kNumLayers - 1).next_skip_topk);

  CHECK_THROWS_AS(IndexerRoleFor(p, g::kNumLayers), std::runtime_error);
  CHECK_THROWS_AS(IndexerRoleFor(p, -1), std::runtime_error);
}

TEST_CASE("glm5_next attn: a SHARED layer REUSES the previous selection") {
  const MlaDims d = Dims();
  const IndexerDims id = IdxDims();
  const Glm5NextParams p = FixtureParams();
  const IndexerRole role = IndexerRoleFor(p, 1);
  REQUIRE(role.skip_topk);

  const std::vector<int32_t> prev = IVec(g::kL0Topk);
  const AttentionResult shared =
      Attention(d, L1Weights(), id, /*indexer=*/nullptr, role,
                Vec(g::kHiddenStates), BVec(g::kMask), &prev, g::kTopkWidth,
                g::kBatch, g::kSeqLen);

  // It USED the caller's selection, unchanged.
  CHECK(shared.topk_indices == prev);
  CHECK(shared.topk_width == g::kTopkWidth);
  // ...and it propagates NOTHING (`:1132-1133`, `:1216`).
  CHECK_FALSE(shared.propagates_topk);

  const Diff ok = Compare(shared.attn_output, g::kL1SharedAttnOut,
                          sizeof(g::kL1SharedAttnOut) / sizeof(float), kTol);
  CHECK(ok.n_differing == 0);
  MESSAGE("shared attn_output max|delta| = " << ok.max_abs);

  // THE ASSERTION THIS CASE EXISTS FOR. A port that RECOMPUTES produces
  // `kL1RecomputedAttnOut`; ours must not. Both goldens come from the same
  // oracle run, so the inequality is between two REFERENCE values and not
  // between a reference and a guess.
  size_t differing = 0;
  double sep = 0.0;
  const size_t n = sizeof(g::kL1RecomputedAttnOut) / sizeof(float);
  REQUIRE(shared.attn_output.size() == n);
  for (size_t i = 0; i < n; ++i) {
    const double e =
        std::fabs(static_cast<double>(shared.attn_output[i]) -
                  g::kL1RecomputedAttnOut[i]);
    if (e > kTol) ++differing;
    sep = std::max(sep, e);
  }
  CHECK(differing > 0);
  CHECK(sep > 0.1);
  MESSAGE("shared vs RECOMPUTED: " << differing << " of " << n
          << " values differ, max separation " << sep);
}

TEST_CASE("glm5_next attn: the RECOMPUTED golden really is a recomputation") {
  // Without this case the inequality above could be satisfied by any two
  // different numbers. Running layer 1 as a FULL layer over the decoy indexer
  // must reproduce `kL1RecomputedAttnOut` exactly, which is what makes
  // `kL1RecomputedAttnOut` a wrong PORT's output rather than an arbitrary one.
  const MlaDims d = Dims();
  const IndexerDims id = IdxDims();
  const IndexerStore decoy = DecoyIndexer();
  const IndexerWeights view = decoy.View();
  IndexerRole as_full;
  as_full.skip_topk = false;
  as_full.next_skip_topk = false;

  const AttentionResult r =
      Attention(d, L1Weights(), id, &view, as_full, Vec(g::kHiddenStates),
                BVec(g::kMask), nullptr, 0, g::kBatch, g::kSeqLen);

  REQUIRE(r.topk_indices.size() == sizeof(g::kL1DecoyTopk) / sizeof(int32_t));
  size_t topk_bad = 0;
  size_t topk_differs_from_l0 = 0;
  for (size_t i = 0; i < r.topk_indices.size(); ++i) {
    if (r.topk_indices[i] != g::kL1DecoyTopk[i]) ++topk_bad;
    if (g::kL1DecoyTopk[i] != g::kL0Topk[i]) ++topk_differs_from_l0;
  }
  CHECK(topk_bad == 0);
  // The two selections must actually DISAGREE, or the shared case above proves
  // nothing about sharing.
  CHECK(topk_differs_from_l0 > 0);
  MESSAGE("decoy vs layer-0 selection: " << topk_differs_from_l0 << " of "
          << r.topk_indices.size() << " slots differ");

  const Diff x = Compare(r.attn_output, g::kL1RecomputedAttnOut,
                         sizeof(g::kL1RecomputedAttnOut) / sizeof(float), kTol);
  CHECK(x.n_differing == 0);
}

TEST_CASE("glm5_next attn: the shared-layer contract is refused BY NAME") {
  const MlaDims d = Dims();
  const IndexerDims id = IdxDims();
  const IndexerStore ix = L0Indexer();
  const IndexerWeights view = ix.View();
  const Glm5NextParams p = FixtureParams();
  const std::vector<float> hidden = Vec(g::kHiddenStates);
  const std::vector<uint8_t> mask = BVec(g::kMask);
  const std::vector<int32_t> prev = IVec(g::kL0Topk);

  // A shared layer with no previous selection. Upstream's own message
  // (`:1190`), so a log line means the same thing on both sides.
  CHECK_THROWS_WITH_AS(
      Attention(d, L1Weights(), id, nullptr, IndexerRoleFor(p, 1), hidden, mask,
                nullptr, 0, g::kBatch, g::kSeqLen),
      doctest::Contains("Shared DSA layers require top-k indices from a "
                        "previous full indexer layer."),
      std::runtime_error);

  // A shared layer HANDED an indexer. Refused rather than quietly preferring
  // one arm: accepting it is exactly how a recomputing port gets written.
  CHECK_THROWS_AS(Attention(d, L1Weights(), id, &view, IndexerRoleFor(p, 1),
                            hidden, mask, &prev, g::kTopkWidth, g::kBatch,
                            g::kSeqLen),
                  std::runtime_error);

  // A full layer with no indexer.
  CHECK_THROWS_AS(Attention(d, L0Weights(), id, nullptr, IndexerRoleFor(p, 0),
                            hidden, mask, nullptr, 0, g::kBatch, g::kSeqLen),
                  std::runtime_error);
}

// --- (5) the geometry refusals ----------------------------------------------

TEST_CASE("glm5_next attn: a positive RoPE width is refused, in upstream's words") {
  MlaDims d = Dims();
  d.qk_rope_head_dim = 2;
  // `kRopeRefusal` is the sentence `Glm5NextTextConfig.validate_architecture`
  // raised when the GENERATOR constructed such a config. Our refusal is gated
  // against the reference's own message, not against a transcription of it.
  CHECK_THROWS_WITH_AS(d.Validate(), doctest::Contains(g::kRopeRefusal),
                       std::runtime_error);

  MlaDims zero = Dims();
  CHECK_NOTHROW(zero.Validate());
  CHECK(zero.qk_rope_head_dim == 0);
  CHECK(zero.qk_head_dim() == g::kQkNope);
  // `self.scaling = self.qk_head_dim ** (-0.5)` (`:1128`) — the MLA head dim,
  // not `v_head_dim` and not the indexer's.
  CHECK(zero.scaling() ==
        doctest::Approx(1.0 / std::sqrt(static_cast<double>(g::kQkNope))));
  CHECK(zero.scaling() !=
        doctest::Approx(1.0 / std::sqrt(static_cast<double>(g::kVHead))));

  for (int64_t* field : {&zero.hidden_size, &zero.num_heads, &zero.q_lora_rank,
                         &zero.kv_lora_rank, &zero.qk_nope_head_dim,
                         &zero.v_head_dim}) {
    const int64_t saved = *field;
    *field = 0;
    CHECK_THROWS_AS(zero.Validate(), std::runtime_error);
    *field = saved;
  }
}

TEST_CASE("glm5_next attn: MlaDimsFrom reads the PUBLISHED config") {
  const Glm5NextParams p = vllm::ParseGlm5NextParams(PublishedConfig());
  const MlaDims d = MlaDimsFrom(p);
  // The published checkpoint's values, none of them a class default.
  CHECK(d.hidden_size == 4096);
  CHECK(d.num_heads == 64);
  CHECK(d.q_lora_rank == 1536);
  CHECK(d.kv_lora_rank == 512);
  CHECK(d.qk_nope_head_dim == 256);
  CHECK(d.qk_rope_head_dim == 0);
  CHECK(d.v_head_dim == 256);
  CHECK(d.qk_head_dim() == 256);
  CHECK(d.rms_norm_eps == doctest::Approx(1e-5));

  // ALL 45 layers are `full` on this checkpoint, so NO layer shares and NO
  // layer propagates. Recorded as a measurement rather than a belief: the
  // `shared` arm is config-keyed and this artifact does not select it, which is
  // why the fixture above declares its own schedule.
  REQUIRE(p.indexer_types.size() == 45U);
  int64_t shared = 0;
  int64_t propagating = 0;
  for (int64_t i = 0; i < 45; ++i) {
    const IndexerRole r = IndexerRoleFor(p, i);
    shared += r.skip_topk ? 1 : 0;
    propagating += r.next_skip_topk ? 1 : 0;
  }
  CHECK(shared == 0);
  CHECK(propagating == 0);
  MESSAGE("published schedule: " << shared << " shared layers of 45");
}

// --- (6) every golden is read -----------------------------------------------

TEST_CASE("glm5_next attn: every emitted golden is consumed by an assertion") {
  // Not decoration. W3 emitted a `kIndexScores` golden that no case read, and
  // two real scale defects then passed 1602 assertions (spec `## Owed`). This
  // case names each array and the case that reads it, so a golden added without
  // a reader is a visible omission rather than an invisible one.
  //
  //   kHiddenStates, kMask ............... every forward case
  //   kL0QAProj/QANorm ................... (1) q_resid
  //   kL0KvAProj/KvANorm ................. (1) k_pass
  //   kL0KB/VB ........................... (1) expand_kv
  //   kL0QBProj/OProj, kL0Idx* ........... (3) a FULL layer's forward
  //   kL0QResid/KPass/KeyStates/ValueStates (1)
  //   kL0Topk ............................ (2) mask, (3) forward, (4) shared
  //   kL0BoolMask ........................ (2) mask
  //   kL0AttnOut ......................... (3) forward
  //   kL1QAProj..OProj ................... (4) shared and recomputed
  //   kL1DecoyIdx* ....................... (4) the recomputation
  //   kL1DecoyTopk ....................... (4) the recomputation
  //   kL1SharedAttnOut ................... (4) shared
  //   kL1RecomputedAttnOut ............... (4) shared (inequality) + recomputed
  //   kSqKvAProj/KvANorm/KB/VB ........... (1) the square case
  //   kSqKPass/KeyStates/ValueStates ..... (1) the square case
  //   kSqKNopeUntransposed ............... (1) the square case
  //   kRopeRefusal ....................... (5) the RoPE refusal
  //
  // The sizes below are what makes the list checkable rather than a comment: a
  // golden regenerated at a different geometry breaks here first.
  CHECK(sizeof(g::kHiddenStates) / sizeof(float) ==
        static_cast<size_t>(g::kBatch * g::kSeqLen * g::kHidden));
  CHECK(sizeof(g::kMask) / sizeof(int32_t) ==
        static_cast<size_t>(g::kBatch * g::kSeqLen));
  CHECK(sizeof(g::kL0Topk) / sizeof(int32_t) ==
        static_cast<size_t>(g::kBatch * g::kSeqLen * g::kTopkWidth));
  CHECK(sizeof(g::kL0BoolMask) / sizeof(int32_t) ==
        static_cast<size_t>(g::kBatch * g::kSeqLen * g::kSeqLen));
  CHECK(sizeof(g::kL0AttnOut) / sizeof(float) ==
        static_cast<size_t>(g::kBatch * g::kSeqLen * g::kHidden));
  CHECK(sizeof(g::kL1SharedAttnOut) == sizeof(g::kL0AttnOut));
  CHECK(sizeof(g::kL1RecomputedAttnOut) == sizeof(g::kL0AttnOut));
  CHECK(sizeof(g::kSqKNopeUntransposed) / sizeof(float) ==
        static_cast<size_t>(g::kBatch * g::kNumHeads * g::kSeqLen * g::kSqDim));
  CHECK(g::kSeqLen > g::kIndexTopk);  // or the selection is the identity
}
