// Ported from deepseek-ai/DeepSeek-V4-Flash-Vision-Exp
// inference/vision.py at revision
// 86f746b36186f0e567729a5c06a8c918caba82a9. The committed stage goldens were
// generated by scripts/gen-deepseek-v4-vision-goldens.py with torch 2.11.0.
#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <fstream>
#include <limits>
#include <memory>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "doctest/doctest.h"
#include "vllm/model_executor/models/deepseek_v4_vision.h"
#include "vllm/model_executor/models/dense_device_glue.h"
#include "vllm/model_executor/models/device_pool.h"
#include "vt/dtype.h"

#ifndef DEEPSEEK_V4_VISION_GOLDEN
#error "DEEPSEEK_V4_VISION_GOLDEN must name the committed oracle fixture"
#endif

namespace {

using json = nlohmann::json;
using vllm::dense_attn::DBuf;
using vllm::dense_attn::Dev;
using vllm::multimodal::DeepSeekV4Vision;
using vllm::multimodal::DeepSeekV4VisionBlockWeights;
using vllm::multimodal::DeepSeekV4VisionCapture;
using vllm::multimodal::DeepSeekV4VisionConfig;
using vllm::multimodal::DeepSeekV4VisionRopeCosSin;
using vllm::multimodal::DeepSeekV4VisionWeights;
using vt::Backend;
using vt::DType;
using vt::Queue;
using vt::Tensor;

const json& Goldens() {
  static const json document = [] {
    std::ifstream input(DEEPSEEK_V4_VISION_GOLDEN);
    if (!input) throw std::runtime_error("cannot open DeepSeek-V4 vision golden");
    return json::parse(input);
  }();
  return document;
}

std::vector<float> Floats(const json& values) {
  return values.get<std::vector<float>>();
}

std::vector<uint16_t> Bf16(const json& values) {
  const std::vector<float> floats = Floats(values);
  std::vector<uint16_t> words(floats.size());
  for (size_t i = 0; i < floats.size(); ++i) words[i] = vt::F32ToBF16(floats[i]);
  return words;
}

class TensorStore {
 public:
  TensorStore(Backend& backend, Queue& queue) : dev_{backend, queue} {}

  Tensor Make(const json& values, DType dtype, std::vector<int64_t> shape) {
    if (dtype == DType::kBF16) {
      const std::vector<uint16_t> words = Bf16(values);
      buffers_.push_back(std::make_unique<DBuf>(dev_, dtype, shape, words.data()));
    } else {
      const std::vector<float> floats = Floats(values);
      buffers_.push_back(std::make_unique<DBuf>(dev_, dtype, shape, floats.data()));
    }
    return buffers_.back()->t();
  }

  Tensor Empty(DType dtype, std::vector<int64_t> shape) {
    buffers_.push_back(std::make_unique<DBuf>(dev_, dtype, shape));
    return buffers_.back()->t();
  }

  std::vector<float> Download(const Tensor& tensor) {
    const size_t count = static_cast<size_t>(tensor.Numel());
    std::vector<float> result(count);
    if (tensor.dtype == DType::kBF16) {
      std::vector<uint16_t> words(count);
      dev_.b.Copy(dev_.q, words.data(), tensor.data, words.size() * sizeof(uint16_t));
      dev_.b.Synchronize(dev_.q);
      for (size_t i = 0; i < count; ++i) result[i] = vt::BF16ToF32(words[i]);
    } else {
      dev_.b.Copy(dev_.q, result.data(), tensor.data, result.size() * sizeof(float));
      dev_.b.Synchronize(dev_.q);
    }
    return result;
  }

 private:
  Dev dev_;
  std::vector<std::unique_ptr<DBuf>> buffers_;
};

DeepSeekV4VisionConfig Config(const json& fixture) {
  const json& c = fixture.at("config");
  DeepSeekV4VisionConfig config;
  config.patch_size = c.at("patch_size").get<int64_t>();
  config.hidden_size = c.at("hidden_size").get<int64_t>();
  config.num_heads = c.at("num_heads").get<int64_t>();
  config.depth = c.at("depth").get<int64_t>();
  config.intermediate_size = c.at("intermediate_size").get<int64_t>();
  config.output_size = c.at("output_size").get<int64_t>();
  config.downsample_ratio = c.at("downsample_ratio").get<int64_t>();
  config.norm_epsilon = c.at("norm_epsilon").get<float>();
  config.rope_theta = c.at("rope_theta").get<double>();
  config.compute_dtype = DType::kBF16;
  return config;
}

DeepSeekV4VisionWeights Weights(const json& fixture, const DeepSeekV4VisionConfig& config,
                                TensorStore& store) {
  const json& w = fixture.at("weights");
  const int64_t h = config.hidden_size;
  const int64_t inter = config.intermediate_size;
  const int64_t out = config.output_size;
  DeepSeekV4VisionWeights weights;
  weights.patch_weight = store.Make(w.at("patch_weight"), config.compute_dtype,
                                    {h, config.patch_dim()});
  weights.patch_bias = store.Make(w.at("patch_bias"), config.compute_dtype, {h});
  for (const json& block : w.at("blocks")) {
    DeepSeekV4VisionBlockWeights layer;
    layer.norm1_weight = store.Make(block.at("norm1"), DType::kF32, {h});
    layer.qkv_weight = store.Make(block.at("qkv_weight"), config.compute_dtype,
                                  {3 * h, h});
    layer.qkv_bias = store.Make(block.at("qkv_bias"), config.compute_dtype, {3 * h});
    layer.out_weight = store.Make(block.at("out_weight"), config.compute_dtype, {h, h});
    layer.out_bias = store.Make(block.at("out_bias"), config.compute_dtype, {h});
    layer.norm2_weight = store.Make(block.at("norm2"), DType::kF32, {h});
    layer.mlp_w1_weight = store.Make(block.at("mlp_w1"), config.compute_dtype,
                                     {2 * inter, h});
    layer.mlp_w2_weight = store.Make(block.at("mlp_w2"), config.compute_dtype,
                                     {h, inter});
    weights.blocks.push_back(layer);
  }
  weights.final_norm_weight = store.Make(w.at("final_norm"), DType::kF32, {h});
  weights.aligner_w1_weight = store.Make(w.at("aligner_w1_weight"), config.compute_dtype,
                                         {out, config.aligner_input_size()});
  weights.aligner_w1_bias = store.Make(w.at("aligner_w1_bias"), config.compute_dtype, {out});
  weights.aligner_w2_weight = store.Make(w.at("aligner_w2_weight"), config.compute_dtype,
                                         {out, out});
  weights.aligner_w2_bias = store.Make(w.at("aligner_w2_bias"), config.compute_dtype, {out});
  return weights;
}

float MaxAbsDiff(const std::vector<float>& actual, const json& expected_json) {
  const std::vector<float> expected = Floats(expected_json);
  REQUIRE(actual.size() == expected.size());
  float maximum = 0.0f;
  for (size_t i = 0; i < actual.size(); ++i) {
    REQUIRE(std::isfinite(actual[i]));
    maximum = std::max(maximum, std::abs(actual[i] - expected[i]));
  }
  return maximum;
}

class CountingBackend final : public Backend {
 public:
  explicit CountingBackend(Backend& inner) : inner_(inner) {}

  void* Alloc(size_t bytes) override {
    ++allocations_;
    return inner_.Alloc(bytes);
  }
  void Free(void* pointer) override { inner_.Free(pointer); }
  void OnScratchBlockAcquired(void* pointer) override {
    inner_.OnScratchBlockAcquired(pointer);
  }
  void Memset(Queue& queue, void* pointer, int value, size_t bytes) override {
    inner_.Memset(queue, pointer, value, bytes);
  }
  void Copy(Queue& queue, void* destination, const void* source, size_t bytes) override {
    inner_.Copy(queue, destination, source, bytes);
  }
  Queue CreateQueue() override { return inner_.CreateQueue(); }
  void DestroyQueue(Queue& queue) override { inner_.DestroyQueue(queue); }
  void Synchronize(Queue& queue) override { inner_.Synchronize(queue); }
  bool UnifiedMemory() const override { return inner_.UnifiedMemory(); }
  bool DeviceMemoryIsHostAddressable() const override {
    return inner_.DeviceMemoryIsHostAddressable();
  }

  size_t allocations() const { return allocations_; }

 private:
  Backend& inner_;
  size_t allocations_ = 0;
};

struct CaptureTensors {
  explicit CaptureTensors(TensorStore& store, const DeepSeekV4VisionConfig& config,
                          int64_t patch_rows, int64_t output_rows) {
    patch = store.Empty(config.compute_dtype, {patch_rows, config.hidden_size});
    capture.patch_embedding = &patch;
    blocks.reserve(static_cast<size_t>(config.depth));
    capture.block_outputs.reserve(static_cast<size_t>(config.depth));
    for (int64_t i = 0; i < config.depth; ++i) {
      blocks.push_back(store.Empty(config.compute_dtype, {patch_rows, config.hidden_size}));
      capture.block_outputs.push_back(&blocks.back());
    }
    final_norm = store.Empty(config.compute_dtype, {patch_rows, config.hidden_size});
    unfold = store.Empty(config.compute_dtype, {output_rows, config.aligner_input_size()});
    aligner_hidden = store.Empty(config.compute_dtype, {output_rows, config.output_size});
    gelu = store.Empty(config.compute_dtype, {output_rows, config.output_size});
    capture.final_norm = &final_norm;
    capture.aligner_unfold = &unfold;
    capture.aligner_hidden = &aligner_hidden;
    capture.aligner_gelu = &gelu;
  }

  DeepSeekV4VisionCapture capture;
  Tensor patch;
  std::vector<Tensor> blocks;
  Tensor final_norm;
  Tensor unfold;
  Tensor aligner_hidden;
  Tensor gelu;
};

}  // namespace

TEST_CASE("DeepSeek-V4 vision goldens pin the model-author source") {
  const json& document = Goldens();
  CHECK(document.at("oracle") == "deepseek-ai/DeepSeek-V4-Flash-Vision-Exp");
  CHECK(document.at("revision") == "86f746b36186f0e567729a5c06a8c918caba82a9");
  CHECK(document.at("source") == "inference/vision.py");
  CHECK(document.at("torch_version") == "2.11.0+cu130");
}

TEST_CASE("DeepSeek-V4 2-D RoPE keeps height then width frequencies") {
  for (const json& fixture : Goldens().at("fixtures")) {
    const DeepSeekV4VisionConfig config = Config(fixture);
    for (const json& test_case : fixture.at("cases")) {
      const int64_t height = test_case.at("grid").at(0).get<int64_t>();
      const int64_t width = test_case.at("grid").at(1).get<int64_t>();
      std::vector<float> cosine;
      std::vector<float> sine;
      DeepSeekV4VisionRopeCosSin(height, width, config, &cosine, &sine);
      CAPTURE(fixture.at("name"));
      CAPTURE(test_case.at("name"));
      CHECK(MaxAbsDiff(cosine, test_case.at("expected").at("rope_cos")) <= 2.0e-6f);
      CHECK(MaxAbsDiff(sine, test_case.at("expected").at("rope_sin")) <= 2.0e-6f);
    }
  }
}

TEST_CASE("DeepSeek-V4 ViT and aligner match pinned BF16 stage goldens") {
  Backend& backend = vt::GetBackend(vt::DeviceType::kCPU);
  Queue queue = backend.CreateQueue();
  for (const json& fixture : Goldens().at("fixtures")) {
    const DeepSeekV4VisionConfig config = Config(fixture);
    TensorStore store(backend, queue);
    DeepSeekV4Vision model(backend, config, Weights(fixture, config, store));
    CHECK(model.config().depth == config.depth);
    for (const json& test_case : fixture.at("cases")) {
      const int64_t height = test_case.at("grid").at(0).get<int64_t>();
      const int64_t width = test_case.at("grid").at(1).get<int64_t>();
      const int64_t patch_rows = height * width;
      const int64_t output_rows = config.aligned_rows(height, width);
      Tensor patches = store.Make(test_case.at("patches"), config.compute_dtype,
                                  {patch_rows, config.patch_dim()});
      Tensor output = store.Empty(config.compute_dtype, {output_rows, config.output_size});
      CaptureTensors captures(store, config, patch_rows, output_rows);
      model.Forward(queue, output, patches, height, width, &captures.capture);

      const json& expected = test_case.at("expected");
      CAPTURE(fixture.at("name"));
      CAPTURE(test_case.at("name"));
      CHECK(MaxAbsDiff(store.Download(captures.patch), expected.at("patch_embedding")) <= 0.004f);
      for (int64_t layer = 0; layer < config.depth; ++layer) {
        CAPTURE(layer);
        CHECK(MaxAbsDiff(store.Download(captures.blocks[static_cast<size_t>(layer)]),
                         expected.at("blocks").at(static_cast<size_t>(layer))) <= 0.01f);
      }
      CHECK(MaxAbsDiff(store.Download(captures.final_norm), expected.at("vision")) <= 0.024f);
      CHECK(MaxAbsDiff(store.Download(captures.unfold), expected.at("unfold")) <= 0.024f);
      CHECK(MaxAbsDiff(store.Download(captures.aligner_hidden),
                       expected.at("aligner_hidden")) <= 0.016f);
      CHECK(MaxAbsDiff(store.Download(captures.gelu), expected.at("gelu")) <= 0.01f);
      CHECK(MaxAbsDiff(store.Download(output), expected.at("output")) <= 0.01f);
      CHECK(output.dtype == DType::kBF16);
      CHECK(output.IsContiguous());
    }
  }
  backend.DestroyQueue(queue);
}

TEST_CASE("DeepSeek-V4 aligner preserves F.unfold channel-major order and zero padding") {
  Backend& backend = vt::GetBackend(vt::DeviceType::kCPU);
  Queue queue = backend.CreateQueue();
  const json& fixture = Goldens().at("fixtures").at(0);
  const DeepSeekV4VisionConfig config = Config(fixture);
  TensorStore store(backend, queue);
  DeepSeekV4Vision model(backend, config, Weights(fixture, config, store));
  const int64_t height = 2;
  const int64_t width = 5;
  const int64_t patch_rows = height * width;
  const int64_t output_rows = config.aligned_rows(height, width);
  std::vector<float> source(static_cast<size_t>(patch_rows * config.hidden_size));
  for (size_t i = 0; i < source.size(); ++i) {
    source[i] = static_cast<float>(i + 1);
  }
  Tensor vision = store.Make(json(source), config.compute_dtype,
                             {patch_rows, config.hidden_size});
  Tensor output = store.Empty(config.compute_dtype,
                              {output_rows, config.output_size});
  Tensor unfold = store.Empty(config.compute_dtype,
                              {output_rows, config.aligner_input_size()});
  DeepSeekV4VisionCapture capture;
  capture.aligner_unfold = &unfold;
  model.AlignerForward(queue, output, vision, height, width, &capture);
  const std::vector<float> actual = store.Download(unfold);

  std::vector<float> expected;
  expected.reserve(actual.size());
  const int64_t ratio = config.downsample_ratio;
  for (int64_t block_row = 0; block_row < (height + ratio - 1) / ratio;
       ++block_row) {
    for (int64_t block_column = 0;
         block_column < (width + ratio - 1) / ratio; ++block_column) {
      for (int64_t channel = 0; channel < config.hidden_size; ++channel) {
        for (int64_t local_row = 0; local_row < ratio; ++local_row) {
          for (int64_t local_column = 0; local_column < ratio; ++local_column) {
            const int64_t row = block_row * ratio + local_row;
            const int64_t column = block_column * ratio + local_column;
            expected.push_back(
                row < height && column < width
                    ? source[static_cast<size_t>((row * width + column) *
                                                 config.hidden_size + channel)]
                    : 0.0f);
          }
        }
      }
    }
  }
  CHECK(actual == expected);
  const size_t second_block = static_cast<size_t>(config.aligner_input_size());
  CHECK(actual[second_block + 2] == 0.0f);
  CHECK(actual[second_block + 5] == 0.0f);
  CHECK(actual[second_block + 8] == 0.0f);
  CHECK(actual[6] == 0.0f);
  backend.DestroyQueue(queue);
}

TEST_CASE("DeepSeek-V4 aligner uses exact erf GELU") {
  Backend& backend = vt::GetBackend(vt::DeviceType::kCPU);
  Queue queue = backend.CreateQueue();
  const json& fixture = Goldens().at("fixtures").at(0);
  const json& probe = Goldens().at("gelu_probe");
  const DeepSeekV4VisionConfig config = Config(fixture);
  TensorStore store(backend, queue);
  DeepSeekV4VisionWeights weights = Weights(fixture, config, store);
  const std::vector<float> zeros(
      static_cast<size_t>(config.output_size * config.aligner_input_size()),
      0.0f);
  weights.aligner_w1_weight =
      store.Make(json(zeros), config.compute_dtype,
                 {config.output_size, config.aligner_input_size()});
  weights.aligner_w1_bias =
      store.Make(probe.at("input"), config.compute_dtype, {config.output_size});
  DeepSeekV4Vision model(backend, config, std::move(weights));

  const std::vector<float> vision_zeros(
      static_cast<size_t>(config.hidden_size), 0.0f);
  Tensor vision = store.Make(json(vision_zeros), config.compute_dtype,
                             {1, config.hidden_size});
  Tensor output = store.Empty(config.compute_dtype, {1, config.output_size});
  Tensor hidden = store.Empty(config.compute_dtype, {1, config.output_size});
  Tensor gelu = store.Empty(config.compute_dtype, {1, config.output_size});
  DeepSeekV4VisionCapture capture;
  capture.aligner_hidden = &hidden;
  capture.aligner_gelu = &gelu;
  model.AlignerForward(queue, output, vision, 1, 1, &capture);

  CHECK(store.Download(hidden) == Floats(probe.at("input")));
  CHECK(store.Download(gelu) == Floats(probe.at("expected")));
  backend.DestroyQueue(queue);
}

TEST_CASE("DeepSeek-V4 vision rejects invalid geometry dtype layout and weights") {
  Backend& backend = vt::GetBackend(vt::DeviceType::kCPU);
  Queue queue = backend.CreateQueue();
  const json& fixture = Goldens().at("fixtures").at(0);
  DeepSeekV4VisionConfig config = Config(fixture);
  TensorStore store(backend, queue);

  SUBCASE("head geometry") {
    config.hidden_size = 10;
    config.num_heads = 2;
    CHECK_THROWS_WITH_AS(DeepSeekV4Vision(backend, config, {}),
                         "DeepSeek-V4 vision head dimension must be divisible by four",
                         std::invalid_argument);
  }
  SUBCASE("depth") {
    DeepSeekV4VisionWeights weights = Weights(fixture, config, store);
    weights.blocks.pop_back();
    CHECK_THROWS_WITH_AS(DeepSeekV4Vision(backend, config, std::move(weights)),
                         "DeepSeek-V4 vision block count does not match depth",
                         std::invalid_argument);
  }
  SUBCASE("unsupported dtype") {
    config.compute_dtype = DType::kF16;
    CHECK_THROWS_WITH_AS(DeepSeekV4Vision(backend, config, {}),
                         "DeepSeek-V4 vision compute dtype must be bf16",
                         std::invalid_argument);
  }
  SUBCASE("input and output contracts") {
    DeepSeekV4Vision model(backend, config, Weights(fixture, config, store));
    const json& test_case = fixture.at("cases").at(0);
    Tensor patches = store.Make(test_case.at("patches"), config.compute_dtype,
                                {10, config.patch_dim()});
    Tensor output = store.Empty(config.compute_dtype, {2, config.output_size});
    Tensor wrong_rows = patches;
    wrong_rows.shape[0] = 9;
    CHECK_THROWS_WITH_AS(model.Forward(queue, output, wrong_rows, 2, 5),
                         "DeepSeek-V4 vision patches must be [height*width, patch_dim]",
                         std::invalid_argument);
    Tensor strided = patches;
    strided.stride[0] += 1;
    CHECK_THROWS_WITH_AS(model.Forward(queue, output, strided, 2, 5),
                         "DeepSeek-V4 vision patches must be contiguous",
                         std::invalid_argument);
    Tensor wrong_dtype = store.Empty(DType::kF32, {2, config.output_size});
    CHECK_THROWS_WITH_AS(model.Forward(queue, wrong_dtype, patches, 2, 5),
                         "DeepSeek-V4 vision output dtype must equal model dtype",
                         std::invalid_argument);
    CHECK_THROWS_WITH_AS(model.Forward(queue, output, patches, 0, 5),
                         "DeepSeek-V4 vision grid dimensions must be positive",
                         std::invalid_argument);
  }
  backend.DestroyQueue(queue);
}

TEST_CASE("DeepSeek-V4 repeated shape reuses scratch and 2-D RoPE allocation") {
  Backend& inner = vt::GetBackend(vt::DeviceType::kCPU);
  CountingBackend backend(inner);
  vllm::Pool(backend).Drain(backend);
  Queue queue = backend.CreateQueue();
  const json& fixture = Goldens().at("fixtures").at(0);
  const json& test_case = fixture.at("cases").at(0);
  const DeepSeekV4VisionConfig config = Config(fixture);
  TensorStore store(backend, queue);
  DeepSeekV4Vision model(backend, config, Weights(fixture, config, store));
  Tensor patches = store.Make(test_case.at("patches"), config.compute_dtype,
                              {10, config.patch_dim()});
  Tensor output = store.Empty(config.compute_dtype, {2, config.output_size});

  model.Forward(queue, output, patches, 2, 5);
  backend.Synchronize(queue);
  const size_t after_warmup = backend.allocations();
  const auto pool_after_warmup = vllm::Pool(backend).stats();
  CHECK(model.cached_geometry_count() == 1);

  model.Forward(queue, output, patches, 2, 5);
  backend.Synchronize(queue);
  const auto pool_after_repeat = vllm::Pool(backend).stats();
  CHECK(backend.allocations() == after_warmup);
  CHECK(pool_after_repeat.misses == pool_after_warmup.misses);
  CHECK(pool_after_repeat.hits > pool_after_warmup.hits);
  CHECK(model.cached_geometry_count() == 1);

  backend.DestroyQueue(queue);
}
