// Ported from deepseek-ai/DeepSeek-V4-Flash-Vision-Exp
// inference/vision.py at revision
// 86f746b36186f0e567729a5c06a8c918caba82a9. The committed stage goldens were
// generated by scripts/gen-deepseek-v4-vision-goldens.py with torch 2.11.0.
#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <functional>
#include <limits>
#include <memory>
#include <string>
#include <utility>
#include <vector>

#include <nlohmann/json.hpp>

#include "doctest/doctest.h"
#include "vllm/model_executor/models/deepseek_v4_vision.h"
#include "vllm/model_executor/models/dense_device_glue.h"
#include "vllm/model_executor/models/device_pool.h"
#include "vt/dtype.h"

#ifndef DEEPSEEK_V4_VISION_GOLDEN
#error "DEEPSEEK_V4_VISION_GOLDEN must name the committed oracle fixture"
#endif

namespace {

using json = nlohmann::json;
using vllm::dense_attn::DBuf;
using vllm::dense_attn::Dev;
using vllm::multimodal::DeepSeekV4Vision;
using vllm::multimodal::DeepSeekV4VisionBlockWeights;
using vllm::multimodal::DeepSeekV4VisionCapture;
using vllm::multimodal::DeepSeekV4VisionConfig;
using vllm::multimodal::DeepSeekV4VisionRopeCosSin;
using vllm::multimodal::DeepSeekV4VisionWeights;
using vt::Backend;
using vt::DType;
using vt::Queue;
using vt::Tensor;

const json& Goldens() {
  static const json document = [] {
    std::ifstream input(DEEPSEEK_V4_VISION_GOLDEN);
    if (!input) throw std::runtime_error("cannot open DeepSeek-V4 vision golden");
    return json::parse(input);
  }();
  return document;
}

std::vector<float> Floats(const json& values) {
  return values.get<std::vector<float>>();
}

std::vector<uint16_t> Bf16(const json& values) {
  const std::vector<float> floats = Floats(values);
  std::vector<uint16_t> words(floats.size());
  for (size_t i = 0; i < floats.size(); ++i) words[i] = vt::F32ToBF16(floats[i]);
  return words;
}

class TensorStore {
 public:
  TensorStore(Backend& backend, Queue& queue) : dev_{backend, queue} {}

  Tensor Make(const json& values, DType dtype, std::vector<int64_t> shape) {
    if (dtype == DType::kBF16) {
      const std::vector<uint16_t> words = Bf16(values);
      buffers_.push_back(std::make_unique<DBuf>(dev_, dtype, shape, words.data()));
    } else {
      const std::vector<float> floats = Floats(values);
      buffers_.push_back(std::make_unique<DBuf>(dev_, dtype, shape, floats.data()));
    }
    return buffers_.back()->t();
  }

  Tensor Empty(DType dtype, std::vector<int64_t> shape) {
    buffers_.push_back(std::make_unique<DBuf>(dev_, dtype, shape));
    return buffers_.back()->t();
  }

  std::vector<float> Download(const Tensor& tensor) {
    const size_t count = static_cast<size_t>(tensor.Numel());
    std::vector<float> result(count);
    if (tensor.dtype == DType::kBF16) {
      std::vector<uint16_t> words(count);
      dev_.b.Copy(dev_.q, words.data(), tensor.data, words.size() * sizeof(uint16_t));
      dev_.b.Synchronize(dev_.q);
      for (size_t i = 0; i < count; ++i) result[i] = vt::BF16ToF32(words[i]);
    } else {
      dev_.b.Copy(dev_.q, result.data(), tensor.data, result.size() * sizeof(float));
      dev_.b.Synchronize(dev_.q);
    }
    return result;
  }

 private:
  Dev dev_;
  std::vector<std::unique_ptr<DBuf>> buffers_;
};

DeepSeekV4VisionConfig Config(const json& fixture) {
  const json& c = fixture.at("config");
  DeepSeekV4VisionConfig config;
  config.patch_size = c.at("patch_size").get<int64_t>();
  config.hidden_size = c.at("hidden_size").get<int64_t>();
  config.num_heads = c.at("num_heads").get<int64_t>();
  config.depth = c.at("depth").get<int64_t>();
  config.intermediate_size = c.at("intermediate_size").get<int64_t>();
  config.output_size = c.at("output_size").get<int64_t>();
  config.downsample_ratio = c.at("downsample_ratio").get<int64_t>();
  config.norm_epsilon = c.at("norm_epsilon").get<float>();
  config.rope_theta = c.at("rope_theta").get<double>();
  config.compute_dtype = DType::kBF16;
  return config;
}

DeepSeekV4VisionWeights Weights(const json& fixture, const DeepSeekV4VisionConfig& config,
                                TensorStore& store) {
  const json& w = fixture.at("weights");
  const int64_t h = config.hidden_size;
  const int64_t inter = config.intermediate_size;
  const int64_t out = config.output_size;
  DeepSeekV4VisionWeights weights;
  weights.patch_weight = store.Make(w.at("patch_weight"), config.compute_dtype,
                                    {h, config.patch_dim()});
  weights.patch_bias = store.Make(w.at("patch_bias"), config.compute_dtype, {h});
  for (const json& block : w.at("blocks")) {
    DeepSeekV4VisionBlockWeights layer;
    layer.norm1_weight = store.Make(block.at("norm1"), DType::kF32, {h});
    layer.qkv_weight = store.Make(block.at("qkv_weight"), config.compute_dtype,
                                  {3 * h, h});
    layer.qkv_bias = store.Make(block.at("qkv_bias"), config.compute_dtype, {3 * h});
    layer.out_weight = store.Make(block.at("out_weight"), config.compute_dtype, {h, h});
    layer.out_bias = store.Make(block.at("out_bias"), config.compute_dtype, {h});
    layer.norm2_weight = store.Make(block.at("norm2"), DType::kF32, {h});
    layer.mlp_w1_weight = store.Make(block.at("mlp_w1"), config.compute_dtype,
                                     {2 * inter, h});
    layer.mlp_w2_weight = store.Make(block.at("mlp_w2"), config.compute_dtype,
                                     {h, inter});
    weights.blocks.push_back(layer);
  }
  weights.final_norm_weight = store.Make(w.at("final_norm"), DType::kF32, {h});
  weights.aligner_w1_weight = store.Make(w.at("aligner_w1_weight"), config.compute_dtype,
                                         {out, config.aligner_input_size()});
  weights.aligner_w1_bias = store.Make(w.at("aligner_w1_bias"), config.compute_dtype, {out});
  weights.aligner_w2_weight = store.Make(w.at("aligner_w2_weight"), config.compute_dtype,
                                         {out, out});
  weights.aligner_w2_bias = store.Make(w.at("aligner_w2_bias"), config.compute_dtype, {out});
  return weights;
}

// sup|GELU'|, DERIVED rather than sampled. GELU(x) = x*Phi(x), so
// GELU'(x) = Phi(x) + x*phi(x) and GELU''(x) = phi(x) * (2 - x^2), which is zero
// at x = sqrt(2). The supremum is therefore
//   Phi(sqrt2) + sqrt2*phi(sqrt2) = 0.9213503965 + 0.2075516 = 1.1289041452,
// confirmed by a brute-force sweep of [-10, 10] at 1e-5, which peaks at
// x = 1.41421. An earlier value of 1.084 "near x = 1.5216" was wrong twice over:
// it is GELU'(1.0) = 1.0833155, the derivative at 1 rather than at the stationary
// point, and GELU'(1.5216) is 1.1266919, so the stated pair did not even agree
// with itself. The GELU stage can amplify its input's error by up to 12.9% and
// can never be assumed to reduce it, which is what makes a stage bound below its
// input's bound wrong.
constexpr float kGeluLipschitz = 1.1289042f;
// Floor for a case whose input error is zero: our GeluErf and torch F.gelu may
// still differ by one rounding step on identical bf16 input. One bf16 ulp at
// the magnitudes this stage reaches, which is the patch-embedding stage's bound.
constexpr float kGeluErrorFloor = 0.004f;

float MaxAbsDiff(const std::vector<float>& actual, const json& expected_json) {
  const std::vector<float> expected = Floats(expected_json);
  REQUIRE(actual.size() == expected.size());
  float maximum = 0.0f;
  for (size_t i = 0; i < actual.size(); ++i) {
    REQUIRE(std::isfinite(actual[i]));
    maximum = std::max(maximum, std::abs(actual[i] - expected[i]));
  }
  return maximum;
}

class CountingBackend final : public Backend {
 public:
  explicit CountingBackend(Backend& inner) : inner_(inner) {}

  void* Alloc(size_t bytes) override {
    ++allocations_;
    return inner_.Alloc(bytes);
  }
  void Free(void* pointer) override { inner_.Free(pointer); }
  void OnScratchBlockAcquired(void* pointer) override {
    inner_.OnScratchBlockAcquired(pointer);
  }
  void Memset(Queue& queue, void* pointer, int value, size_t bytes) override {
    inner_.Memset(queue, pointer, value, bytes);
  }
  void Copy(Queue& queue, void* destination, const void* source, size_t bytes) override {
    inner_.Copy(queue, destination, source, bytes);
  }
  Queue CreateQueue() override { return inner_.CreateQueue(); }
  void DestroyQueue(Queue& queue) override { inner_.DestroyQueue(queue); }
  void Synchronize(Queue& queue) override { inner_.Synchronize(queue); }
  bool UnifiedMemory() const override { return inner_.UnifiedMemory(); }
  bool DeviceMemoryIsHostAddressable() const override {
    return inner_.DeviceMemoryIsHostAddressable();
  }

  size_t allocations() const { return allocations_; }

 private:
  Backend& inner_;
  size_t allocations_ = 0;
};

struct CaptureTensors {
  explicit CaptureTensors(TensorStore& store, const DeepSeekV4VisionConfig& config,
                          int64_t patch_rows, int64_t output_rows) {
    patch = store.Empty(config.compute_dtype, {patch_rows, config.hidden_size});
    capture.patch_embedding = &patch;
    blocks.reserve(static_cast<size_t>(config.depth));
    capture.block_outputs.reserve(static_cast<size_t>(config.depth));
    for (int64_t i = 0; i < config.depth; ++i) {
      blocks.push_back(store.Empty(config.compute_dtype, {patch_rows, config.hidden_size}));
      capture.block_outputs.push_back(&blocks.back());
    }
    final_norm = store.Empty(config.compute_dtype, {patch_rows, config.hidden_size});
    unfold = store.Empty(config.compute_dtype, {output_rows, config.aligner_input_size()});
    aligner_hidden = store.Empty(config.compute_dtype, {output_rows, config.output_size});
    gelu = store.Empty(config.compute_dtype, {output_rows, config.output_size});
    capture.final_norm = &final_norm;
    capture.aligner_unfold = &unfold;
    capture.aligner_hidden = &aligner_hidden;
    capture.aligner_gelu = &gelu;
  }

  DeepSeekV4VisionCapture capture;
  Tensor patch;
  std::vector<Tensor> blocks;
  Tensor final_norm;
  Tensor unfold;
  Tensor aligner_hidden;
  Tensor gelu;
};

}  // namespace

TEST_CASE("DeepSeek-V4 vision goldens pin the model-author source") {
  const json& document = Goldens();
  CHECK(document.at("oracle") == "deepseek-ai/DeepSeek-V4-Flash-Vision-Exp");
  CHECK(document.at("revision") == "86f746b36186f0e567729a5c06a8c918caba82a9");
  CHECK(document.at("source") == "inference/vision.py");
  CHECK(document.at("torch_version") == "2.11.0+cu130");
}

TEST_CASE("DeepSeek-V4 2-D RoPE keeps height then width frequencies") {
  for (const json& fixture : Goldens().at("fixtures")) {
    const DeepSeekV4VisionConfig config = Config(fixture);
    for (const json& test_case : fixture.at("cases")) {
      const int64_t height = test_case.at("grid").at(0).get<int64_t>();
      const int64_t width = test_case.at("grid").at(1).get<int64_t>();
      std::vector<float> cosine;
      std::vector<float> sine;
      DeepSeekV4VisionRopeCosSin(height, width, config, &cosine, &sine);
      CAPTURE(fixture.at("name"));
      CAPTURE(test_case.at("name"));
      CHECK(MaxAbsDiff(cosine, test_case.at("expected").at("rope_cos")) <= 2.0e-6f);
      CHECK(MaxAbsDiff(sine, test_case.at("expected").at("rope_sin")) <= 2.0e-6f);
    }
  }
}

TEST_CASE("DeepSeek-V4 ViT and aligner match pinned BF16 stage goldens") {
  Backend& backend = vt::GetBackend(vt::DeviceType::kCPU);
  Queue queue = backend.CreateQueue();
  for (const json& fixture : Goldens().at("fixtures")) {
    const DeepSeekV4VisionConfig config = Config(fixture);
    TensorStore store(backend, queue);
    DeepSeekV4Vision model(backend, config, Weights(fixture, config, store));
    CHECK(model.config().depth == config.depth);
    for (const json& test_case : fixture.at("cases")) {
      const int64_t height = test_case.at("grid").at(0).get<int64_t>();
      const int64_t width = test_case.at("grid").at(1).get<int64_t>();
      const int64_t patch_rows = height * width;
      const int64_t output_rows = config.aligned_rows(height, width);
      Tensor patches = store.Make(test_case.at("patches"), config.compute_dtype,
                                  {patch_rows, config.patch_dim()});
      Tensor output = store.Empty(config.compute_dtype, {output_rows, config.output_size});
      CaptureTensors captures(store, config, patch_rows, output_rows);
      model.Forward(queue, output, patches, height, width, &captures.capture);

      const json& expected = test_case.at("expected");
      CAPTURE(fixture.at("name"));
      CAPTURE(test_case.at("name"));
      CHECK(MaxAbsDiff(store.Download(captures.patch), expected.at("patch_embedding")) <= 0.004f);
      for (int64_t layer = 0; layer < config.depth; ++layer) {
        CAPTURE(layer);
        CHECK(MaxAbsDiff(store.Download(captures.blocks[static_cast<size_t>(layer)]),
                         expected.at("blocks").at(static_cast<size_t>(layer))) <= 0.01f);
      }
      CHECK(MaxAbsDiff(store.Download(captures.final_norm), expected.at("vision")) <= 0.024f);
      CHECK(MaxAbsDiff(store.Download(captures.unfold), expected.at("unfold")) <= 0.024f);
      const float aligner_hidden_diff = MaxAbsDiff(
          store.Download(captures.aligner_hidden), expected.at("aligner_hidden"));
      CHECK(aligner_hidden_diff <= 0.016f);
      // THE GELU BOUND IS DERIVED FROM ITS INPUT, not declared beside it.
      //
      // A declared 0.01f here was LOWER than the 0.016f allowed for the
      // aligner_hidden buffer that feeds this stage, and that ordering is not
      // derivable: sup|GELU'| is about 1.0839 (at x about 1.5216), so GELU can
      // amplify the error it is handed by about 8.4% and can never be relied on
      // to shrink it. The declared value held only because the first two
      // fixtures happened to hand it half their allowance, and heads4_depth1
      // already ran at 0.015625 against 0.016, one bf16 ulp from failing.
      //
      // Measured on the fixture set, per case, aligner_hidden -> gelu:
      //   heads2_depth2 2x5              0.0078125  -> 0.0078125
      //   heads2_depth2 3x3              0.0078125  -> 0.0078125
      //   heads4_depth1 3x4              0.015625   -> 0.00878906
      //   heads1_headdim16 4x5           0.0078125  -> 0.00390625
      //   heads1_headdim16 7x4           0.0136719  -> 0.0117188
      // Every case ATTENUATES, and no case reaches the Lipschitz ceiling.
      // aligner_hidden keeps its own absolute cap above, so this stage stays
      // transitively bounded at 0.016f * kGeluLipschitz = 0.0180625f rather than
      // floating free.
      //
      // THIS BOUND IS PARTLY A WIDENING, and saying otherwise was the defect a
      // fresh review found. Against the 0.01f it replaced it is tighter for the
      // three cases at 0.0078125 (0.008820) and LOOSER for the two above them:
      // 0.015625 -> 0.017639 (+76%) and 0.0136719 -> 0.015434 (+54%). The
      // widening is not free. A GELU that scales its output by 1.004f -- one
      // bf16 ulp at these magnitudes -- when and only when it is called on more
      // than one row is a REAL defect, it is fully green here, and under the old
      // 0.01f it reds `heads4_depth1 / 3x4` as well as the case below.
      //
      // The widening is kept because a stage bound BELOW its own input's bound
      // is not derivable and the `heads1_headdim16_theta7919 / 7x4` fixture is
      // handed 0.0136719 by `aligner_hidden`. What pays for it is the exact-erf
      // probe further down, which now runs at more than one row and compares
      // BIT-EXACTLY, so that mutation is caught where it belongs -- on the GELU
      // itself rather than on a fixture's leftover error budget.
      CHECK(MaxAbsDiff(store.Download(captures.gelu), expected.at("gelu")) <=
            std::max(kGeluErrorFloor, kGeluLipschitz * aligner_hidden_diff));
      CHECK(MaxAbsDiff(store.Download(output), expected.at("output")) <= 0.01f);
      CHECK(output.dtype == DType::kBF16);
      CHECK(output.IsContiguous());
    }
  }
  backend.DestroyQueue(queue);
}

TEST_CASE("DeepSeek-V4 aligner preserves F.unfold channel-major order and zero padding") {
  Backend& backend = vt::GetBackend(vt::DeviceType::kCPU);
  Queue queue = backend.CreateQueue();
  const json& fixture = Goldens().at("fixtures").at(0);
  const DeepSeekV4VisionConfig config = Config(fixture);
  TensorStore store(backend, queue);
  DeepSeekV4Vision model(backend, config, Weights(fixture, config, store));
  const int64_t height = 2;
  const int64_t width = 5;
  const int64_t patch_rows = height * width;
  const int64_t output_rows = config.aligned_rows(height, width);
  std::vector<float> source(static_cast<size_t>(patch_rows * config.hidden_size));
  for (size_t i = 0; i < source.size(); ++i) {
    source[i] = static_cast<float>(i + 1);
  }
  Tensor vision = store.Make(json(source), config.compute_dtype,
                             {patch_rows, config.hidden_size});
  Tensor output = store.Empty(config.compute_dtype,
                              {output_rows, config.output_size});
  Tensor unfold = store.Empty(config.compute_dtype,
                              {output_rows, config.aligner_input_size()});
  DeepSeekV4VisionCapture capture;
  capture.aligner_unfold = &unfold;
  model.AlignerForward(queue, output, vision, height, width, &capture);
  const std::vector<float> actual = store.Download(unfold);

  std::vector<float> expected;
  expected.reserve(actual.size());
  const int64_t ratio = config.downsample_ratio;
  for (int64_t block_row = 0; block_row < (height + ratio - 1) / ratio;
       ++block_row) {
    for (int64_t block_column = 0;
         block_column < (width + ratio - 1) / ratio; ++block_column) {
      for (int64_t channel = 0; channel < config.hidden_size; ++channel) {
        for (int64_t local_row = 0; local_row < ratio; ++local_row) {
          for (int64_t local_column = 0; local_column < ratio; ++local_column) {
            const int64_t row = block_row * ratio + local_row;
            const int64_t column = block_column * ratio + local_column;
            expected.push_back(
                row < height && column < width
                    ? source[static_cast<size_t>((row * width + column) *
                                                 config.hidden_size + channel)]
                    : 0.0f);
          }
        }
      }
    }
  }
  CHECK(actual == expected);
  const size_t second_block = static_cast<size_t>(config.aligner_input_size());
  CHECK(actual[second_block + 2] == 0.0f);
  CHECK(actual[second_block + 5] == 0.0f);
  CHECK(actual[second_block + 8] == 0.0f);
  CHECK(actual[6] == 0.0f);
  backend.DestroyQueue(queue);
}

// AT ONE ROW AND AT MORE THAN ONE, because a GELU defect can be confined to
// either and this probe is the only BIT-EXACT observable on the activation.
//
// `vt::GeluErf`'s CPU kernel splits its work by ROW (`ParallelForRows` in
// `src/vt/cpu/cpu_layernorm.cpp`), so a defect that fires only when `rows > 1`
// never enters a single-row probe. A fresh review scaled that kernel's output by
// 1.004f -- one bf16 ulp at the magnitudes this stage reaches -- under exactly
// that condition, and the whole suite stayed green at 15 of 15 cases and 7404 of
// 7404 assertions: the probe above never took the branch, and the stage goldens
// carry a per-case tolerance derived from their own input error, which at two of
// the five cases is wider than the defect. That widening is argued where it is
// declared; this case is what pays for it.
//
// The grid is chosen for the ROW COUNT rather than for the geometry:
// `aligned_rows(downsample_ratio + 1, 1)` is 2, and `aligner_w1` is zeroed, so
// every output row is the same bias vector and must carry the same exact-erf
// answer to the bit.
TEST_CASE("DeepSeek-V4 aligner uses exact erf GELU") {
  Backend& backend = vt::GetBackend(vt::DeviceType::kCPU);
  Queue queue = backend.CreateQueue();
  const json& fixture = Goldens().at("fixtures").at(0);
  const json& probe = Goldens().at("gelu_probe");
  const DeepSeekV4VisionConfig config = Config(fixture);
  TensorStore store(backend, queue);
  DeepSeekV4VisionWeights weights = Weights(fixture, config, store);
  const std::vector<float> zeros(
      static_cast<size_t>(config.output_size * config.aligner_input_size()),
      0.0f);
  weights.aligner_w1_weight =
      store.Make(json(zeros), config.compute_dtype,
                 {config.output_size, config.aligner_input_size()});
  weights.aligner_w1_bias =
      store.Make(probe.at("input"), config.compute_dtype, {config.output_size});
  DeepSeekV4Vision model(backend, config, std::move(weights));

  const std::vector<float> input = Floats(probe.at("input"));
  const std::vector<float> expected = Floats(probe.at("expected"));
  const auto probe_at = [&](int64_t height, int64_t width) {
    const int64_t rows = config.aligned_rows(height, width);
    const int64_t tokens = height * width;
    CAPTURE(rows);
    const std::vector<float> vision_zeros(
        static_cast<size_t>(tokens * config.hidden_size), 0.0f);
    Tensor vision = store.Make(json(vision_zeros), config.compute_dtype,
                               {tokens, config.hidden_size});
    Tensor output =
        store.Empty(config.compute_dtype, {rows, config.output_size});
    Tensor hidden =
        store.Empty(config.compute_dtype, {rows, config.output_size});
    Tensor gelu = store.Empty(config.compute_dtype, {rows, config.output_size});
    DeepSeekV4VisionCapture capture;
    capture.aligner_hidden = &hidden;
    capture.aligner_gelu = &gelu;
    model.AlignerForward(queue, output, vision, height, width, &capture);

    std::vector<float> input_rows;
    std::vector<float> expected_rows;
    for (int64_t r = 0; r < rows; ++r) {
      input_rows.insert(input_rows.end(), input.begin(), input.end());
      expected_rows.insert(expected_rows.end(), expected.begin(),
                           expected.end());
    }
    CHECK(store.Download(hidden) == input_rows);
    CHECK(store.Download(gelu) == expected_rows);
  };
  probe_at(1, 1);
  REQUIRE(config.aligned_rows(config.downsample_ratio + 1, 1) > 1);
  probe_at(config.downsample_ratio + 1, 1);
  backend.DestroyQueue(queue);
}

TEST_CASE("DeepSeek-V4 vision rejects invalid geometry dtype layout and weights") {
  Backend& backend = vt::GetBackend(vt::DeviceType::kCPU);
  Queue queue = backend.CreateQueue();
  const json& fixture = Goldens().at("fixtures").at(0);
  DeepSeekV4VisionConfig config = Config(fixture);
  TensorStore store(backend, queue);

  SUBCASE("head geometry") {
    config.hidden_size = 10;
    config.num_heads = 2;
    CHECK_THROWS_WITH_AS(DeepSeekV4Vision(backend, config, {}),
                         "DeepSeek-V4 vision head dimension must be divisible by four",
                         std::invalid_argument);
  }
  SUBCASE("depth") {
    DeepSeekV4VisionWeights weights = Weights(fixture, config, store);
    weights.blocks.pop_back();
    CHECK_THROWS_WITH_AS(DeepSeekV4Vision(backend, config, std::move(weights)),
                         "DeepSeek-V4 vision block count does not match depth",
                         std::invalid_argument);
  }
  SUBCASE("unsupported dtype") {
    config.compute_dtype = DType::kF16;
    CHECK_THROWS_WITH_AS(DeepSeekV4Vision(backend, config, {}),
                         "DeepSeek-V4 vision compute dtype must be bf16",
                         std::invalid_argument);
  }
  SUBCASE("input and output contracts") {
    DeepSeekV4Vision model(backend, config, Weights(fixture, config, store));
    const json& test_case = fixture.at("cases").at(0);
    Tensor patches = store.Make(test_case.at("patches"), config.compute_dtype,
                                {10, config.patch_dim()});
    Tensor output = store.Empty(config.compute_dtype, {2, config.output_size});
    Tensor wrong_rows = patches;
    wrong_rows.shape[0] = 9;
    CHECK_THROWS_WITH_AS(model.Forward(queue, output, wrong_rows, 2, 5),
                         "DeepSeek-V4 vision patches must be [height*width, patch_dim]",
                         std::invalid_argument);
    Tensor strided = patches;
    strided.stride[0] += 1;
    CHECK_THROWS_WITH_AS(model.Forward(queue, output, strided, 2, 5),
                         "DeepSeek-V4 vision patches must be contiguous",
                         std::invalid_argument);
    Tensor wrong_dtype = store.Empty(DType::kF32, {2, config.output_size});
    CHECK_THROWS_WITH_AS(model.Forward(queue, wrong_dtype, patches, 2, 5),
                         "DeepSeek-V4 vision output dtype must equal model dtype",
                         std::invalid_argument);
    CHECK_THROWS_WITH_AS(model.Forward(queue, output, patches, 0, 5),
                         "DeepSeek-V4 vision grid dimensions must be positive",
                         std::invalid_argument);
  }
  backend.DestroyQueue(queue);
}

TEST_CASE("DeepSeek-V4 repeated shape reuses scratch and 2-D RoPE allocation") {
  Backend& inner = vt::GetBackend(vt::DeviceType::kCPU);
  CountingBackend backend(inner);
  vllm::Pool(backend).Drain(backend);
  Queue queue = backend.CreateQueue();
  const json& fixture = Goldens().at("fixtures").at(0);
  const json& test_case = fixture.at("cases").at(0);
  const DeepSeekV4VisionConfig config = Config(fixture);
  TensorStore store(backend, queue);
  DeepSeekV4Vision model(backend, config, Weights(fixture, config, store));
  Tensor patches = store.Make(test_case.at("patches"), config.compute_dtype,
                              {10, config.patch_dim()});
  Tensor output = store.Empty(config.compute_dtype, {2, config.output_size});

  model.Forward(queue, output, patches, 2, 5);
  backend.Synchronize(queue);
  const size_t after_warmup = backend.allocations();
  const auto pool_after_warmup = vllm::Pool(backend).stats();
  CHECK(model.cached_geometry_count() == 1);

  model.Forward(queue, output, patches, 2, 5);
  backend.Synchronize(queue);
  const auto pool_after_repeat = vllm::Pool(backend).stats();
  CHECK(backend.allocations() == after_warmup);
  CHECK(pool_after_repeat.misses == pool_after_warmup.misses);
  CHECK(pool_after_repeat.hits > pool_after_warmup.hits);
  CHECK(model.cached_geometry_count() == 1);

  backend.DestroyQueue(queue);
}

// W2 repair, F2 (#2411). A REDUCED FIXTURE CAN DEGENERATE THE AXIS IT GATES.
//
// get_vision_cos_sin builds inv_freq[i] = theta ** -(2i / rope_dim) for
// i in [0, rope_dim/2), and at rope_dim 2 that set is the single element
// theta ** -0 = 1.0 FOR EVERY THETA. The first two fixtures are head_dim 4, so
// both were in exactly that state: pinning rope_theta to a literal 10000.0 and
// halving the exponent denominator each left every golden byte unchanged.
// Production is head_dim 64, i.e. 16 frequencies.
//
// This case fails if the fixture set ever loses the geometry that makes those
// two mutations observable, so the coverage cannot be removed silently.
TEST_CASE("DeepSeek-V4 vision goldens can measure rope_theta and the frequency decay") {
  const DeepSeekV4VisionConfig defaults;
  REQUIRE(defaults.rope_theta == 10000.0);

  int measuring_fixtures = 0;
  for (const json& fixture : Goldens().at("fixtures")) {
    const DeepSeekV4VisionConfig config = Config(fixture);
    const int64_t frequencies = config.head_dim() / 4;
    // One frequency means every exponent is 0, so theta cancels entirely.
    // Two or more make theta and the denominator both observable; require four
    // so the decay is a curve rather than a single ratio.
    if (frequencies >= 4 && config.rope_theta != defaults.rope_theta) {
      ++measuring_fixtures;
      CAPTURE(fixture.at("name"));
      // Prove the frequencies really do differ from each other at this
      // geometry: an equal set would cancel the decay law again.
      std::vector<float> cosine;
      std::vector<float> sine;
      DeepSeekV4VisionRopeCosSin(1, 2, config, &cosine, &sine);
      const int64_t rope_width = config.head_dim() / 2;
      // Token 1 is (row 0, column 1), so its WIDTH half carries position 1 and
      // its values are cos(inv_freq[i]) across the frequency ladder.
      const size_t width_half = static_cast<size_t>(rope_width + frequencies);
      CHECK(cosine[width_half + 0] != cosine[width_half + 1]);
      CHECK(cosine[width_half + 1] != cosine[width_half + 2]);
      CHECK(cosine[width_half + 2] != cosine[width_half + 3]);
    }
  }
  CHECK(measuring_fixtures >= 1);
}

// W2 repair, F3 (#2411). The same degeneracy on the aligner's ROW ORDER.
//
// Every original fixture grid ((2,5), (3,3), (3,4)) aligns to ONE merged row at
// downsample_ratio 3, and with block_rows == 1 a row-major and a column-major
// walk of the merged grid are the same sequence. Swapping the two loops was
// therefore invisible, although the order fixes the spatial arrangement of the
// image tokens W4 hands the language model: a 448x448 image is a 32x32 patch
// grid, 11x11 merged, and would emit transposed rows with the token count, the
// dtype and every golden unchanged.
TEST_CASE("DeepSeek-V4 vision goldens can measure the aligner row order") {
  int measuring_cases = 0;
  for (const json& fixture : Goldens().at("fixtures")) {
    const DeepSeekV4VisionConfig config = Config(fixture);
    const int64_t ratio = config.downsample_ratio;
    for (const json& test_case : fixture.at("cases")) {
      const int64_t height = test_case.at("grid").at(0).get<int64_t>();
      const int64_t width = test_case.at("grid").at(1).get<int64_t>();
      const int64_t block_rows = 1 + (height - 1) / ratio;
      const int64_t block_columns = 1 + (width - 1) / ratio;
      if (block_rows > 1 && block_columns > 1) ++measuring_cases;
    }
  }
  CHECK(measuring_cases >= 1);
}

// W2 repair, F3 (#2411). The row order itself, at a merged grid that can show it
// and WITHOUT rebuilding the expectation from the implementation's own loop
// nesting.
//
// The dedicated unfold case above walks block_row then block_column exactly as
// the implementation does, so on this axis it is a tautology and cannot rescue
// the order. This one takes the destination row index from the SECONDARY ORACLE
// instead. llama.cpp release `b10766` = `9400c8946e4da5e7694f2c26d6d4e50e14b690fa`
// (oracle `llama-cpp-dsv4vision`) builds the same 3x3 patch merge and then maps
// merged cell (row r, column c) to aligner output row `r * n_llm_w + c` in
// `clip.cpp`'s `set_input` for `PROJECTOR_TYPE_DEEPSEEK4V`. Its graph in
// `tools/mtmd/models/deepseek4v.cpp` (blob `ffe8f59d9997` at that pin) reaches
// the same order through `ggml_im2col` over a [x, y, n_embd] tensor reshaped
// `[ne0, ne1*ne2]`, which flattens [OW, OH] with OW fastest.
//
// So the merged grid is ROW-MAJOR, our loop nesting is right, and this case
// exists to hold it rather than to change it.
TEST_CASE("DeepSeek-V4 aligner emits merged cells in llama.cpp row-major order") {
  Backend& backend = vt::GetBackend(vt::DeviceType::kCPU);
  Queue queue = backend.CreateQueue();
  const json& fixture = Goldens().at("fixtures").at(0);
  const DeepSeekV4VisionConfig config = Config(fixture);
  TensorStore store(backend, queue);
  DeepSeekV4Vision model(backend, config, Weights(fixture, config, store));

  // 7x4 merges to 3x2 at ratio 3: both dimensions exceed one and they differ,
  // so a transposed walk is a genuine permutation and not a relabelling.
  const int64_t height = 7;
  const int64_t width = 4;
  const int64_t ratio = config.downsample_ratio;
  const int64_t hidden = config.hidden_size;
  const int64_t merged_rows = 1 + (height - 1) / ratio;
  const int64_t merged_columns = 1 + (width - 1) / ratio;
  REQUIRE(merged_rows == 3);
  REQUIRE(merged_columns == 2);

  const int64_t patch_rows = height * width;
  const int64_t output_rows = config.aligned_rows(height, width);
  REQUIRE(output_rows == merged_rows * merged_columns);

  // Every element gets its own value. The largest is 7*4*8 = 224, and every
  // integer up to 256 is exact in bf16, so nothing here is a rounding artefact.
  std::vector<float> source(static_cast<size_t>(patch_rows * hidden));
  for (size_t i = 0; i < source.size(); ++i) source[i] = static_cast<float>(i + 1);
  REQUIRE(source.back() <= 256.0f);

  Tensor vision = store.Make(json(source), config.compute_dtype, {patch_rows, hidden});
  Tensor output = store.Empty(config.compute_dtype, {output_rows, config.output_size});
  Tensor unfold = store.Empty(config.compute_dtype,
                              {output_rows, config.aligner_input_size()});
  DeepSeekV4VisionCapture capture;
  capture.aligner_unfold = &unfold;
  model.AlignerForward(queue, output, vision, height, width, &capture);
  const std::vector<float> actual = store.Download(unfold);
  const int64_t unfold_width = config.aligner_input_size();

  for (int64_t merged_row = 0; merged_row < merged_rows; ++merged_row) {
    for (int64_t merged_column = 0; merged_column < merged_columns;
         ++merged_column) {
      // The oracle's index, not ours: r * n_llm_w + c.
      const int64_t destination = merged_row * merged_columns + merged_column;
      CAPTURE(merged_row);
      CAPTURE(merged_column);
      CAPTURE(destination);
      for (int64_t channel = 0; channel < hidden; ++channel) {
        for (int64_t local_row = 0; local_row < ratio; ++local_row) {
          for (int64_t local_column = 0; local_column < ratio; ++local_column) {
            const int64_t row = merged_row * ratio + local_row;
            const int64_t column = merged_column * ratio + local_column;
            const float expected =
                row < height && column < width
                    ? source[static_cast<size_t>((row * width + column) * hidden +
                                                 channel)]
                    : 0.0f;
            const size_t offset = static_cast<size_t>(
                destination * unfold_width + channel * ratio * ratio +
                local_row * ratio + local_column);
            REQUIRE(actual[offset] == expected);
          }
        }
      }
    }
  }
  backend.DestroyQueue(queue);
}

// W2 repair, F4 (#2411). THE MEMORY FORMAT OF THE MODEL PATH.
//
// AGENTS.md, "Inherit vLLM defaults": a token gate CANNOT detect a dtype that is
// too wide. Widening the attention-output buffer to f32 left every stage golden
// green, because `vt::MatmulBT` and `vt::Add` accept the mix and the VALUES are
// unchanged while the path moves twice the bytes. This case reads the dtypes the
// forward actually allocated, so the width is asserted rather than assumed.
//
// The two f32 entries are the documented exceptions and keep their reason: the
// pinned `apply_rotary` widens q and k before multiplying by its f32 cos/sin
// table and narrows once afterward. The RoPE cos/sin cache itself is f32 for the
// same reason and lives in the geometry cache, not in this per-call list.
//
// THE RECORDED LIST ALONE IS A HAND-MAINTAINED MIRROR, and a fresh review proved
// it cannot see the defect it was written for. `RecordScratch` is called by hand
// at each allocation site, so a buffer that calls it is described and a buffer
// that does not is invisible: the review hoisted an f32 attention buffer and
// round-tripped the attention output through `CastF32`/`CastBf16` -- identical
// values, twice the bytes on the model path -- WITHOUT a `RecordScratch` call,
// and the whole suite stayed green at 15 of 15 cases and 7407 of 7407
// assertions. `f32_entries == 2` counts recorded entries only, and the pool
// slope case below measures traffic per layer, which a hoisted buffer does not
// change.
//
// So the list is bounded by something the code cannot drift from: the BYTES the
// pool hands this forward. Every `DBuf` in the forward comes from
// `vllm::Pool(backend)`, recorded or not, so one Forward from a drained pool
// prices the whole model path in one number. Measured on this tree at this
// fixture, 13 driver allocations totalling 2680 class-rounded bytes; under the
// review's mutation, 14 and 3000. The bound is stated as a CAP rather than an
// equality because a pool block is class-rounded and an unrelated backend may
// serve the same forward from fewer blocks, while every way of widening the
// model path can only push it up.
//
// If this cap reds, the forward's scratch footprint changed. Find which buffer
// and why before touching the number: re-baselining it is how the mirror above
// stopped measuring anything.
TEST_CASE("DeepSeek-V4 vision keeps the model path bf16 except the rotary scratch") {
  Backend& backend = vt::GetBackend(vt::DeviceType::kCPU);
  Queue queue = backend.CreateQueue();
  const json& fixture = Goldens().at("fixtures").at(0);
  const json& test_case = fixture.at("cases").at(0);
  const DeepSeekV4VisionConfig config = Config(fixture);
  TensorStore store(backend, queue);
  DeepSeekV4Vision model(backend, config, Weights(fixture, config, store));
  Tensor patches = store.Make(test_case.at("patches"), config.compute_dtype,
                              {10, config.patch_dim()});
  Tensor output = store.Empty(config.compute_dtype, {2, config.output_size});

  std::vector<vllm::multimodal::DeepSeekV4VisionScratchDType> scratch;
  DeepSeekV4VisionCapture capture;
  capture.scratch_dtypes = &scratch;

  // Drain AFTER the weights are staged so the reading covers the forward only,
  // exactly as the pool-slope case below does.
  vllm::Pool(backend).Drain(backend);
  const auto pool_before = vllm::Pool(backend).stats();
  model.Forward(queue, output, patches, 2, 5, &capture);
  backend.Synchronize(queue);
  const auto pool_after = vllm::Pool(backend).stats();

  const std::vector<std::pair<std::string, DType>> expected = {
      {"vision.hidden_state", DType::kBF16},
      {"vision.normalized", DType::kBF16},
      {"vision.query", DType::kBF16},
      {"vision.key", DType::kBF16},
      {"vision.value", DType::kBF16},
      {"vision.attention", DType::kBF16},
      {"vision.projected", DType::kBF16},
      {"vision.rope_query_f32", DType::kF32},
      {"vision.rope_key_f32", DType::kF32},
      {"vision.mlp_gate_up_activated", DType::kBF16},
      // `Forward`'s own buffer, recorded between the stages. See the capture
      // struct's comment for why it is not first.
      {"forward.vision", DType::kBF16},
      {"aligner.padded", DType::kBF16},
      {"aligner.unfolded", DType::kBF16},
      {"aligner.hidden_state", DType::kBF16},
  };
  REQUIRE(scratch.size() == expected.size());
  int f32_entries = 0;
  for (size_t i = 0; i < expected.size(); ++i) {
    CAPTURE(i);
    CAPTURE(expected[i].first);
    REQUIRE(scratch[i].name != nullptr);
    CHECK(std::string(scratch[i].name) == expected[i].first);
    CHECK(scratch[i].dtype == expected[i].second);
    if (scratch[i].dtype == DType::kF32) ++f32_entries;
  }
  // Stated from the other end: exactly two recorded f32 entries, and both are
  // the rotary pair. This holds the list it can see; the cap below is what holds
  // the buffers it cannot.
  CHECK(f32_entries == 2);
  CHECK(model.config().compute_dtype == DType::kBF16);

  // One Forward, priced in driver allocations and in bytes. See the header.
  constexpr uint64_t kForwardDriverAllocations = 13;
  constexpr size_t kForwardPoolBytes = 2680;
  CHECK(pool_after.misses - pool_before.misses <= kForwardDriverAllocations);
  CHECK(pool_after.retained_bytes - pool_before.retained_bytes <=
        kForwardPoolBytes);
  backend.DestroyQueue(queue);
}

// W2 repair, F5 (#2411). PER-LAYER SCRATCH IS HOISTED, and that is now measured
// at the only observable that can see it.
//
// The allocation case above compares driver Alloc counts and pool statistics
// across TWO Forward calls at one shape. A per-layer pooled Get/Put inside a
// single call reuses the same warm block, so moving a buffer into the block loop
// changes neither, and it stayed green. Measured on this tree, one Forward from
// a drained pool, hoisted against un-hoisted:
//
//   depth 2   17 gets (13 misses, 4 hits)   vs   18 gets (13 misses,  5 hits)
//   depth 4   21 gets (13 misses, 8 hits)   vs   24 gets (13 misses, 11 hits)
//   depth 8   29 gets (13 misses, 16 hits)  vs   36 gets (13 misses, 23 hits)
//
// `misses` is 13 in BOTH forms at every depth, so bounding misses alone cannot
// see this defect: the fixed working set is the same either way and the pool
// serves every extra request from its own free list. What separates them is the
// pool GET traffic PER LAYER, which is 2 hoisted and 3 un-hoisted. At the
// production depth of 32 the un-hoisted form is 32 extra pool round trips per
// image, invisibly.
//
// The slope is 2 because the shared MlpGateUpMethodBase seam legitimately owns
// two per-layer buffers, the merged gate_up output and the activation it returns
// (`UnquantizedMlpGateUpMethod::Apply`). Everything this file allocates is
// hoisted, so it contributes 0 to the slope.
TEST_CASE("DeepSeek-V4 vision allocates no per-layer scratch of its own") {
  // The two per-layer buffers the shared MLP seam owns, and nothing else.
  constexpr uint64_t kPerLayerPooledBuffers = 2;

  Backend& inner = vt::GetBackend(vt::DeviceType::kCPU);
  CountingBackend backend(inner);
  Queue queue = backend.CreateQueue();
  const json& fixture = Goldens().at("fixtures").at(0);
  const json& test_case = fixture.at("cases").at(0);

  struct Reading {
    uint64_t gets = 0;
    uint64_t misses = 0;
  };
  auto measure = [&](int64_t depth) {
    DeepSeekV4VisionConfig config = Config(fixture);
    TensorStore store(backend, queue);
    DeepSeekV4VisionWeights weights = Weights(fixture, config, store);
    while (static_cast<int64_t>(weights.blocks.size()) < depth) {
      weights.blocks.push_back(weights.blocks[0]);
    }
    config.depth = depth;
    DeepSeekV4Vision model(backend, config, std::move(weights));
    Tensor patches = store.Make(test_case.at("patches"), config.compute_dtype,
                                {10, config.patch_dim()});
    Tensor output = store.Empty(config.compute_dtype, {2, config.output_size});
    // Drain AFTER the weights are staged so the reading covers the forward only.
    vllm::Pool(backend).Drain(backend);
    const auto before = vllm::Pool(backend).stats();
    model.Forward(queue, output, patches, 2, 5);
    backend.Synchronize(queue);
    const auto after = vllm::Pool(backend).stats();
    Reading reading;
    reading.misses = after.misses - before.misses;
    reading.gets = reading.misses + (after.hits - before.hits);
    return reading;
  };

  const int64_t shallow = Config(fixture).depth;
  REQUIRE(shallow >= 1);
  const Reading at_shallow = measure(shallow);
  const Reading at_deep = measure(2 * shallow);

  // The fixed working set does not scale with depth. This is the bound the
  // review asked for, and it holds; it is kept because it is true and useful,
  // not because it can see the defect below.
  CHECK(at_deep.misses == at_shallow.misses);

  // The bound that CAN see it: pool traffic per layer.
  REQUIRE(at_deep.gets >= at_shallow.gets);
  const uint64_t per_layer =
      (at_deep.gets - at_shallow.gets) / static_cast<uint64_t>(shallow);
  CHECK(per_layer == kPerLayerPooledBuffers);
  // Exactly divisible, so the slope is a real per-layer count and not a rounded
  // one.
  CHECK((at_deep.gets - at_shallow.gets) %
            static_cast<uint64_t>(shallow) == 0);

  backend.DestroyQueue(queue);
}

// W2 repair, F7 (#2411). THE BORROW MUST NOT DROP THE REPACK MARKERS.
//
// `BorrowResidentWeight` hands each block's gate-up weight to the shared
// MlpGateUpMethodBase seam as an OwnedTensor. It copied dtype, rank, shape, `nk`,
// bytes and `d_dev` and stopped there, so `repacked`, `q8_0_aligned` and
// `elem_kn_repacked` were lost. Those three say the BYTES were rewritten at load
// into a different block interleave or orientation while the byte count and the
// [N,K] shape stayed the same, so nothing downstream can notice: `ValidateTensor`
// does not check them and no value gate can see them.
//
// THIS IS THE SAME DEFECT `main` FIXED AT `7a937db8a` (#2031), in the shared
// `dense_attn::ResidentWeight`, re-introduced in a private helper. There it cost
// a debugging campaign: an i8mm-interleaved `block_q8_0x4` buffer (136-byte
// blocks) reached the quant GEMM flagged as flat `q8_0` (34-byte blocks) and
// decoded to NaN, then all-zero logits, then token id 0, with nothing logged
// because the `lm_head` GEMM swallowed the NaN.
//
// It is HOST-CONDITIONAL: `vt::cpu::QuantRepackActive()` is true only on an
// aarch64 i8mm host, so this x86 box can never show it as a wrong number. That is
// exactly why the markers are asserted structurally instead. W3A's mmproj reader
// is what turns it from latent into live, because it can now hand this tower
// block-quantized weights.
//
// The forward is deliberately NOT run here. `elem_kn_repacked` claims the bytes
// are physically [K,N], and this fixture's bytes are not, so a forward would read
// a genuinely mislabelled buffer. The markers are metadata and the assertion is
// about whether they survive the borrow.
TEST_CASE("DeepSeek-V4 vision carries the load-time repack markers into the MLP seam") {
  Backend& backend = vt::GetBackend(vt::DeviceType::kCPU);
  Queue queue = backend.CreateQueue();
  const json& fixture = Goldens().at("fixtures").at(0);
  const DeepSeekV4VisionConfig config = Config(fixture);
  REQUIRE(config.depth >= 2);

  SUBCASE("every marker survives, and an unmarked block stays unmarked") {
    TensorStore store(backend, queue);
    DeepSeekV4VisionWeights weights = Weights(fixture, config, store);
    weights.blocks[0].mlp_w1_weight.repacked = true;
    weights.blocks[0].mlp_w1_weight.q8_0_aligned = true;
    weights.blocks[0].mlp_w1_weight.elem_kn_repacked = true;
    DeepSeekV4Vision model(backend, config, std::move(weights));

    const auto marked = model.mlp_gate_up_markers(0);
    CHECK(marked.repacked);
    CHECK(marked.q8_0_aligned);
    CHECK(marked.elem_kn_repacked);

    // Opposite polarity, so a stub that answers true cannot pass either.
    const auto plain = model.mlp_gate_up_markers(1);
    CHECK_FALSE(plain.repacked);
    CHECK_FALSE(plain.q8_0_aligned);
    CHECK_FALSE(plain.elem_kn_repacked);
  }

  SUBCASE("each marker travels on its own") {
    for (int which = 0; which < 3; ++which) {
      CAPTURE(which);
      TensorStore store(backend, queue);
      DeepSeekV4VisionWeights weights = Weights(fixture, config, store);
      if (which == 0) weights.blocks[0].mlp_w1_weight.repacked = true;
      if (which == 1) weights.blocks[0].mlp_w1_weight.q8_0_aligned = true;
      if (which == 2) weights.blocks[0].mlp_w1_weight.elem_kn_repacked = true;
      DeepSeekV4Vision model(backend, config, std::move(weights));
      const auto markers = model.mlp_gate_up_markers(0);
      CHECK(markers.repacked == (which == 0));
      CHECK(markers.q8_0_aligned == (which == 1));
      CHECK(markers.elem_kn_repacked == (which == 2));
    }
  }

  SUBCASE("the accessor refuses a block that does not exist") {
    TensorStore store(backend, queue);
    DeepSeekV4Vision model(backend, config, Weights(fixture, config, store));
    CHECK_THROWS_WITH_AS(model.mlp_gate_up_markers(-1),
                         "DeepSeek-V4 vision block index is out of range",
                         std::invalid_argument);
    CHECK_THROWS_WITH_AS(model.mlp_gate_up_markers(config.depth),
                         "DeepSeek-V4 vision block index is out of range",
                         std::invalid_argument);
  }
  backend.DestroyQueue(queue);
}


// W2 repair, F6 (#2411). THE WEIGHT-SHAPE REFUSALS ARE NOW LOAD-BEARING.
//
// `ValidateWeights` makes fifteen `ValidateTensor` calls and NONE of them was
// exercised. Deleting the `aligner_w2_weight` refusal outright left the suite
// green, and the header's "RMSNorm weights stay f32" claim rested on three
// refusals nothing drove, so relaxing one to accept the model dtype was green
// too. A refusal nothing reaches is not a contract, it is a comment.
//
// One table rather than thirty-five cases, but every row is INDIVIDUALLY
// falsifiable: deleting any one `ValidateTensor` call reds exactly the two rows
// that name it, and relaxing one from f32 to the model dtype reds that tensor's
// dtype row. The dtypes are driven in both directions, a model-dtype weight
// offered as f32 and an f32 norm offered as bf16, so the polarity cannot be
// flipped silently either. Two blocks are covered rather than only block 0,
// because these checks sit inside a loop over every block.
TEST_CASE("DeepSeek-V4 vision refuses every mis-declared weight tensor") {
  Backend& backend = vt::GetBackend(vt::DeviceType::kCPU);
  Queue queue = backend.CreateQueue();
  const json& fixture = Goldens().at("fixtures").at(0);
  const DeepSeekV4VisionConfig config = Config(fixture);
  REQUIRE(config.depth >= 2);

  struct Sizes {
    int64_t h;
    int64_t inter;
    int64_t out;
    int64_t patch_dim;
    int64_t aligner_input;
    DType model;
    DType f32;
  };
  const Sizes z{config.hidden_size,  config.intermediate_size,
                config.output_size,  config.patch_dim(),
                config.aligner_input_size(), config.compute_dtype,
                DType::kF32};

  struct Case {
    const char* label;
    const char* message;
    void (*corrupt)(DeepSeekV4VisionWeights&, TensorStore&, const Sizes&);
  };

  const std::vector<Case> cases = {
      {"patch weight dtype", "DeepSeek-V4 vision patch weight has the wrong dtype",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.patch_weight = s.Empty(z.f32, {z.h, z.patch_dim});
       }},
      {"patch weight shape", "DeepSeek-V4 vision patch weight has the wrong shape",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.patch_weight = s.Empty(z.model, {z.h + 1, z.patch_dim});
       }},
      {"patch bias dtype", "DeepSeek-V4 vision patch bias has the wrong dtype",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.patch_bias = s.Empty(z.f32, {z.h});
       }},
      {"patch bias shape", "DeepSeek-V4 vision patch bias has the wrong shape",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.patch_bias = s.Empty(z.model, {z.h + 1});
       }},
      {"block 0 norm1 dtype", "DeepSeek-V4 vision norm1 weight has the wrong dtype",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.blocks[0].norm1_weight = s.Empty(z.model, {z.h});
       }},
      {"block 0 norm1 shape", "DeepSeek-V4 vision norm1 weight has the wrong shape",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.blocks[0].norm1_weight = s.Empty(z.f32, {z.h + 1});
       }},
      {"block 1 norm1 dtype", "DeepSeek-V4 vision norm1 weight has the wrong dtype",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.blocks[1].norm1_weight = s.Empty(z.model, {z.h});
       }},
      {"block 1 norm1 shape", "DeepSeek-V4 vision norm1 weight has the wrong shape",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.blocks[1].norm1_weight = s.Empty(z.f32, {z.h + 1});
       }},
      {"block 0 qkv weight dtype", "DeepSeek-V4 vision qkv weight has the wrong dtype",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.blocks[0].qkv_weight = s.Empty(z.f32, {3 * z.h, z.h});
       }},
      {"block 0 qkv weight shape", "DeepSeek-V4 vision qkv weight has the wrong shape",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.blocks[0].qkv_weight = s.Empty(z.model, {3 * z.h, z.h + 1});
       }},
      {"block 0 qkv bias dtype", "DeepSeek-V4 vision qkv bias has the wrong dtype",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.blocks[0].qkv_bias = s.Empty(z.f32, {3 * z.h});
       }},
      {"block 0 qkv bias shape", "DeepSeek-V4 vision qkv bias has the wrong shape",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.blocks[0].qkv_bias = s.Empty(z.model, {3 * z.h + 1});
       }},
      {"block 0 attn out weight dtype", "DeepSeek-V4 vision attention output weight has the wrong dtype",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.blocks[0].out_weight = s.Empty(z.f32, {z.h, z.h});
       }},
      {"block 0 attn out weight shape", "DeepSeek-V4 vision attention output weight has the wrong shape",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.blocks[0].out_weight = s.Empty(z.model, {z.h, z.h + 1});
       }},
      {"block 0 attn out bias dtype", "DeepSeek-V4 vision attention output bias has the wrong dtype",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.blocks[0].out_bias = s.Empty(z.f32, {z.h});
       }},
      {"block 0 attn out bias shape", "DeepSeek-V4 vision attention output bias has the wrong shape",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.blocks[0].out_bias = s.Empty(z.model, {z.h + 1});
       }},
      {"block 0 norm2 dtype", "DeepSeek-V4 vision norm2 weight has the wrong dtype",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.blocks[0].norm2_weight = s.Empty(z.model, {z.h});
       }},
      {"block 0 norm2 shape", "DeepSeek-V4 vision norm2 weight has the wrong shape",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.blocks[0].norm2_weight = s.Empty(z.f32, {z.h + 1});
       }},
      {"block 1 MLP w1 dtype", "DeepSeek-V4 vision MLP w1 weight has the wrong dtype",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.blocks[1].mlp_w1_weight = s.Empty(z.f32, {2 * z.inter, z.h});
       }},
      {"block 1 MLP w1 shape", "DeepSeek-V4 vision MLP w1 weight has the wrong shape",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.blocks[1].mlp_w1_weight = s.Empty(z.model, {2 * z.inter, z.h + 1});
       }},
      {"block 0 MLP w2 dtype", "DeepSeek-V4 vision MLP w2 weight has the wrong dtype",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.blocks[0].mlp_w2_weight = s.Empty(z.f32, {z.h, z.inter});
       }},
      {"block 0 MLP w2 shape", "DeepSeek-V4 vision MLP w2 weight has the wrong shape",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.blocks[0].mlp_w2_weight = s.Empty(z.model, {z.h, z.inter + 1});
       }},
      {"final norm dtype", "DeepSeek-V4 vision final norm weight has the wrong dtype",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.final_norm_weight = s.Empty(z.model, {z.h});
       }},
      {"final norm shape", "DeepSeek-V4 vision final norm weight has the wrong shape",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.final_norm_weight = s.Empty(z.f32, {z.h + 1});
       }},
      {"aligner w1 weight dtype", "DeepSeek-V4 vision aligner w1 weight has the wrong dtype",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.aligner_w1_weight = s.Empty(z.f32, {z.out, z.aligner_input});
       }},
      {"aligner w1 weight shape", "DeepSeek-V4 vision aligner w1 weight has the wrong shape",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.aligner_w1_weight = s.Empty(z.model, {z.out, z.aligner_input + 1});
       }},
      {"aligner w1 bias dtype", "DeepSeek-V4 vision aligner w1 bias has the wrong dtype",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.aligner_w1_bias = s.Empty(z.f32, {z.out});
       }},
      {"aligner w1 bias shape", "DeepSeek-V4 vision aligner w1 bias has the wrong shape",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.aligner_w1_bias = s.Empty(z.model, {z.out + 1});
       }},
      {"aligner w2 weight dtype", "DeepSeek-V4 vision aligner w2 weight has the wrong dtype",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.aligner_w2_weight = s.Empty(z.f32, {z.out, z.out});
       }},
      {"aligner w2 weight shape", "DeepSeek-V4 vision aligner w2 weight has the wrong shape",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.aligner_w2_weight = s.Empty(z.model, {z.out, z.out + 1});
       }},
      {"aligner w2 bias dtype", "DeepSeek-V4 vision aligner w2 bias has the wrong dtype",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.aligner_w2_bias = s.Empty(z.f32, {z.out});
       }},
      {"aligner w2 bias shape", "DeepSeek-V4 vision aligner w2 bias has the wrong shape",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.aligner_w2_bias = s.Empty(z.model, {z.out + 1});
       }},
      // The two remaining ValidateTensor branches, on one representative tensor
      // each: a rank that does not match, and storage that is absent.
      {"patch weight rank", "DeepSeek-V4 vision patch weight has the wrong rank",
       [](DeepSeekV4VisionWeights& w, TensorStore& s, const Sizes& z) {
         w.patch_weight = s.Empty(z.model, {z.h});
       }},
      {"qkv weight contiguity",
       "DeepSeek-V4 vision qkv weight must be contiguous",
       [](DeepSeekV4VisionWeights& w, TensorStore&, const Sizes&) {
         w.blocks[0].qkv_weight.stride[0] += 1;
       }},
      {"aligner w2 weight storage",
       "DeepSeek-V4 vision aligner w2 weight has no storage",
       [](DeepSeekV4VisionWeights& w, TensorStore&, const Sizes&) {
         w.aligner_w2_weight.data = nullptr;
       }},
  };

  for (const Case& one : cases) {
    // As a std::string: doctest stringifies a bare const char* as a pointer,
    // which makes a failing row unidentifiable.
    const std::string label(one.label);
    CAPTURE(label);
    TensorStore store(backend, queue);
    DeepSeekV4VisionWeights weights = Weights(fixture, config, store);
    one.corrupt(weights, store, z);
    bool refused = false;
    try {
      DeepSeekV4Vision model(backend, config, std::move(weights));
    } catch (const std::invalid_argument& error) {
      refused = true;
      CHECK(std::string(error.what()) == std::string(one.message));
    }
    CHECK(refused);
  }
  backend.DestroyQueue(queue);
}

// W2 repair, F6 continued (#2411). THE CAPTURE VALIDATIONS TOO.
//
// `ValidateTensor` has 21 call sites. Fifteen are the weight checks the table
// above drives; five more sit behind `ValidateCaptureTensor`, and the whole body
// of that helper could be replaced by a no-op with the suite staying green. The
// stage goldens pass CORRECT captures, so they exercise the happy path and no
// refusal.
//
// These are gate-facing rather than production-facing, because production passes
// nullptr and copies nothing. That is precisely why they need driving: a capture
// contract nothing checks lets a future parity gate read a wrongly shaped buffer
// and compare whatever happens to be in it.
TEST_CASE("DeepSeek-V4 vision refuses every mis-declared capture tensor") {
  Backend& backend = vt::GetBackend(vt::DeviceType::kCPU);
  Queue queue = backend.CreateQueue();
  const json& fixture = Goldens().at("fixtures").at(0);
  const json& test_case = fixture.at("cases").at(0);
  const DeepSeekV4VisionConfig config = Config(fixture);
  const int64_t height = 2;
  const int64_t width = 5;
  const int64_t patch_rows = height * width;
  const int64_t output_rows = config.aligned_rows(height, width);

  struct Case {
    const char* label;
    const char* message;
    void (*corrupt)(CaptureTensors&, TensorStore&,
                    const DeepSeekV4VisionConfig&, int64_t, int64_t);
  };
  const std::vector<Case> cases = {
      {"patch capture dtype",
       "DeepSeek-V4 vision patch capture has the wrong dtype",
       [](CaptureTensors& c, TensorStore& s, const DeepSeekV4VisionConfig& f,
          int64_t p, int64_t) { c.patch = s.Empty(DType::kF32, {p, f.hidden_size}); }},
      {"patch capture shape",
       "DeepSeek-V4 vision patch capture has the wrong shape",
       [](CaptureTensors& c, TensorStore& s, const DeepSeekV4VisionConfig& f,
          int64_t p, int64_t) {
         c.patch = s.Empty(f.compute_dtype, {p + 1, f.hidden_size});
       }},
      {"patch capture device",
       "DeepSeek-V4 vision patch capture is on the wrong device",
       [](CaptureTensors& c, TensorStore&, const DeepSeekV4VisionConfig&,
          int64_t, int64_t) { c.patch.device.type = vt::DeviceType::kCUDA; }},
      {"block capture dtype",
       "DeepSeek-V4 vision block capture has the wrong dtype",
       [](CaptureTensors& c, TensorStore& s, const DeepSeekV4VisionConfig& f,
          int64_t p, int64_t) {
         c.blocks[1] = s.Empty(DType::kF32, {p, f.hidden_size});
       }},
      {"block capture shape",
       "DeepSeek-V4 vision block capture has the wrong shape",
       [](CaptureTensors& c, TensorStore& s, const DeepSeekV4VisionConfig& f,
          int64_t p, int64_t) {
         c.blocks[0] = s.Empty(f.compute_dtype, {p, f.hidden_size + 1});
       }},
      {"block capture count",
       "DeepSeek-V4 vision block capture count must match depth",
       [](CaptureTensors& c, TensorStore&, const DeepSeekV4VisionConfig&,
          int64_t, int64_t) { c.capture.block_outputs.push_back(&c.patch); }},
      {"final norm capture dtype",
       "DeepSeek-V4 vision final norm capture has the wrong dtype",
       [](CaptureTensors& c, TensorStore& s, const DeepSeekV4VisionConfig& f,
          int64_t p, int64_t) {
         c.final_norm = s.Empty(DType::kF32, {p, f.hidden_size});
       }},
      {"final norm capture shape",
       "DeepSeek-V4 vision final norm capture has the wrong shape",
       [](CaptureTensors& c, TensorStore& s, const DeepSeekV4VisionConfig& f,
          int64_t p, int64_t) {
         c.final_norm = s.Empty(f.compute_dtype, {p + 1, f.hidden_size});
       }},
      {"unfold capture dtype",
       "DeepSeek-V4 vision unfold capture has the wrong dtype",
       [](CaptureTensors& c, TensorStore& s, const DeepSeekV4VisionConfig& f,
          int64_t, int64_t o) {
         c.unfold = s.Empty(DType::kF32, {o, f.aligner_input_size()});
       }},
      {"unfold capture shape",
       "DeepSeek-V4 vision unfold capture has the wrong shape",
       [](CaptureTensors& c, TensorStore& s, const DeepSeekV4VisionConfig& f,
          int64_t, int64_t o) {
         c.unfold = s.Empty(f.compute_dtype, {o, f.aligner_input_size() + 1});
       }},
      {"aligner hidden capture dtype",
       "DeepSeek-V4 vision aligner hidden capture has the wrong dtype",
       [](CaptureTensors& c, TensorStore& s, const DeepSeekV4VisionConfig& f,
          int64_t, int64_t o) {
         c.aligner_hidden = s.Empty(DType::kF32, {o, f.output_size});
       }},
      {"aligner hidden capture shape",
       "DeepSeek-V4 vision aligner hidden capture has the wrong shape",
       [](CaptureTensors& c, TensorStore& s, const DeepSeekV4VisionConfig& f,
          int64_t, int64_t o) {
         c.aligner_hidden = s.Empty(f.compute_dtype, {o + 1, f.output_size});
       }},
      {"aligner GELU capture dtype",
       "DeepSeek-V4 vision aligner GELU capture has the wrong dtype",
       [](CaptureTensors& c, TensorStore& s, const DeepSeekV4VisionConfig& f,
          int64_t, int64_t o) {
         c.gelu = s.Empty(DType::kF32, {o, f.output_size});
       }},
      {"aligner GELU capture shape",
       "DeepSeek-V4 vision aligner GELU capture has the wrong shape",
       [](CaptureTensors& c, TensorStore& s, const DeepSeekV4VisionConfig& f,
          int64_t, int64_t o) {
         c.gelu = s.Empty(f.compute_dtype, {o, f.output_size + 1});
       }},
  };

  for (const Case& one : cases) {
    const std::string label(one.label);
    CAPTURE(label);
    TensorStore store(backend, queue);
    DeepSeekV4Vision model(backend, config, Weights(fixture, config, store));
    Tensor patches = store.Make(test_case.at("patches"), config.compute_dtype,
                                {patch_rows, config.patch_dim()});
    Tensor output = store.Empty(config.compute_dtype,
                                {output_rows, config.output_size});
    CaptureTensors captures(store, config, patch_rows, output_rows);
    one.corrupt(captures, store, config, patch_rows, output_rows);
    bool refused = false;
    try {
      model.Forward(queue, output, patches, height, width, &captures.capture);
    } catch (const std::invalid_argument& error) {
      refused = true;
      CHECK(std::string(error.what()) == std::string(one.message));
    }
    CHECK(refused);
  }
  backend.DestroyQueue(queue);
}

// W7-CUDA repair (#2411). THE PER-BLOCK STAGING IS GATEABLE ON A CPU HOST, and
// the `## Owed` entry that recorded it as catchable only on a leased device was
// wrong.
//
// `EnsureResident` stages on ONE condition -- `queue.device != weights.device`
// -- and stages through the backend the tower was CONSTRUCTED with. Neither is a
// CUDA predicate. `vt::Queue` is a plain aggregate, so a non-CPU queue can be
// built by hand, and `vt::Backend` has six pure virtuals, so a host-memory fake
// can answer for a non-CPU device type. Together those give the staging loop a
// real run on this box and let the staged copies be COUNTED.
//
// WHAT THE OLD ENTRY GOT RIGHT, and what this keeps: making `EnsureResident` a
// no-op leaves every OTHER CPU case green, because it returns on its first line
// for a CPU queue whose weights are already host-resident. That is precisely why
// this case hands it a queue on a DIFFERENT device -- the only shape in which
// the body executes at all.
//
// WHY IT THROWS, and why that is the point rather than a weakness. `Forward`
// calls `EnsureResident` FIRST, before any I/O validation. The patches and the
// output stay on the host here, so the forward refuses by name immediately after
// staging. The message is asserted, so a case that stopped reaching the staging
// loop for some earlier reason cannot pass quietly. Nothing after the refusal is
// measured, and nothing needs to be: the staging is already done and counted.
namespace {

class StagingCountingBackend final : public Backend {
 public:
  void* Alloc(size_t bytes) override {
    ++allocations;
    return std::malloc(bytes == 0 ? 1 : bytes);
  }
  void Free(void* pointer) override { std::free(pointer); }
  void Memset(Queue&, void* pointer, int value, size_t bytes) override {
    std::memset(pointer, value, bytes);
  }
  void Copy(Queue&, void* destination, const void* source, size_t bytes) override {
    ++copies;
    std::memcpy(destination, source, bytes);
  }
  Queue CreateQueue() override {
    return Queue{vt::Device{vt::DeviceType::kXPU, 0}, nullptr};
  }
  bool UnifiedMemory() const override { return true; }

  size_t allocations = 0;
  size_t copies = 0;
};

}  // namespace

TEST_CASE("DeepSeek-V4 vision stages every per-block weight to the queue's device") {
  // The tower's staged tensor census, by construction rather than by
  // observation: `patch_weight` and `patch_bias`, then eight per block, then the
  // final norm and the aligner's four. A block the loop skips costs exactly
  // eight.
  constexpr size_t kFixedStagedTensors = 7;
  constexpr size_t kPerBlockStagedTensors = 8;

  Backend& host = vt::GetBackend(vt::DeviceType::kCPU);
  Queue host_queue = host.CreateQueue();
  const json& fixture = Goldens().at("fixtures").at(0);
  const json& test_case = fixture.at("cases").at(0);

  struct Reading {
    size_t allocations = 0;
    size_t copies = 0;
  };

  auto measure = [&](int64_t depth) {
    DeepSeekV4VisionConfig config = Config(fixture);
    // The weights are built on the HOST queue, so `weights.patch_weight.device`
    // is kCPU and the staging condition is genuinely unmet before the call.
    TensorStore store(host, host_queue);
    DeepSeekV4VisionWeights weights = Weights(fixture, config, store);
    while (static_cast<int64_t>(weights.blocks.size()) < depth) {
      weights.blocks.push_back(weights.blocks[0]);
    }
    weights.blocks.resize(static_cast<size_t>(depth));
    config.depth = depth;

    StagingCountingBackend device;
    Reading reading;
    {
      DeepSeekV4Vision model(device, config, std::move(weights));
      Queue device_queue{vt::Device{vt::DeviceType::kXPU, 0}, nullptr};
      Tensor patches = store.Make(test_case.at("patches"), config.compute_dtype,
                                  {10, config.patch_dim()});
      Tensor output = store.Empty(config.compute_dtype, {2, config.output_size});
      // Staged, THEN refused -- and the refusal is named, so this cannot pass by
      // failing somewhere earlier.
      CHECK_THROWS_WITH_AS(
          model.Forward(device_queue, output, patches, 2, 5),
          "DeepSeek-V4 vision patches and queue must share one device",
          std::invalid_argument);
      reading.allocations = device.allocations;
      reading.copies = device.copies;
    }
    return reading;
  };

  const Reading at_one = measure(1);
  const Reading at_two = measure(2);

  // Every staged tensor is one Alloc and one Copy, so the two counters agree and
  // a defect that dropped either half is visible on its own.
  CHECK(at_one.allocations == kFixedStagedTensors + kPerBlockStagedTensors);
  CHECK(at_one.copies == at_one.allocations);
  CHECK(at_two.allocations == kFixedStagedTensors + 2 * kPerBlockStagedTensors);
  CHECK(at_two.copies == at_two.allocations);

  // THE BOUND THAT SEES A PER-BLOCK MISS. A loop that stages only block 0 reads
  // 15 at both depths, so the absolute counts above red AND this slope goes to
  // zero. Asserted separately because a future tower with a different fixed
  // census would still have to stage eight tensors per block.
  REQUIRE(at_two.allocations >= at_one.allocations);
  CHECK(at_two.allocations - at_one.allocations == kPerBlockStagedTensors);

  host.DestroyQueue(host_queue);
}
