// Ported from: vllm/v1/core/block_pool.py @ e24d1b24
// See src/vllm/v1/core/block_pool.h for scope, the classic-vs-e24d1b24 version
// note, and recorded deferrals / deviations.
#include "vllm/v1/core/block_pool.h"

#include <cassert>
#include <stdexcept>
#include <utility>

#include "vllm/v1/request.h"

namespace vllm::v1 {
namespace {

// Build num_gpu_blocks KVCacheBlocks with block_id = 0..n-1. Reserve up front so
// the buffer never reallocates: FreeKVCacheBlockQueue and cached_block_hash_to_block
// hold raw pointers into these elements, so their addresses must stay stable.
std::vector<KVCacheBlock> MakeBlocks(int64_t num_gpu_blocks) {
  std::vector<KVCacheBlock> blocks;
  if (num_gpu_blocks > 0) {
    blocks.reserve(static_cast<size_t>(num_gpu_blocks));
    for (int64_t idx = 0; idx < num_gpu_blocks; ++idx) {
      blocks.emplace_back(static_cast<int>(idx));
    }
  }
  return blocks;
}

// A KVCacheBlock* view over `blocks`, used to seed FreeKVCacheBlockQueue.
std::vector<KVCacheBlock*> BlockPtrs(std::vector<KVCacheBlock>& blocks) {
  std::vector<KVCacheBlock*> ptrs;
  ptrs.reserve(blocks.size());
  for (auto& block : blocks) {
    ptrs.push_back(&block);
  }
  return ptrs;
}

}  // namespace

BlockPool::BlockPool(int64_t num_gpu_blocks, bool enable_caching,
                     bool enable_kv_cache_events)
    : num_gpu_blocks(num_gpu_blocks),
      enable_caching(enable_caching),
      blocks(MakeBlocks(num_gpu_blocks)),
      free_block_queue(BlockPtrs(blocks)),
      null_block(nullptr),
      enable_kv_cache_events(enable_kv_cache_events) {
  assert(num_gpu_blocks > 0);

  // To represent a placeholder block with block_id=0. The ref_cnt of null_block
  // is not maintained; it is popped out of the free queue here so it can never
  // be allocated. (Special care is needed elsewhere to avoid freeing it.)
  null_block = free_block_queue.popleft();
  null_block->is_null = true;
}

std::optional<std::vector<KVCacheBlock*>> BlockPool::get_cached_block(
    const BlockHash& block_hash, const std::vector<int>& kv_cache_group_ids) {
  std::vector<KVCacheBlock*> cached_blocks;
  for (int group_id : kv_cache_group_ids) {
    const BlockHashWithGroupId block_hash_with_group_id =
        make_block_hash_with_group_id(block_hash,
                                      static_cast<uint32_t>(group_id));
    auto it = cached_block_hash_to_block.find(block_hash_with_group_id);
    if (it == cached_block_hash_to_block.end() || it->second.empty()) {
      return std::nullopt;
    }
    // If there are duplicated blocks, return the first block in the cache.
    cached_blocks.push_back(it->second.begin()->second);
  }
  return cached_blocks;
}

void BlockPool::cache_full_blocks(const Request& request,
                                  const std::vector<KVCacheBlock*>& blocks_arg,
                                  std::vector<BlockHash>& block_hashes,
                                  int num_cached_blocks, int num_full_blocks,
                                  int block_size, int kv_cache_group_id,
                                  const HashFn& hash_fn) {
  if (num_cached_blocks == num_full_blocks) {
    return;
  }
  // new_full_blocks = blocks[num_cached_blocks:num_full_blocks]
  // (kept as an index range into blocks_arg to avoid a copy).
  assert(static_cast<int>(block_hashes.size()) >= num_cached_blocks);
  // new_block_hashes = block_hashes[num_cached_blocks:] — a fixed-length COPY
  // (Python's slice). The else branch below appends to block_hashes (the
  // caller's list), NOT to this copy, so this length stays fixed.
  const int num_precomputed_new =
      static_cast<int>(block_hashes.size()) - num_cached_blocks;

  // Update the new blocks with the block hashes through the chain.
  std::optional<BlockHash> prev_block_hash_value = std::nullopt;
  if (num_cached_blocks != 0) {
    KVCacheBlock* prev_block = blocks_arg[num_cached_blocks - 1];
    assert(prev_block->block_hash().has_value());
    prev_block_hash_value = get_block_hash(prev_block->block_hash().value());
  }

  // all_token_ids = prompt + output (the T0 no-prompt-embeds path). Only read by
  // the rare else branch (a trailing block whose hash was not precomputed).
  std::vector<int32_t> all_token_ids = request.prompt_token_ids;
  all_token_ids.insert(all_token_ids.end(), request.output_token_ids.begin(),
                       request.output_token_ids.end());

  const int num_new_full = num_full_blocks - num_cached_blocks;
  for (int i = 0; i < num_new_full; ++i) {
    KVCacheBlock* blk = blocks_arg[num_cached_blocks + i];
    assert(!blk->block_hash().has_value());

    BlockHash block_hash;
    if (i < num_precomputed_new) {
      // The block hash may already be computed in get_computed_blocks if the
      // tokens are not generated by this request (prompt tokens, or previously
      // generated tokens after preemption). Reuse the precomputed hash.
      block_hash = block_hashes[num_cached_blocks + i];
    } else {
      // Otherwise compute the block hash and cache it on the request in case it
      // is preempted in the future.
      const int blk_idx = num_cached_blocks + i;
      const int start_token_idx = blk_idx * block_size;
      const int end_token_idx = (blk_idx + 1) * block_size;
      assert(end_token_idx <= static_cast<int>(all_token_ids.size()) &&
             "Not enough tokens for a full block in cache_full_blocks");
      std::vector<int32_t> block_tokens(all_token_ids.begin() + start_token_idx,
                                        all_token_ids.begin() + end_token_idx);
      // Generate extra keys for block hashing (T0 Request: always none).
      std::pair<ExtraKeys, int> extra =
          generate_block_hash_extra_keys(request, start_token_idx, end_token_idx, -1);
      block_hash = hash_block_tokens(hash_fn, prev_block_hash_value, block_tokens,
                                     extra.first);
      block_hashes.push_back(block_hash);
    }

    // Update and add the full block to the cache.
    const BlockHashWithGroupId block_hash_with_group_id =
        make_block_hash_with_group_id(block_hash,
                                      static_cast<uint32_t>(kv_cache_group_id));
    blk->set_block_hash(block_hash_with_group_id);
    cached_block_hash_to_block[block_hash_with_group_id][blk->block_id] = blk;
    // enable_kv_cache_events (BlockStored emission) — DEFERRED (see header).
    prev_block_hash_value = block_hash;
  }
}

std::vector<KVCacheBlock*> BlockPool::get_new_blocks(int num_blocks) {
  if (num_blocks > get_num_free_blocks()) {
    throw std::runtime_error("Cannot get free blocks from the pool");
  }

  std::vector<KVCacheBlock*> ret;
  ret.reserve(static_cast<size_t>(num_blocks));
  int idx = 0;
  while (idx < num_blocks) {
    // First allocate blocks.
    KVCacheBlock* curr_block = free_block_queue.popleft();
    assert(curr_block->ref_cnt == 0);

    // If the block is cached, evict it.
    if (enable_caching) {
      _maybe_evict_cached_block(curr_block);
    }

    curr_block->incr_ref();
    ret.push_back(curr_block);
    ++idx;
  }
  return ret;
}

bool BlockPool::_maybe_evict_cached_block(KVCacheBlock* block) {
  if (!block->block_hash().has_value()) {
    // The block doesn't have a hash, eviction is not needed.
    return false;
  }
  const BlockHashWithGroupId block_hash = block->block_hash().value();
  auto it = cached_block_hash_to_block.find(block_hash);
  if (it == cached_block_hash_to_block.end()) {
    // block_hash not found in cached_block_hash_to_block, eviction not needed.
    return false;
  }
  block->reset_hash();
  it->second.erase(block->block_id);
  if (it->second.empty()) {
    cached_block_hash_to_block.erase(it);
  }
  // enable_kv_cache_events (BlockRemoved emission) — DEFERRED (see header).
  return true;
}

void BlockPool::touch(const std::vector<KVCacheBlock*>& blocks_arg) {
  for (KVCacheBlock* block : blocks_arg) {
    // ref_cnt=0 means this block is in the free list (i.e. an eviction
    // candidate), so remove it.
    if (block->ref_cnt == 0 && !block->is_null) {
      free_block_queue.remove(block);
    }
    block->incr_ref();
  }
}

void BlockPool::free_blocks(const std::vector<KVCacheBlock*>& ordered_blocks) {
  for (KVCacheBlock* block : ordered_blocks) {
    block->decr_ref();
    if (block->ref_cnt == 0 && !block->is_null) {
      free_block_queue.append(block);
    }
  }
}

bool BlockPool::reset_prefix_cache() {
  const int64_t num_used_blocks = num_gpu_blocks - get_num_free_blocks();
  if (num_used_blocks != 1) {  // The null block is always marked as used.
    // Some blocks are still in use; cannot reset (upstream logs a warning).
    return false;
  }

  // Remove all hashes so that no new blocks will hit.
  cached_block_hash_to_block.clear();

  // Remove all hashes from all blocks.
  for (KVCacheBlock& block : blocks) {
    block.reset_hash();
  }

  // enable_kv_cache_events (AllBlocksCleared emission) — DEFERRED (see header).
  return true;
}

int BlockPool::get_num_free_blocks() const {
  return free_block_queue.num_free_blocks;
}

double BlockPool::get_usage() const {
  // Subtract 1 to account for the null block.
  const int64_t total_gpu_blocks = num_gpu_blocks - 1;
  if (total_gpu_blocks == 0) {
    return 0.0;
  }
  return 1.0 - (static_cast<double>(get_num_free_blocks()) /
                static_cast<double>(total_gpu_blocks));
}

std::vector<KVCacheEvent> BlockPool::take_events() {
  // DEFERRED: KV-cache events are not emitted (see file header). Upstream would
  // atomically drain kv_event_queue here.
  if (!enable_kv_cache_events) {
    return {};
  }
  std::vector<KVCacheEvent> events = std::move(kv_event_queue);
  kv_event_queue.clear();
  return events;
}

}  // namespace vllm::v1
